/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.ckeditor5StyleSettingsSummary = {
    attach: function attach() {
      $('[data-ckeditor5-plugin-id="ckeditor5_style"]').drupalSetSummary(function (context) {
        var stylesElement = document.querySelector('[data-drupal-selector="edit-editor-settings-plugins-ckeditor5-style-styles"]');
        var styles = stylesElement ? stylesElement.value.trim() : '';

        if (styles.length === 0) {
          return Drupal.t('No styles configured');
        }

        var count = styles.split('\n').length;
        return Drupal.t('@count styles configured', {
          '@count': count
        });
      });
    }
  };
})(jQuery, Drupal);