/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal, once, drupalSettings) {
  Drupal.behaviors.ckEditor5StylesheetsWarn = {
    attach: function attach() {
      var editorSelect = once('editor-select-stylesheet-warning', '[data-drupal-selector="filter-format-edit-form"] [data-drupal-selector="edit-editor-editor"], [data-drupal-selector="filter-format-add-form"] [data-drupal-selector="edit-editor-editor"]');

      if (typeof editorSelect[0] !== 'undefined' && drupalSettings.ckeditor5 && drupalSettings.ckeditor5.ckeditor_stylesheets_warning) {
        var select = editorSelect[0];
        var selectMessageContainer = document.createElement('div');
        select.parentNode.insertBefore(selectMessageContainer, select);
        var selectMessages = new Drupal.Message(selectMessageContainer);

        var addCkeditorStylesheetsWarning = function addCkeditorStylesheetsWarning() {
          selectMessages.add(drupalSettings.ckeditor5.ckeditor_stylesheets_warning, {
            type: 'warning',
            id: 'ckeditor_stylesheets_warning'
          });
        };

        var updateWarningStatus = function updateWarningStatus() {
          if (select.value === 'ckeditor5' && !select.hasAttribute('data-error-switching-to-ckeditor5')) {
            addCkeditorStylesheetsWarning();
          } else if (selectMessages.select('ckeditor_stylesheets_warning')) {
            selectMessages.remove('ckeditor_stylesheets_warning');
          }
        };

        updateWarningStatus();
        var editorSelectObserver = new MutationObserver(function (mutations) {
          for (var i = 0; i < mutations.length; i++) {
            var switchToCKEditor5Complete = mutations[i].type === 'attributes' && mutations[i].attributeName === 'disabled' && !select.disabled;
            var fixedErrorsPreventingSwitchToCKEditor5 = mutations[i].type === 'attributes' && mutations[i].attributeName === 'data-error-switching-to-ckeditor5' && !select.hasAttribute('data-error-switching-to-ckeditor5');

            if (switchToCKEditor5Complete || fixedErrorsPreventingSwitchToCKEditor5) {
              updateWarningStatus();
            }
          }
        });
        editorSelectObserver.observe(select, {
          attributes: true
        });
      }
    }
  };
})(Drupal, once, drupalSettings);