/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal, once, drupalSettings) {
  Drupal.behaviors.ckEditor5StylesheetsWarn = {
    attach: function attach() {
      var editorSelect = once('editor-select-stylesheet-warning', '[data-drupal-selector="filter-format-edit-form"] [data-drupal-selector="edit-editor-editor"], [data-drupal-selector="filter-format-add-form"] [data-drupal-selector="edit-editor-editor"]');

      if (typeof editorSelect[0] !== 'undefined' && drupalSettings.ckeditor5 && drupalSettings.ckeditor5.ckeditor_stylesheets_warning) {
        var select = editorSelect[0];
        var selectMessageContainer = document.createElement('div');
        select.parentNode.insertBefore(selectMessageContainer, select);
        var selectMessages = new Drupal.Message(selectMessageContainer);
        var editorSettings = document.querySelector('[data-drupal-selector="editor-settings-wrapper"]');

        var addCkeditorStylesheetsWarning = function addCkeditorStylesheetsWarning() {
          selectMessages.add(drupalSettings.ckeditor5.ckeditor_stylesheets_warning, {
            type: 'warning'
          });
        };

        var updateWarningStatus = function updateWarningStatus() {
          if (select.value === 'ckeditor5' && !select.classList.contains('error')) {
            addCkeditorStylesheetsWarning();
          } else {
            editorSettings.hidden = false;
            selectMessages.clear();
          }
        };

        updateWarningStatus();
        var editorSelectObserver = null;
        select.addEventListener('change', function () {
          if (editorSelectObserver) {
            editorSelectObserver = new MutationObserver(function (mutations) {
              for (var i = 0; i < mutations.length; i++) {
                if (mutations[i].type === 'attributes' && mutations[i].attributeName === 'disabled' && !select.disabled) {
                  updateWarningStatus();
                  editorSelectObserver.disconnect();
                }
              }
            });
          }

          editorSelectObserver.observe(select, {
            attributes: true
          });
        });
      }
    }
  };
})(Drupal, once, drupalSettings);