/**
 * DO NOT EDIT THIS FILE.
 * See the following change record for more information,
 * https://www.drupal.org/node/2815083
 * @preserve
 **/

(function ($, Drupal) {
  Drupal.behaviors.blockContentFormSummaries = {
    attach: function attach(context) {
      var $context = $(context);

      $context.find('.block-content-form-author').drupalSetSummary(function (context) {
        var $authorContext = $(context);
        var name = $authorContext.find('.field--name-uid input').val();

        if (name) {
          return Drupal.t('By @name', {'@name': name});
        }
      });
    }
  };
})(jQuery, Drupal);
