/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, _ref, once) {
  var behaviors = _ref.behaviors;
  behaviors.autocompleteShimTest = {
    attach: function attach() {
      once('autocomplete_shim_test', '#autocomplete, #autocomplete-contenteditable, #autocomplete-textarea').forEach(function (element) {
        return $(element).autocomplete();
      });
    }
  };
})(jQuery, Drupal, once);