/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, _ref, once) {
  var behaviors = _ref.behaviors;
  behaviors.autocompleteShimTestMixedJquery = {
    attach: function attach() {
      once('autocomplete_shim_test_j', '#autocomplete').forEach(function (element) {
        return $(element).autocomplete();
      });
      once('autocomplete_shim_test_a', '#direct-jquery, #autocomplete-contenteditable, #autocomplete-textarea').forEach(Drupal.Autocomplete.initialize);
    }
  };
})(jQuery, Drupal, once);