<?php

/**
 * @file
 * Install hooks for test profile.
 */

use Drupal\Core\Extension\Requirement\RequirementSeverity;

/**
 * Implements hook_requirements().
 */
function testing_requirements_requirements($phase) {
  $requirements = [];

  if ($phase === 'install') {
    $requirements['testing_requirements'] = [
      'title' => t('Testing requirements'),
      'severity' => RequirementSeverity::Error,
      'description' => t('Testing requirements failed requirements.'),
    ];
  }

  return $requirements;
}
