<?php

/**
 * @file
 * Install, update and uninstall functions for File module.
 */

/**
 * Implements hook_schema().
 */
function file_schema() {
  $schema['file_usage'] = [
    'description' => 'Track where a file is used.',
    'fields' => [
      'fid' => [
        'description' => 'File ID.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'module' => [
        'description' => 'The name of the module that is using the file.',
        'type' => 'varchar_ascii',
        'length' => DRUPAL_EXTENSION_NAME_MAX_LENGTH,
        'not null' => TRUE,
        'default' => '',
      ],
      'type' => [
        'description' => 'The name of the object type in which the file is used.',
        'type' => 'varchar_ascii',
        'length' => 64,
        'not null' => TRUE,
        'default' => '',
      ],
      'id' => [
        'description' => 'The primary key of the object using the file.',
        'type' => 'varchar_ascii',
        'length' => 64,
        'not null' => TRUE,
        'default' => 0,
      ],
      'count' => [
        'description' => 'The number of times this file is used by this object.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ],
    ],
    'primary key' => ['fid', 'type', 'id', 'module'],
    'indexes' => [
      'type_id' => ['type', 'id'],
      'fid_count' => ['fid', 'count'],
      'fid_module' => ['fid', 'module'],
    ],
  ];
  return $schema;
}

/**
 * Implements hook_requirements().
 *
 * Display information about getting upload progress bars working.
 */
function file_requirements($phase) {
  $requirements = [];

  // Check the server's ability to indicate upload progress.
  if ($phase == 'runtime') {
    $description = NULL;
    $severity = NULL;
    $implementation = file_progress_implementation();
    // The environment variable might be missing. Fallback to an empty string to
    // prevent passing NULL to preg_match(), a few lines later.
    $server_software = \Drupal::request()->server->get('SERVER_SOFTWARE', '');

    // Test the web server identity.
    if (preg_match("/Nginx/i", $server_software)) {
      $is_nginx = TRUE;
      $is_apache = FALSE;
      $fastcgi = FALSE;
    }
    elseif (preg_match("/Apache/i", $server_software)) {
      $is_nginx = FALSE;
      $is_apache = TRUE;
      $fastcgi = str_contains($server_software, 'mod_fastcgi') || str_contains($server_software, 'mod_fcgi');
    }
    else {
      $is_nginx = FALSE;
      $is_apache = FALSE;
      $fastcgi = FALSE;
    }

    if (!$is_apache && !$is_nginx) {
      $value = t('Not enabled');
      $description = t('Your server is not capable of displaying file upload progress. File upload progress requires an Apache server running PHP with mod_php or Nginx with PHP-FPM.');
    }
    elseif ($fastcgi) {
      $value = t('Not enabled');
      $description = t('Your server is not capable of displaying file upload progress. File upload progress requires PHP be run with mod_php or PHP-FPM and not as FastCGI.');
    }
    elseif (!$implementation) {
      $value = t('Not enabled');
      $description = t('Your server is capable of displaying file upload progress, but does not have the required libraries. It is recommended to install the <a href="http://pecl.php.net/package/uploadprogress">PECL uploadprogress library</a>.');
    }
    elseif ($implementation == 'uploadprogress') {
      $value = t('Enabled (<a href="http://pecl.php.net/package/uploadprogress">PECL uploadprogress</a>)');
    }
    if ($implementation == 'session') {
      $value = t('Enabled (<a href="http://php.net/manual/en/session.upload-progress.php">PHP session upload progress</a>)');
      $session_manager = \Drupal::service('session_manager');
      if (!method_exists($session_manager, 'getPHPSessionName') || $session_manager->getPHPSessionName() != session_name()) {
        $description = [
          [
            '#markup' => t('The <a href=":url">PHP session name</a> must be set to %session_name before Drupal starts in order to store file upload progress. It is currently set to %php_session_name.', [
              ':url' => 'http://php.net/manual/en/session.configuration.php#ini.session.name',
              '%session_name' => session_name(),
              '%php_session_name' => $session_manager->getPHPSessionName(),
            ]),
          ],
        ];
        // Tell users how to configure the PHP session name, if we can.
        if (substr(PHP_SAPI, 0, 6) == 'apache') {
          // Settings can be configured in a .htaccess file if PHP is running as
          // an Apache module.
          $description[] = [
            '#prefix' => ' ',
            '#markup' => t('Add <code>php_value session.name @session_name</code> to the PHP @php-version settings of the .htaccess file in your Drupal root folder.', [
              '@session_name' => session_name(),
              '@php-version' => PHP_MAJOR_VERSION,
            ]),
          ];
        }
        elseif (substr(PHP_SAPI, 0, 3) == 'cgi') {
          // PHP running as CGI cannot get settings from .htaccess files, but
          // since 5.3.0 it supports .user.ini files.
          $description[] = [
            '#prefix' => ' ',
            '#markup' => t('Add <code>session.name=@session_name</code> to a .<a href=":url">user.ini</a> file in your Drupal root folder.', [
              '@session_name' => session_name(),
              ':url' => 'http://php.net/manual/en/configuration.file.per-user.php',
            ]),
          ];
        }
      }
      if (method_exists($session_manager, 'getPHPSessionName') && $session_manager->getPHPSessionName() != session_name()) {
        $severity = REQUIREMENT_WARNING;
      }
    }
    $requirements['file_progress'] = [
      'title' => t('Upload progress'),
      'value' => $value,
      'description' => $description,
      'severity' => $severity,
    ];
  }

  return $requirements;
}

/**
 * Implements hook_update_last_removed().
 */
function file_update_last_removed() {
  return 8700;
}
