<?php

/**
 * @file
 * Install, update and uninstall functions for File module.
 */

/**
 * Implements hook_schema().
 */
function file_schema(): array {
  $schema['file_usage'] = [
    'description' => 'Track where a file is used.',
    'fields' => [
      'fid' => [
        'description' => 'File ID.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'module' => [
        'description' => 'The name of the module that is using the file.',
        'type' => 'varchar_ascii',
        'length' => DRUPAL_EXTENSION_NAME_MAX_LENGTH,
        'not null' => TRUE,
        'default' => '',
      ],
      'type' => [
        'description' => 'The name of the object type in which the file is used.',
        'type' => 'varchar_ascii',
        'length' => 64,
        'not null' => TRUE,
        'default' => '',
      ],
      'id' => [
        'description' => 'The primary key of the object using the file.',
        'type' => 'varchar_ascii',
        'length' => 64,
        'not null' => TRUE,
        'default' => 0,
      ],
      'count' => [
        'description' => 'The number of times this file is used by this object.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ],
    ],
    'primary key' => ['fid', 'type', 'id', 'module'],
    'indexes' => [
      'type_id' => ['type', 'id'],
      'fid_count' => ['fid', 'count'],
      'fid_module' => ['fid', 'module'],
    ],
  ];
  return $schema;
}

/**
 * Implements hook_update_last_removed().
 */
function file_update_last_removed(): int {
  return 8700;
}

/**
 * Add additional settings for the "file_video" formatter.
 */
function file_update_8001() {
  // Load all "file" field storage instances:
  $fieldInstances = \Drupal::entityTypeManager()
    ->getStorage('field_config')
    ->loadByProperties(['field_type' => 'file']);

  foreach ($fieldInstances as $fieldInstance) {
    $properties = [
      'targetEntityType' => $fieldInstance->getEntityTypeId(),
      'bundle' => $fieldInstance->bundle(),
    ];
    // @todo Only get form displays, using the "file_video" formatter here:
    if ($form_displays = \Drupal::entityTypeManager()->getStorage('entity_form_display')->loadByProperties($properties)) {
      foreach ($form_displays as $form_display) {
        if ($component = $form_display->getComponent($fieldInstance->getName())) {
          $form_display->setComponent($fieldInstance->getName(), array_merge_recursive(
            $component,
            [
            'settings' => [
              'poster' => '',
              'poster_image_style' => '',
              'transcript' => '',
            ],
          ]))->save();
        }
      }
    }
  }
}
