<?php

/**
 * @file
 * Install, update and uninstall functions for the field module.
 */

/**
 * Implements hook_update_last_removed().
 */
function field_update_last_removed(): int {
  return 8500;
}

/**
 * Adds default config for Show add more button for multivalued fields.
 */
function field_update_9001(): void {
  // Get all the fields which are multivalued but not unlimited cardinality.
  $query = \Drupal::entityQuery('field_storage_config')
    ->condition('cardinality', 1, '>')
    ->accessCheck(TRUE);
  $results = $query->execute();

  if (!empty($results)) {
    $bundle_field_maps = \Drupal::service('keyvalue')
      ->get('entity.definitions.bundle_field_map')
      ->getAll();
    // Get all the bundles for which the multivalued fields are configured.
    foreach ($bundle_field_maps as $entity_type_id => $bundle_field_map) {
      foreach ($bundle_field_map as $field_name => $map_entry) {
        if (in_array("$entity_type_id.$field_name", $results)) {
          if (!isset($fieldMap[$entity_type_id][$field_name])) {
            $fieldMap["$entity_type_id.$field_name"] = $map_entry;
          }
          else {
            $fieldMap["$entity_type_id.$field_name"]['bundles']
            += $map_entry['bundles'];
          }
        }
      }
    }
    if (!empty($fieldMap)) {
      foreach ($fieldMap as $field_storage => $array_bundles) {
        [$entity_type, $field_name] = explode('.', $field_storage);
        foreach ($array_bundles['bundles'] as $bundle) {
          // Update Show add more for the fields in entity form display.
          $entity_form_display = \Drupal::entityTypeManager()
            ->getStorage('entity_form_display')
            ->load("$entity_type.$bundle.default");
          if ($component = $entity_form_display->getComponent($field_name)) {
            $component['settings']['add_more'] = FALSE;
            $entity_form_display->setComponent($field_name, $component)->save();
            \Drupal::logger('field')
              ->notice("Show add more configured FALSE for $field_name");
          }
        }
      }
    }
  }
}
