<?php

/**
 * @file
 * Contains install and update functions for Automatic Updates.
 */

declare(strict_types=1);

use Drupal\auto_updates\CronUpdateRunner;
use Drupal\auto_updates\UpdateStage;
use Drupal\auto_updates\Validation\StatusCheckRequirements;
use Drupal\system\SystemManager;

/**
 * Implements hook_uninstall().
 */
function auto_updates_uninstall() {
  \Drupal::service(UpdateStage::class)->destroy(TRUE);
}

/**
 * Implements hook_requirements().
 */
function auto_updates_requirements($phase) {
  if ($phase === 'runtime') {
    // Check that site is ready to perform automatic updates.
    /** @var \Drupal\auto_updates\Validation\StatusCheckRequirements $status_check_requirement */
    $status_check_requirement = \Drupal::classResolver(StatusCheckRequirements::class);
    $requirements = $status_check_requirement->getRequirements();

    // Check that site has cron updates enabled or not.
    // @todo Remove in https://www.drupal.org/project/auto_updates/issues/3284443
    if (\Drupal::configFactory()->get('auto_updates.settings')->get('unattended.level') !== CronUpdateRunner::DISABLED) {
      $requirements['auto_updates_cron'] = [
        'title' => t('Cron installs updates automatically'),
        'severity' => SystemManager::REQUIREMENT_WARNING,
        'value' => t('Enabled. This is NOT an officially supported feature of the Automatic Updates module at this time. Use at your own risk.'),
      ];
    }
    return $requirements;
  }
}
