<?php

declare(strict_types=1);

namespace Drupal\Tests\pgsql\Kernel\pgsql;

use Drupal\Core\Database\Schema\Index;
use Drupal\Core\Database\Exception\SchemaIndexOnJsonFieldUnsupportedException;
use Drupal\KernelTests\Core\Database\AutoGeneratedIndexTestTrait;
use Drupal\KernelTests\Core\Database\DriverSpecificSchemaTestBase;
use Drupal\pgsql\Schema\IndexType;

// cSpell:ignore attname attnum attrelid indexdef objid refobjid refobjsubid
// cspell:ignore regclass relkind relname seqscan tsvector

/**
 * Tests schema API for the PostgreSQL driver.
 *
 * @group Database
 */
class SchemaTest extends DriverSpecificSchemaTestBase {

  use AutoGeneratedIndexTestTrait;

  /**
   * {@inheritdoc}
   */
  public function checkSchemaComment(string $description, string $table, ?string $column = NULL): void {
    $this->assertSame($description, $this->schema->getComment($table, $column), 'The comment matches the schema description.');
  }

  /**
   * {@inheritdoc}
   */
  protected function checkSequenceRenaming(string $tableName): void {
    // For PostgreSQL, we also need to check that the sequence has been renamed.
    // The initial name of the sequence has been generated automatically by
    // PostgreSQL when the table was created, however, on subsequent table
    // renames the name is generated by Drupal and can not be easily
    // re-constructed. Hence we can only check that we still have a sequence on
    // the new table name.
    $sequenceExists = (bool) $this->connection->query("SELECT pg_get_serial_sequence('{" . $tableName . "}', 'id')")->fetchField();
    $this->assertTrue($sequenceExists, 'Sequence was renamed.');

    // Rename the table again and repeat the check.
    $anotherTableName = strtolower($this->getRandomGenerator()->name(63 - strlen($this->getDatabasePrefix())));
    $this->schema->renameTable($tableName, $anotherTableName);

    $sequenceExists = (bool) $this->connection->query("SELECT pg_get_serial_sequence('{" . $anotherTableName . "}', 'id')")->fetchField();
    $this->assertTrue($sequenceExists, 'Sequence was renamed.');
  }

  /**
   * {@inheritdoc}
   */
  public function testTableWithSpecificDataType(): void {
    $table_specification = [
      'description' => 'Schema table description.',
      'fields' => [
        'timestamp'  => [
          'pgsql_type' => 'timestamp',
          'not null' => FALSE,
          'default' => NULL,
        ],
      ],
    ];
    $this->schema->createTable('test_timestamp', $table_specification);
    $this->assertTrue($this->schema->tableExists('test_timestamp'));
  }

  /**
   * @covers \Drupal\pgsql\Driver\Database\pgsql\Schema::introspectIndexSchema
   */
  public function testIntrospectIndexSchema(): void {
    $table_specification = [
      'fields' => [
        'id'  => [
          'type' => 'int',
          'not null' => TRUE,
          'default' => 0,
        ],
        'test_field_1'  => [
          'type' => 'int',
          'not null' => TRUE,
          'default' => 0,
        ],
        'test_field_2'  => [
          'type' => 'int',
          'default' => 0,
        ],
        'test_field_3'  => [
          'type' => 'int',
          'default' => 0,
        ],
        'test_field_4'  => [
          'type' => 'int',
          'default' => 0,
        ],
        'test_field_5'  => [
          'type' => 'int',
          'default' => 0,
        ],
      ],
      'primary key' => ['id', 'test_field_1'],
      'unique keys' => [
        'test_field_2' => ['test_field_2'],
        'test_field_3_test_field_4' => ['test_field_3', 'test_field_4'],
      ],
      'indexes' => [
        'test_field_4' => ['test_field_4'],
        'test_field_4_test_field_5' => ['test_field_4', 'test_field_5'],
      ],
    ];

    $table_name = strtolower($this->getRandomGenerator()->name());
    $this->schema->createTable($table_name, $table_specification);

    unset($table_specification['fields']);

    $introspect_index_schema = new \ReflectionMethod(get_class($this->schema), 'introspectIndexSchema');
    $index_schema = $introspect_index_schema->invoke($this->schema, $table_name);

    // The PostgreSQL driver is using a custom naming scheme for its indexes, so
    // we need to adjust the initial table specification.
    $ensure_identifier_length = new \ReflectionMethod(get_class($this->schema), 'ensureIdentifiersLength');

    foreach ($table_specification['unique keys'] as $original_index_name => $columns) {
      unset($table_specification['unique keys'][$original_index_name]);
      $new_index_name = $ensure_identifier_length->invoke($this->schema, $table_name, $original_index_name, 'key');
      $table_specification['unique keys'][$new_index_name] = $columns;
    }

    foreach ($table_specification['indexes'] as $original_index_name => $columns) {
      unset($table_specification['indexes'][$original_index_name]);
      $new_index_name = $ensure_identifier_length->invoke($this->schema, $table_name, $original_index_name, 'idx');
      $table_specification['indexes'][$new_index_name] = $columns;
    }

    $this->assertEquals($table_specification, $index_schema);
  }

  /**
   * {@inheritdoc}
   */
  public function testReservedKeywordsForNaming(): void {
    $table_specification = [
      'description' => 'A test table with an ANSI reserved keywords for naming.',
      'fields' => [
        'primary' => [
          'description' => 'Simple unique ID.',
          'type' => 'int',
          'not null' => TRUE,
        ],
        'update' => [
          'description' => 'A column with reserved name.',
          'type' => 'varchar',
          'length' => 255,
        ],
      ],
      'primary key' => ['primary'],
      'unique keys' => [
        'having' => ['update'],
      ],
      'indexes' => [
        'in' => ['primary', 'update'],
      ],
    ];

    // Creating a table.
    $table_name = 'select';
    $this->schema->createTable($table_name, $table_specification);
    $this->assertTrue($this->schema->tableExists($table_name));

    // Finding all tables.
    $tables = $this->schema->findTables('%');
    sort($tables);
    $this->assertEquals(['config', 'select'], $tables);

    // Renaming a table.
    $table_name_new = 'from';
    $this->schema->renameTable($table_name, $table_name_new);
    $this->assertFalse($this->schema->tableExists($table_name));
    $this->assertTrue($this->schema->tableExists($table_name_new));

    // Adding a field.
    $field_name = 'delete';
    $this->schema->addField($table_name_new, $field_name, ['type' => 'int', 'not null' => TRUE]);
    $this->assertTrue($this->schema->fieldExists($table_name_new, $field_name));

    // Dropping a primary key.
    $this->schema->dropPrimaryKey($table_name_new);

    // Adding a primary key.
    $this->schema->addPrimaryKey($table_name_new, [$field_name]);

    // Check the primary key columns.
    $find_primary_key_columns = new \ReflectionMethod(get_class($this->schema), 'findPrimaryKeyColumns');
    $this->assertEquals([$field_name], $find_primary_key_columns->invoke($this->schema, $table_name_new));

    // Dropping a primary key.
    $this->schema->dropPrimaryKey($table_name_new);

    // Changing a field.
    $field_name_new = 'where';
    $this->schema->changeField($table_name_new, $field_name, $field_name_new, ['type' => 'int', 'not null' => FALSE]);
    $this->assertFalse($this->schema->fieldExists($table_name_new, $field_name));
    $this->assertTrue($this->schema->fieldExists($table_name_new, $field_name_new));

    // Adding an unique key
    $unique_key_name = $unique_key_introspect_name = 'unique';
    $this->schema->addUniqueKey($table_name_new, $unique_key_name, [$field_name_new]);

    // Check the unique key columns.
    $introspect_index_schema = new \ReflectionMethod(get_class($this->schema), 'introspectIndexSchema');
    $ensure_identifiers_length = new \ReflectionMethod(get_class($this->schema), 'ensureIdentifiersLength');
    $unique_key_introspect_name = $ensure_identifiers_length->invoke($this->schema, $table_name_new, $unique_key_name, 'key');
    $this->assertEquals([$field_name_new], $introspect_index_schema->invoke($this->schema, $table_name_new)['unique keys'][$unique_key_introspect_name]);

    // Dropping an unique key
    $this->schema->dropUniqueKey($table_name_new, $unique_key_name);

    // Dropping a field.
    $this->schema->dropField($table_name_new, $field_name_new);
    $this->assertFalse($this->schema->fieldExists($table_name_new, $field_name_new));

    // Adding an index.
    $index_name = $index_introspect_name = 'index';
    $this->schema->addIndex($table_name_new, $index_name, ['update'], $table_specification);
    $this->assertTrue($this->schema->indexExists($table_name_new, $index_name));

    // Check the index columns.
    $index_introspect_name = $ensure_identifiers_length->invoke($this->schema, $table_name_new, $index_name, 'idx');
    $this->assertEquals(['update'], $introspect_index_schema->invoke($this->schema, $table_name_new)['indexes'][$index_introspect_name]);

    // Dropping an index.
    $this->schema->dropIndex($table_name_new, $index_name);
    $this->assertFalse($this->schema->indexExists($table_name_new, $index_name));

    // Dropping a table.
    $this->schema->dropTable($table_name_new);
    $this->assertFalse($this->schema->tableExists($table_name_new));
  }

  /**
   * @covers \Drupal\pgsql\Driver\Database\pgsql\Schema::extensionExists
   */
  public function testPgsqlExtensionExists(): void {
    // Test the method for a non existing extension.
    $this->assertFalse($this->schema->extensionExists('non_existing_extension'));

    // Test the method for an existing extension.
    $this->assertTrue($this->schema->extensionExists('pg_trgm'));
  }

  /**
   * Tests if the new sequences get the right ownership.
   */
  public function testPgsqlSequences(): void {
    $table_specification = [
      'description' => 'A test table with an ANSI reserved keywords for naming.',
      'fields' => [
        'uid' => [
          'description' => 'Simple unique ID.',
          'type' => 'serial',
          'not null' => TRUE,
        ],
        'update' => [
          'description' => 'A column with reserved name.',
          'type' => 'varchar',
          'length' => 255,
        ],
      ],
      'primary key' => ['uid'],
      'unique keys' => [
        'having' => ['update'],
      ],
      'indexes' => [
        'in' => ['uid', 'update'],
      ],
    ];

    // Creating a table.
    $table_name = 'sequence_test';
    $this->schema->createTable($table_name, $table_specification);
    $this->assertTrue($this->schema->tableExists($table_name));

    // Retrieves a sequence name that is owned by the table and column.
    $sequence_name = $this->connection
      ->query("SELECT pg_get_serial_sequence(:table, :column)", [
        ':table' => $this->connection->getPrefix() . 'sequence_test',
        ':column' => 'uid',
      ])
      ->fetchField();

    $schema = $this->connection->getConnectionOptions()['schema'] ?? 'public';
    $this->assertEquals($schema . '.' . $this->connection->getPrefix() . 'sequence_test_uid_seq', $sequence_name);

    // Checks if the sequence exists.
    $this->assertTrue((bool) \Drupal::database()
      ->query("SELECT c.relname FROM pg_class as c WHERE c.relkind = 'S' AND c.relname = :name", [
        ':name' => $this->connection->getPrefix() . 'sequence_test_uid_seq',
      ])
      ->fetchField());

    // Retrieves the sequence owner object.
    $sequence_owner = \Drupal::database()->query("SELECT d.refobjid::regclass as table_name, a.attname as field_name
      FROM pg_depend d
      JOIN pg_attribute a ON a.attrelid = d.refobjid AND a.attnum = d.refobjsubid
      WHERE d.objid = :seq_name::regclass
      AND d.refobjsubid > 0
      AND d.classid = 'pg_class'::regclass", [':seq_name' => $sequence_name])->fetchObject();

    $this->assertEquals($this->connection->getPrefix() . 'sequence_test', $sequence_owner->table_name);
    $this->assertEquals('uid', $sequence_owner->field_name, 'New sequence is owned by its table.');

  }

  /**
   * Tests the method tableExists().
   */
  public function testTableExists(): void {
    $table_name = 'test_table';
    $table_specification = [
      'fields' => [
        'id'  => [
          'type' => 'int',
          'default' => NULL,
        ],
      ],
    ];
    $this->schema->createTable($table_name, $table_specification);
    $prefixed_table_name = $this->connection->getPrefix($table_name) . $table_name;

    // Three different calls to the method Schema::tableExists() with an
    // unprefixed table name.
    $this->assertTrue($this->schema->tableExists($table_name));
    $this->assertTrue($this->schema->tableExists($table_name, TRUE));
    $this->assertFalse($this->schema->tableExists($table_name, FALSE));

    // Three different calls to the method Schema::tableExists() with a
    // prefixed table name.
    $this->assertFalse($this->schema->tableExists($prefixed_table_name));
    $this->assertFalse($this->schema->tableExists($prefixed_table_name, TRUE));
    $this->assertTrue($this->schema->tableExists($prefixed_table_name, FALSE));
  }

  /**
   * Tests renaming a table where the new index name is equal to the table name.
   */
  public function testRenameTableWithNewIndexNameEqualsTableName(): void {
    // Special table names for colliding with the PostgreSQL new index name.
    $table_name_old = 'some_new_table_name__id__idx';
    $table_name_new = 'some_new_table_name';
    $table_specification = [
      'fields' => [
        'id'  => [
          'type' => 'int',
          'default' => NULL,
        ],
      ],
      'indexes' => [
        'id' => ['id'],
      ],
    ];
    $this->schema->createTable($table_name_old, $table_specification);

    // Renaming the table can fail for PostgreSQL, when a new index name is
    // equal to the old table name.
    $this->schema->renameTable($table_name_old, $table_name_new);

    $this->assertTrue($this->schema->tableExists($table_name_new));
  }

  /**
   * Tests column name escaping in field constraints.
   */
  public function testUnsignedField(): void {
    $table_name = 'unsigned_table';
    $table_spec = [
      'fields' => [
        'order' => [
          'type' => 'int',
          'unsigned' => TRUE,
          'not null' => TRUE,
        ],
      ],
      'primary key' => ['order'],
    ];
    $this->schema->createTable($table_name, $table_spec);
    $this->assertTrue($this->schema->tableExists($table_name));
  }

  /**
   * Test creation of a GIST index.
   *
   * The base method tests a GIST index specification by way of verifying the
   * object-based index specification. Run that test, but also verify it does
   * what it says on the tin.
   */
  #[\Override]
  public function testObjectIndexSyntax(): void {
    parent::testObjectIndexSyntax();
    $introspect_index_schema = new \ReflectionMethod(get_class($this->schema), 'introspectIndexSchema');
    $index_schema = $introspect_index_schema->invoke($this->schema, 'index_with_object');
    $this->assertCount(1, $index_schema['index_definitions']);
    $this->assertStringContainsString('USING gist', current($index_schema['index_definitions']));
    $this->schema->dropIndex('index_with_object', 'text_column_index');
    $index_schema = $introspect_index_schema->invoke($this->schema, 'index_with_object');
    $this->assertEmpty($index_schema['indexes']);
    // Test adding an index via ::addIndex().
    $this->schema->addIndex(
      'index_with_object',
      'text_column_index_2',
      new Index(
      ['text'],
      [
        'pgsql' => [
          'type' => IndexType::GIST,
          'operator' => 'gist_trgm_ops',
        ],
      ]
    ),
      [
        'fields' => [
          'id' => [
            'type' => 'serial',
            'not null' => TRUE,
            'description' => 'Primary Key: Unique ID.',
          ],
          'text' => [
            'type' => 'text',
            'description' => 'A text field',
          ],
        ],
        'primary key' => ['id'],
      ]
    );
    $index_schema = $introspect_index_schema->invoke($this->schema, 'index_with_object');
    $this->assertCount(1, $index_schema['index_definitions']);
    $this->assertStringContainsString('USING gist', current($index_schema['index_definitions']));
  }

  /**
   * Test CRUD of GIN indexes.
   */
  public function testGinIndexCrud(): void {
    $specification = [
      'fields' => [
        'id' => [
          'type' => 'serial',
          'not null' => TRUE,
          'description' => 'Primary Key: Unique ID.',
        ],
        'json' => [
          'type' => 'json',
          'description' => 'A JSON field',
        ],
      ],
      'indexes' => [
        'json_column_index' => new Index(
          ['json'],
          [
            'pgsql' => [
              'type' => IndexType::GIN,
            ],
          ]
        ),
      ],
      'primary key' => ['id'],
    ];
     $table_name = 'index_with_object';
     $this->schema->createTable($table_name, $specification);
     $this->assertIndexOnColumns($table_name, ['json']);
     $introspect_index_schema = new \ReflectionMethod(get_class($this->schema), 'introspectIndexSchema');
     $index_schema = $introspect_index_schema->invoke($this->schema, 'index_with_object');
     $this->assertCount(1, $index_schema['index_definitions']);
     $this->assertStringContainsString('USING gin', current($index_schema['index_definitions']));
     $this->schema->dropIndex('index_with_object', 'json_column_index');
     $index_schema = $introspect_index_schema->invoke($this->schema, 'index_with_object');
     $this->assertEmpty($index_schema['indexes']);
  }

  /**
   * Tests JSON schema type.
   */
  public function testJsonSchema(): void {
    $this->doTestJsonSchema(TRUE);

    // Test validation of malformed indexes.
    try {
      $this->schema->addIndex('test_json', 'invalid_index', ['id', 'test_field'], self::JSON_TABLE_SPECIFICATION);
    }
    catch (SchemaIndexOnJsonFieldUnsupportedException $e) {
      $this->assertEquals('JSON data columns must be indexed only by themselves when using Postgres: Table test_json, index invalid_index contains incompatible source columns.', $e->getMessage());
      $this->assertTrue(TRUE);
    }

    foreach (self::JSON_TEST_DATA as $path => $expected) {
      $query = $this->connection->select('test_json');
      $query->addExpression('jsonb_path_query(test_field, :path)', NULL, [
        ':path' => $path,
      ]);
      $actual = json_decode($query->execute()->fetchField());
      $this->assertSame($expected, $actual);
    }
    // GIN indexing works on JSONB columns, yet only for certain
    // Postgres-supported operators. We test one, here.
    $explain_query = $this->connection->select('test_json');
    // @todo Convert this WHERE to use the query builder when https://www.drupal.org/project/drupal/issues/3378275 lands.
    // Postgres might try to outsmart us and run a table scan instead of using
    // an index, due to a low number of rows. Explicitly tell the database
    // to disable sequence scans for small sets. The index will still only be
    // used if it is properly configured, so this will not result in a
    // false-positive test result.
    $this->connection->query('SET enable_seqscan TO off');
    // Run a query that uses the @? operator to test GIN index compatibility.
    $explained = implode("\n", $this->connection->query(
      'EXPLAIN ' . $explain_query . ' WHERE test_field @? \'$.number ? (@ >= 0)\''
    )->fetchCol());
    // Ensure the auto-generated index is used.
    $this->assertMatchesRegularExpression('/Bitmap Index Scan.*auto_gen_test_field/', $explained);

    // Postgres will automatically drop an orphaned index. Ensure no exception.
    $this->schema->dropField('test_json', 'test_field');
  }

}
