<?php

/**
 * @file
 * Test module for Filter module hooks and functions not used in core.
 */

use Drupal\filter_test\Plugin\Filter\FilterTestImageStyle;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function filter_test_filter_format_insert($format) {
  \Drupal::messenger()->addStatus('hook_filter_format_insert invoked.');
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function filter_test_filter_format_update($format) {
  \Drupal::messenger()->addStatus('hook_filter_format_update invoked.');
}

/**
 * Implements hook_filter_format_disable().
 */
function filter_test_filter_format_disable($format) {
  \Drupal::messenger()->addStatus('hook_filter_format_disable invoked.');
}

/**
 * Implements hook_filter_info_alter().
 */
function filter_test_filter_info_alter(array &$info) {
  $info['filter_image_style']['class'] = FilterTestImageStyle::class;
}
