<?php

/**
 * @file
 * Test module for Filter module hooks and functions not used in core.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function filter_test_filter_format_insert($format) {
  \Drupal::messenger()->addStatus('hook_filter_format_insert invoked.');

  if ($format->id() === 'filter_test') {
    $permission = $format->getPermissionName();
    user_role_grant_permissions(RoleInterface::ANONYMOUS_ID, [$permission]);
    user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, [$permission]);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function filter_test_filter_format_update($format) {
  \Drupal::messenger()->addStatus('hook_filter_format_update invoked.');
}

/**
 * Implements hook_filter_format_disable().
 */
function filter_test_filter_format_disable($format) {
  \Drupal::messenger()->addStatus('hook_filter_format_disable invoked.');
}
