<?php

/**
 * @file
 * Update hooks for the Datetime Range module.
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Entity\Schema\DynamicallyFieldableEntityStorageSchemaInterface;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Add the 'timezone' field to all daterange field tables.
 */
function datetime_range_update_8001(array &$sandbox) {

  if (!isset($sandbox['progress'])) {
    $sandbox['progress'] = 0;
    $sandbox['current_id'] = '';
    $sandbox['processed'] = [];

    // Find all required updates.
    $change_list = [];
    foreach (\Drupal::entityTypeManager()->getDefinitions() as $entity_type_id => $entity_type) {
      $storage = \Drupal::entityTypeManager()->getStorage($entity_type_id);
      if ($storage instanceof DynamicallyFieldableEntityStorageSchemaInterface) {
        $field_changes = [];
        $field_storage_definitions = \Drupal::service('entity_field.manager')->getFieldStorageDefinitions($entity_type_id);
        $original_storage_definitions = \Drupal::service('entity.last_installed_schema.repository')->getLastInstalledFieldStorageDefinitions($entity_type_id);
        foreach (array_intersect_key($field_storage_definitions, $original_storage_definitions) as $field_name => $storage_definition) {
          if ($storage_definition->getType() === 'daterange' && $storage->requiresFieldStorageSchemaChanges($storage_definition, $original_storage_definitions[$field_name])) {
            /** @var \Drupal\Core\Entity\Sql\DefaultTableMapping $table_mapping */
            $table_mapping = $storage->getTableMapping();
            $field_changes[$field_name] = [
              'table' => $table_mapping->getFieldTableName($field_name),
              'revision_table' => $table_mapping->getDedicatedRevisionTableName($storage_definition),
            ];
          }
        }

        if (!empty($field_changes)) {
          $change_list[$entity_type_id] = $field_changes;
        }
      }
    }

    $sandbox['change_list'] = $change_list;
    $sandbox['max'] = count($change_list);
  }

  $remaining = array_diff(array_keys($sandbox['change_list']), $sandbox['processed']);
  if (!empty($remaining)) {
    $entity_type_id = array_pop($remaining);
    $field_changes = $sandbox['change_list'][$entity_type_id];

    $field_spec = [
      'description' => 'The date time zone.',
      'type' => 'varchar',
      'length' => 50,
    ];
    $schema = Database::getConnection()->schema();

    foreach ($field_changes as $field_name => $field_tables) {
      $timezone_field_name = $field_name . '_timezone';
      $field_schema = [
        'fields' => [
          // Include the 'value' field in order to properly create the index.
          $field_name . '_value' => [
            'description' => 'The date value.',
            'type' => 'varchar',
            'length' => 20,
          ],
          $timezone_field_name => $field_spec,
        ],
        'indexes' => [
          'value_timezone' => [$field_name . '_value', $timezone_field_name],
        ],
      ];
      $schema->addField($field_tables['table'], $timezone_field_name, $field_spec);
      $schema->addIndex($field_tables['table'], 'value_timezone', $field_schema['indexes']['value_timezone'], $field_schema);

      if ($field_tables['revision_table']) {
        $schema->addField($field_tables['revision_table'], $timezone_field_name, $field_spec);
        $schema->addIndex($field_tables['revision_table'], 'value_timezone', $field_schema['indexes']['value_timezone'], $field_schema);
      }

      // Set time zone storage to FALSE, which is the behavior prior to the
      // introduction of configurable per-date time zone storage.
      $field_storage = FieldStorageConfig::load($entity_type_id . '.' . $field_name);
      $field_storage->setSetting('timezone_storage', FALSE);
      $field_storage->save();
      \Drupal::entityDefinitionUpdateManager()->updateFieldStorageDefinition($field_storage);
    }
    $sandbox['processed'][] = $entity_type_id;
  }

  $sandbox['#finished'] = empty($remaining);
}
