<?php

/**
 * @file
 * More Help Page Test module to test the help blocks.
 */

declare(strict_types=1);

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function more_help_page_test_help($route_name, RouteMatchInterface $route_match): string {

  switch ($route_name) {
    // Return help for the same route as the help_page_test module.
    case 'help_page_test.test_array':
      return '<p>' . 'Help text from more_help_page_test_help module.' . '</p>';

    default:
      return '';
  }
}

/**
 * Implements hook_help_section_info_alter().
 */
function more_help_page_test_help_section_info_alter(array &$info) {
  $info['hook_help']['weight'] = 500;
}
