<?php

/**
 * @file
 * Configuration Translation Test module.
 */

declare(strict_types=1);

use Drupal\Core\Extension\Extension;

/**
 * Implements hook_system_info_alter().
 */
function config_translation_test_system_info_alter(array &$info, Extension $file, $type) {
  // @see \Drupal\config_translation\Tests\ConfigTranslationUiThemeTest
  if ($file->getType() == 'theme' && $file->getName() == 'config_translation_test_theme') {
    $info['hidden'] = FALSE;
  }
}
