<?php

/**
 * Implements hook_testhook()
 */
function hk_b_test_testhook(): string {
  return __FUNCTION__;
}

/**
 * Implements hook_procedural_alter().
 *
 * @param list<string> $calls
 *   Parameter to collect called function names.
 */
function hk_b_test_procedural_alter(array &$calls): void {
  $calls[] = __FUNCTION__;
}

/**
 * Implements hook_procedural_subtype_alter().
 *
 * @param list<string> $calls
 *   Parameter to collect called function names.
 */
function hk_b_test_procedural_subtype_alter(array &$calls): void {
  $calls[] = __FUNCTION__;
}
