<?php

declare(strict_types=1);

namespace Drupal\KernelTests\Core\Database;

trait AutoGeneratedFieldTestTrait {

  /**
   * Tests cleanup of auto-generated fields when the source field is dropped.
   *
   * @covers ::dropField
   */
  public function testAutoGeneratedFieldCleanup(): void {
    $this->schema->createTable('test_json', static::JSON_TABLE_SPECIFICATION);
    $created_tables = $this->schema->getFields('test_json');
    $this->assertCount(4, $created_tables);
    $this->schema->dropField('test_json', 'test_field');
    $after_tables = $this->schema->getFields('test_json');
    // The called code also deletes the index, however we need not make an
    // assertion here on index removal because it would throw an exception if
    // we tried deleting a field which was still part of an active index.
    $this->assertCount(1, $after_tables);
  }

  /**
   * Test that adding fields to existing tables also generate their indexes.
   *
   * @covers ::addField
   */
  public function testAddFieldWithAutoGeneratedIndexes(): void {
    $spec = static::JSON_TABLE_SPECIFICATION;
    $field = $spec['fields']['test_field'];
    unset($spec['fields']['test_field']);
    $this->schema->createTable('test_json', $spec);
    $this->schema->addField(
      'test_json',
      'test_field',
      $field
    );
    $introspect_index_schema = new \ReflectionMethod(get_class($this->schema), 'introspectIndexSchema');
    $indexes = $introspect_index_schema->invoke($this->schema, 'test_json')['indexes'];
    $this->assertCount(2, $indexes);
    foreach (array_keys($indexes) as $index) {
      $this->assertStringStartsWith('auto_gen_test_field_', $index);
    }
  }

}
