<?php

declare(strict_types=1);

namespace Drupal\KernelTests\Core\Database;

use Drupal\Core\Database\JsonpathGeneratedFieldTrait;

/**
 * Test trait for database drivers which automatically create indexes for JSON.
 */
trait AutoGeneratedIndexTestTrait {

  /**
   * Test that adding fields to existing tables also generate their indexes.
   */
  public function testAddFieldWithAutoGeneratedIndexes(): void {
    $spec = static::JSON_TABLE_SPECIFICATION;
    $field = $spec['fields']['test_field'];
    unset($spec['fields']['test_field']);
    $this->schema->createTable('test_json', $spec);
    $this->schema->addField(
      'test_json',
      'test_field',
      $field
    );
    $introspect_index_schema = new \ReflectionMethod(get_class($this->schema), 'introspectIndexSchema');
    $indexes = $introspect_index_schema->invoke($this->schema, 'test_json')['indexes'];
    $this->assertCount(
      in_array(JsonpathGeneratedFieldTrait::class, class_uses($this->schema)) ? 2 : 1,
      $indexes
    );
    foreach (array_keys($indexes) as $index) {
      $this->assertStringContainsString('auto_gen_test_field_', $index);
    }
  }

}
