<?php

declare(strict_types=1);

namespace Drupal\KernelTests\Core\Database;

trait AutoGeneratedFieldTestTrait {

  /**
   * Tests cleanup of auto-generated fields when the source field is dropped.
   */
  public function testAutoGeneratedFieldCleanup(): void {
    $this->schema->createTable('test_json', static::JSON_TABLE_SPECIFICATION);
    $created_tables = $this->schema->getFields('test_json');
    $this->assertCount(5, $created_tables);
    $this->schema->dropField('test_json', 'test_field');
    $after_tables = $this->schema->getFields('test_json');
    // The called code also deletes the index, however we need not make an
    // assertion here on index removal because it would throw an exception if
    // we tried deleting a field which was still part of an active index.
    $this->assertCount(1, $after_tables);
  }

}
