# Schema for the configuration files of the Block module.

block.block.*:
  type: config_entity
  label: 'Block'
  constraints:
    FullyValidatable: ~
  mapping:
    id:
      type: machine_name
      label: 'ID'
      # Blocks have atypical machine names: they allow periods for historical reasons.
      # @see https://www.drupal.org/project/drupal/issues/2685917
      # @see https://www.drupal.org/project/drupal/issues/2043527
      constraints:
        Regex:
          pattern: '/^[a-z0-9_.]+$/'
          message: "The %value machine name is not valid."
    theme:
      type: string
      label: 'Theme'
      constraints:
        NotBlank: []
        ExtensionName: []
        ExtensionExists: theme
    region:
      type: string
      label: 'Region'
    weight:
      type: weight
      label: 'Weight'
      # @todo Figure out when/why this is sensible. Seems unintentional: BlockInterface::getWeight() has `int` return type, implementation does not cast from NULL to int.
      nullable: true
    provider:
      deprecated: "The 'block.block.*:provider' config property path is deprecated in drupal:10.3.0 and is removed from drupal 11.0.0. It was unused, there is no replacement. See https://www.drupal.org/node/1234567."
      nullable: true
      type: string
      label: 'Provider'
    plugin:
      type: string
      label: 'Plugin'
      constraints:
        PluginExists:
          manager: plugin.manager.block
          interface: Drupal\Core\Block\BlockPluginInterface
          # Block plugin IDs may not be valid in blocks that are backed by
          # block_content entities that don't exist yet. Therefore, it's okay
          # to consider the fallback plugin ID as valid.
          allowFallback: true
    settings:
      # @todo
      type: block.settings.[%parent.plugin]
    visibility:
      # @todo
      type: sequence
      label: 'Visibility Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Visibility Condition'
