<?php

/**
 * @file
 * Install, update and uninstall functions for the pgsql module.
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Database\Schema\Index;
use Drupal\pgsql\Schema\IndexType;

/**
 * Implements hook_requirements().
 */
function pgsql_requirements() {
  $requirements = [];
  // Test with PostgreSQL databases for the status of the pg_trgm extension.
  if (Database::isActiveConnection()) {
    $connection = Database::getConnection();

    // Set the requirement just for postgres.
    if ($connection->driver() == 'pgsql') {
      $requirements['pgsql_extension_pg_trgm'] = [
        'severity' => REQUIREMENT_OK,
        'title' => t('PostgreSQL pg_trgm extension'),
        'value' => t('Available'),
        'description' => 'The pg_trgm PostgreSQL extension is present.',
      ];

      // If the extension is not available, set the requirement error.
      if (!$connection->schema()->extensionExists('pg_trgm')) {
        $requirements['pgsql_extension_pg_trgm']['severity'] = REQUIREMENT_ERROR;
        $requirements['pgsql_extension_pg_trgm']['value'] = t('Not created');
        $requirements['pgsql_extension_pg_trgm']['description'] = t('The <a href=":pg_trgm">pg_trgm</a> PostgreSQL extension is not present. The extension is required by Drupal 10 to improve performance when using PostgreSQL. See <a href=":requirements">Drupal database server requirements</a> for more information.', [
          ':pg_trgm' => 'https://www.postgresql.org/docs/current/pgtrgm.html',
          ':requirements' => 'https://www.drupal.org/docs/system-requirements/database-server-requirements',
        ]);
      }

    }
  }

  return $requirements;
}

/**
 * Implements hook_update_last_removed().
 */
function pgsql_update_last_removed() {
  return 10101;
}

/**
 * Change the path_alias and path_alias_revision tables to add GIST indexes.
 */
function pgsql_update_10102(&$sandbox) {
  $connection = \Drupal::database();
  if ($connection->databaseType() === 'pgsql') {
    $schema = $connection->schema();
    // Add GIST indexes to make queries on the columns 'path' and 'alias'
    // faster.
    // @see https://www.postgresql.org/docs/12/textsearch-indexes.html
    if ($schema->tableExists('path_alias') && !$schema->indexExists('path_alias', 'path_alias__path_gist')) {
      $schema->addIndex('path_alias', 'path_alias__path_gist', new Index(['path'], [
        'pgsql' => [
          'type' => IndexType::Gist,
          'operator' => 'gist_trgm_ops',
        ],
      ]), []);
    }
    if ($schema->tableExists('path_alias') && !$schema->indexExists('path_alias', 'path_alias__alias_gist')) {
      $schema->addIndex('path_alias', 'path_alias__alias_gist', new Index(['alias'], [
        'pgsql' => [
          'type' => IndexType::Gist,
          'operator' => 'gist_trgm_ops',
        ],
      ]), []);
    }
    if ($schema->tableExists('path_alias_revision') && !$schema->indexExists('path_alias_revision', 'path_alias__path_gist')) {
      $schema->addIndex('path_alias_revision', 'path_alias_revision__path_gist', new Index(['path'], [
        'pgsql' => [
          'type' => IndexType::Gist,
          'operator' => 'gist_trgm_ops',
        ],
      ]), []);
    }
    if ($schema->tableExists('path_alias_revision') && !$schema->indexExists('path_alias_revision', 'path_alias__alias_gist')) {
      $schema->addIndex('path_alias_revision', 'path_alias_revision__alias_gist', new Index(['alias'], [
        'pgsql' => [
          'type' => IndexType::Gist,
          'operator' => 'gist_trgm_ops',
        ],
      ]), []);
    }
  }
}
