<?php

declare(strict_types=1);

use Drupal\hk_a_test\Hook\ModuleImplementsAlter;

/**
 * Implements hook_testhook().
 */
function hk_a_test_testhook(): string {
  return __FUNCTION__;
}

/**
 * Implements hook_procedural_alter().
 */
function hk_a_test_procedural_alter(array &$calls): void {
  $calls[] = __FUNCTION__;
}

/**
 * Implements hook_procedural_subtype_alter().
 */
function hk_a_test_procedural_subtype_alter(array &$calls): void {
  $calls[] = __FUNCTION__;
}

/**
 * Implements hook_module_implements_alter().
 */
function hk_a_test_module_implements_alter(array &$implementations, string $hook): void {
  ModuleImplementsAlter::call($implementations, $hook);
}
