################
# Defining Variables for GitLabCI pipelines
#
# https://docs.gitlab.com/ee/ci/variables/
# Predefined variables: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
################

################
# Variables
#
# These variables provide 'Semantic Labels' to help you automatically track the current supported and development versions of Drupal, as well as the current min/max system requirements for PHP, database, etc.
#
# If this file is updated, your testing configuration will automatically follow these changes.
#
# Overriding variables
#   - To override one or more of these variables, simply declare your own variables keyword.
#   - Keywords declared directly in .gitlab-ci.yml take precedence over include files.
#   - Documentation:  https://docs.gitlab.com/ee/ci/variables/
#     - Predefined variables: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
#
################

variables:
    ################
    # Experimenting with setting the dockerhub image root using a variable
    #
    # Ultimately may not be practical because the docker image names don't necessarily follow the same patterns across different namespaces, so replacement may not work. (e.g: wodby/php:$VERSION vs drupalci/php-$VERSION-apache:production)
    ################

    _CONFIG_DOCKERHUB_ROOT:
        value: "drupalci"
        description: "The root namespace on Dockerhub to pull containers from."
