include:
  - local: .gitlab-ci/base-pipeline.yml

'🩹 Test-only changes':
  <<: [ !reference [.with-composer], !reference [.default-job-settings] ]
  services:
    - <<: !reference [.with-database]
    - <<: !reference [.with-chrome]
  script:
    - chmod +x $CI_PROJECT_DIR/.gitlab-ci/scripts/test-only.sh
    - $CI_PROJECT_DIR/.gitlab-ci/scripts/test-only.sh