<?php

/**
 * @file
 * Test module.
 */

declare(strict_types=1);

/**
 * Load function used by module_test_hook_dynamic_loading_invoke_all_during_load().
 *
 * @see module_test_menu()
 */
function module_test_load($param) {
  $result = \Drupal::moduleHandler()->invokeAll('test_hook');
  return $result[$param];
}

/**
 * Implements hook_modules_installed().
 */
function module_test_modules_installed($modules) {
  // Record the ordered list of modules that were passed in to this hook so we
  // can check that the modules were enabled in the correct sequence.
  \Drupal::state()->set('module_test.install_order', $modules);
}

/**
 * Implements hook_modules_uninstalled().
 */
function module_test_modules_uninstalled($modules) {
  // Record the ordered list of modules that were passed in to this hook so we
  // can check that the modules were uninstalled in the correct sequence.
  \Drupal::state()->set('module_test.uninstall_order', $modules);
}
