<?php

/**
 * @file
 * Test module.
 */

declare(strict_types=1);

use Drupal\Core\Extension\Extension;

/**
 * Implements hook_hook_info().
 */
function module_test_hook_info(): array {
  $hooks['test_hook'] = [
    'group' => 'file',
  ];
  return $hooks;
}

/**
 * Load function used by module_test_hook_dynamic_loading_invoke_all_during_load().
 *
 * @see module_test_menu()
 */
function module_test_load($param) {
  $result = \Drupal::moduleHandler()->invokeAll('test_hook');
  return $result[$param];
}

/**
 * Implements hook_module_implements_alter().
 *
 * @see module_test_altered_test_hook()
 * @see \Drupal\system\Tests\Module\ModuleImplementsAlterTest::testModuleImplementsAlter()
 */
function module_test_module_implements_alter(&$implementations, $hook): void {
  if ($hook === 'altered_test_hook') {
    // Add a hook implementation, that will be found in
    // module_test.implementation.inc.
    $implementations['module_test'] = 'implementations';
  }
  if ($hook === 'unimplemented_test_hook') {
    // Add the non-existing function module_test_unimplemented_test_hook(). This
    // should cause an exception to be thrown in
    // \Drupal\Core\Extension\ModuleHandler::buildImplementationInfo('unimplemented_test_hook').
    $implementations['module_test'] = FALSE;
  }
}
