navigation_block.settings.*:
  type: navigation_block_settings

navigation_block_settings:
  type: mapping
  label: 'Navigation block settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Description'
    label_display:
      type: string
      label: 'Display title'
    provider:
      type: string
      label: 'Provider'
    status:
      type: boolean
      label: 'Status'
    info:
      type: label
      label: 'Admin info'
    view_mode:
      type: string
      label: 'View mode'
    context_mapping:
      type: sequence
      label: 'Context assignments'
      sequence:
        type: string
