name: Tags
description: 'Provides "Tags" taxonomy vocabulary and related configuration. Use tags to group content on similar topics into categories.'
type: 'Taxonomy'
install:
  - taxonomy
  - views
config:
  import:
    taxonomy: '*'
