<?php

/**
 * @file
 * Mock module for language layer tests.
 */

declare(strict_types=1);

/**
 * Store the last negotiated languages.
 */
function language_test_store_language_negotiation() {
  $last = [];
  foreach (\Drupal::languageManager()->getDefinedLanguageTypes() as $type) {
    $last[$type] = \Drupal::languageManager()->getCurrentLanguage($type)->getId();
  }
  \Drupal::keyValue('language_test')->set('language_negotiation_last', $last);
}

/**
 * Implements hook_module_preinstall().
 */
function language_test_module_preinstall() {
  \Drupal::state()->set('language_test.language_count_preinstall', count(\Drupal::languageManager()->getLanguages()));
}
