<?php

/**
 * @file
 * Functions to support theming in the Stable9 theme.
 */

/**
 * Implements hook_preprocess_item_list__search_results().
 *
 * Converts the markup of #empty for search results.
 */
function stable9_preprocess_item_list__search_results(&$variables) {
  if (isset($variables['empty']['#tag'])) {
    $variables['empty']['#tag'] = 'h3';
  }
}

// Add removed css/user.icons.admin.css file back so that themes overriding
// this file continue getting same behavior until Drupal 9.
if ($extension === 'user' && isset($libraries['drupal.user.icons'])) {
  $libraries['drupal.user.icons']['css']['theme']['css/user.icons.admin.css'] = [];
}
