# Schema for the configuration files of the dblog module.

dblog.settings:
  type: config_object
  label: 'Database logging settings'
  mapping:
    row_limit:
      type: integer
      label: 'Database log messages to keep'
      constraints:
        Choice:
          # All (no limit)
          - 0
          - 100
          - 1000
          - 10000
          - 100000
          - 1000000
