/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  var autocomplete;

  function autocompleteSplitValues(value) {
    var result = [];
    var quote = false;
    var current = '';
    var valueLength = value.length;
    var character;

    for (var i = 0; i < valueLength; i++) {
      character = value.charAt(i);

      if (character === '"') {
        current += character;
        quote = !quote;
      } else if (character === ',' && !quote) {
        result.push(current.trim());
        current = '';
      } else {
        current += character;
      }
    }

    if (value.length > 0) {
      result.push(current.trim());
    }

    return result;
  }

  function extractLastTerm(terms) {
    return autocomplete.splitValues(terms).pop();
  }

  function searchHandler(event) {
    var options = autocomplete.options;

    if (options.isComposing) {
      return false;
    }

    var term = autocomplete.extractLastTerm(event.target.value);

    if (term.length > 0 && options.firstCharacterBlacklist.indexOf(term[0]) !== -1) {
      return false;
    }

    return term.length >= options.minLength;
  }

  function sourceData(request, response) {
    var elementId = this.element.attr('id');

    if (!(elementId in autocomplete.cache)) {
      autocomplete.cache[elementId] = {};
    }

    function showSuggestions(suggestions) {
      var tagged = autocomplete.splitValues(request.term);
      var il = tagged.length;

      for (var i = 0; i < il; i++) {
        var index = suggestions.indexOf(tagged[i]);

        if (index >= 0) {
          suggestions.splice(index, 1);
        }
      }

      response(suggestions);
    }

    var term = autocomplete.extractLastTerm(request.term);

    function sourceCallbackHandler(data) {
      autocomplete.cache[elementId][term] = data;
      showSuggestions(data);
    }

    if (autocomplete.cache[elementId].hasOwnProperty(term)) {
      showSuggestions(autocomplete.cache[elementId][term]);
    } else {
      var options = $.extend({
        success: sourceCallbackHandler,
        data: {
          q: term
        }
      }, autocomplete.ajax);
      $.ajax(this.element.attr('data-autocomplete-path'), options);
    }
  }

  function focusHandler() {
    return false;
  }

  function selectHandler(event, ui) {
    var terms = autocomplete.splitValues(event.target.value);
    terms.pop();
    terms.push(ui.item.value);
    event.target.value = terms.join(', ');
    return false;
  }

  function renderItem(ul, item) {
    return $('<li>').append($('<a>').html(item.label)).appendTo(ul);
  }

  Drupal.behaviors.autocomplete = {
    attach: function attach(context) {
      var optionsToOriginalMethods = {
        source: sourceData,
        focus: focusHandler,
        search: searchHandler,
        select: selectHandler,
        renderItem: renderItem,
        cache: {},
        splitValues: autocompleteSplitValues,
        extractLastTerm: extractLastTerm,
        minLength: 1,
        firstCharacterBlacklist: '',
        isComposing: false,
        ajax: {
          dataType: 'json',
          jsonp: false
        }
      };
      once('legacy-autocomplete', 'body').forEach(function () {
        document.addEventListener('autocomplete-created', function (e) {
          var autocompleteInput = e.detail.autocomplete._internal_object.input;
          Object.keys(Drupal.autocomplete.options).forEach(function (option) {
            if (optionsToOriginalMethods.hasOwnProperty(option)) {
              if (optionsToOriginalMethods[option] !== Drupal.autocomplete.options[option]) {
                Drupal.deprecationError({
                  message: 'Setting autocomplete widget options via Drupal.autocomplete.options is deprecated in drupal:9.4.0 and is removed from drupal:10.0.0. Override Drupal.Autocomplete.defaultOptions using the its new API instead. See https://www.drupal.org/node/3083715'
                });
                var optionName = option === 'renderItem' ? '_renderItem' : option;

                if (optionName !== 'isComposing') {
                  $(autocompleteInput).autocomplete(optionName, Drupal.autocomplete.options[option]);
                }
              }
            }
          });
          Object.keys(Drupal.autocomplete).forEach(function (key) {
            if (key === 'options') {
              return;
            }

            var originalValue = ['ajax', 'cache'].includes(key) ? JSON.stringify(optionsToOriginalMethods[key]) : optionsToOriginalMethods[key];
            var newValue = ['ajax', 'cache'].includes(key) ? JSON.stringify(Drupal.autocomplete[key]) : Drupal.autocomplete[key];

            if (originalValue !== newValue) {
              var instance = e.detail.autocomplete._internal_object;

              switch (key) {
                case 'ajax':
                  Drupal.deprecationError({
                    message: 'Drupal.autocomplete.ajax is deprecated in drupal:9.4.0 and is removed from drupal:10.0.0. Override the source method of A11y_Autocomplete instead. See https://www.drupal.org/node/3083715'
                  });
                  break;

                case 'cache':
                  Drupal.deprecationError({
                    message: 'Drupal.autocomplete.cache is deprecated in drupal:9.4.0 and is removed from drupal:10.0.0. It is now handled automatically and should not be manually configured. See https://www.drupal.org/node/3083715'
                  });
                  break;

                case 'splitValues':
                  Drupal.deprecationError({
                    message: 'Drupal.autocomplete.splitValues is deprecated in drupal:9.4.0 and is removed from drupal:10.0.0. Override the splitValues method of A11y_Autocomplete instead. See https://www.drupal.org/node/3083715'
                  });

                  instance.splitValues = function () {
                    return Drupal.autocomplete[key](this.inputValue());
                  };

                  break;

                case 'extractLastTerm':
                  Drupal.deprecationError({
                    message: 'Drupal.autocomplete.extractLastTerm is deprecated in drupal:9.4.0 and is removed from drupal:10.0.0. Override the inputValue method of A11y_Autocomplete instead. See https://www.drupal.org/node/3083715'
                  });

                  instance.extractLastInputValue = function () {
                    return Drupal.autocomplete[key](this.inputValue());
                  };

                  break;

                default:
                  break;
              }
            }
          });
        });
      });
    }
  };
  autocomplete = {
    cache: {},
    splitValues: autocompleteSplitValues,
    extractLastTerm: extractLastTerm,
    options: {
      source: sourceData,
      focus: focusHandler,
      search: searchHandler,
      select: selectHandler,
      renderItem: renderItem,
      minLength: 1,
      firstCharacterBlacklist: '',
      isComposing: false
    },
    ajax: {
      dataType: 'json',
      jsonp: false
    }
  };
  Drupal.autocomplete = autocomplete;
})(jQuery, Drupal);