/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal, drupalSettings, A11yAutocomplete, once) {
  Drupal.Autocomplete = {};
  Drupal.Autocomplete.instances = {};
  Drupal.Autocomplete.defaultOptions = {
    createLiveRegion: false,
    minCharAssistiveHint: Drupal.t('Type @count or more characters for results'),
    noResultsAssistiveHint: Drupal.t('No results found'),
    moreThanMaxResultsAssistiveHint: Drupal.t('There are at least @count results available. Type additional characters to refine your search.'),
    someResultsAssistiveHint: Drupal.t('There are @count results available.'),
    oneResultAssistiveHint: Drupal.t('There is one result available.'),
    inputAssistiveHint: Drupal.t('When autocomplete results are available use up and down arrows to review and enter to select.  Touch device users, explore by touch or with swipe gestures.'),
    highlightedAssistiveHint: Drupal.t('@selectedItem @position of @count is highlighted')
  };

  Drupal.Autocomplete.initialize = function (autocompleteInput) {
    var options = Drupal.Autocomplete.defaultOptions || {};

    if (!autocompleteInput.hasAttribute('data-autocomplete-cardinality')) {
      autocompleteInput.setAttribute('data-autocomplete-cardinality', '-1');
    }

    if (autocompleteInput.hasAttribute('data-autocomplete-first-character-blacklist')) {
      options.firstCharacterDenylist = autocompleteInput.getAttribute('data-autocomplete-first-character-blacklist');
      Drupal.deprecationError({
        message: 'The data-autocomplete-first-character-blacklist attribute is deprecated in drupal:9.2.0 and is removed from drupal:10.0.0. Use data-autocomplete-first-character-denylist instead See https://www.drupal.org/node/3083715'
      });
    }

    var autocomplete = A11yAutocomplete(autocompleteInput, options);
    var instance = autocomplete._internal_object;

    function autocompleteSendToLiveRegion(message) {
      Drupal.announce(message, 'assertive');
    }

    instance.sendToLiveRegion = autocompleteSendToLiveRegion;
    return autocomplete;
  };

  Drupal.behaviors.autocomplete = {
    attach: function attach() {
      if (once('autocomplete-lifecycle', 'body').length) {
        document.addEventListener('autocomplete-destroy', function (e) {
          delete Drupal.Autocomplete.instances[e.detail.autocomplete.id];
        });
        document.addEventListener('autocomplete-created', function (e) {
          Drupal.Autocomplete.instances[e.detail.autocomplete.id] = e.detail.autocomplete;
        });
      }

      once('autocomplete-init', 'input.form-autocomplete').forEach(Drupal.Autocomplete.initialize);
    },
    detach: function detach(context, settings, trigger) {
      if (trigger === 'unload') {
        once.remove('autocomplete-init', 'input.form-autocomplete', context).forEach(function (input) {
          if (input.id in Drupal.Autocomplete.instances) {
            Drupal.Autocomplete.instances[input.id].destroy();
          }
        });
      }
    }
  };
})(Drupal, drupalSettings, A11yAutocomplete, once);