/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }

function _get(target, property, receiver) { if (typeof Reflect !== "undefined" && Reflect.get) { _get = Reflect.get; } else { _get = function _get(target, property, receiver) { var base = _superPropBase(target, property); if (!base) return; var desc = Object.getOwnPropertyDescriptor(base, property); if (desc.get) { return desc.get.call(receiver); } return desc.value; }; } return _get(target, property, receiver || target); }

function _superPropBase(object, property) { while (!Object.prototype.hasOwnProperty.call(object, property)) { object = _getPrototypeOf(object); if (object === null) break; } return object; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function"); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, writable: true, configurable: true } }); if (superClass) _setPrototypeOf(subClass, superClass); }

function _setPrototypeOf(o, p) { _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) { o.__proto__ = p; return o; }; return _setPrototypeOf(o, p); }

function _createSuper(Derived) { var hasNativeReflectConstruct = _isNativeReflectConstruct(); return function _createSuperInternal() { var Super = _getPrototypeOf(Derived), result; if (hasNativeReflectConstruct) { var NewTarget = _getPrototypeOf(this).constructor; result = Reflect.construct(Super, arguments, NewTarget); } else { result = Super.apply(this, arguments); } return _possibleConstructorReturn(this, result); }; }

function _possibleConstructorReturn(self, call) { if (call && (_typeof(call) === "object" || typeof call === "function")) { return call; } else if (call !== void 0) { throw new TypeError("Derived constructors may only return object or undefined"); } return _assertThisInitialized(self); }

function _assertThisInitialized(self) { if (self === void 0) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return self; }

function _isNativeReflectConstruct() { if (typeof Reflect === "undefined" || !Reflect.construct) return false; if (Reflect.construct.sham) return false; if (typeof Proxy === "function") return true; try { Boolean.prototype.valueOf.call(Reflect.construct(Boolean, [], function () {})); return true; } catch (e) { return false; } }

function _getPrototypeOf(o) { _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf : function _getPrototypeOf(o) { return o.__proto__ || Object.getPrototypeOf(o); }; return _getPrototypeOf(o); }

(function (Drupal, Backbone, $) {
  var deprecatedModelPrototypeProperties = ['on', 'listenTo', 'off', 'stopListening', 'once', 'listenToOnce', 'bind', 'unbind', 'changed', 'validationError', 'idAttribute', 'cidPrefix', 'toJSON', 'sync', 'escape', 'has', 'matches', 'unset', 'clear', 'hasChanged', 'changedAttributes', 'previousAttributes', 'fetch', 'save', 'destroy', 'url', 'parse', 'clone', 'isNew', 'isValid', 'keys', 'values', 'pairs', 'invert', 'pick', 'omit', 'chain', 'isEmpty'];

  Drupal.DrupalModel = function (_Backbone$Model) {
    _inherits(_class, _Backbone$Model);

    var _super = _createSuper(_class);

    function _class(values, options) {
      var _this;

      _classCallCheck(this, _class);

      _this = _super.call(this);
      _this.modelId = (Math.random() + 1).toString(36).substring(7);
      _this.allowSetChanged = true;
      _this.values = {};

      if (options) {
        if (options.hasOwnProperty('collection')) {
          Drupal.deprecationError({
            message: 'options.collection is deprecated in drupal:9.4.0 and will be removed from drupal:10.0.0.'
          });

          if (options.collection) {
            _this.collection = options.collection;
          }
        }

        if (options.hasOwnProperty('parse')) {
          Drupal.deprecationError({
            message: 'options.parse is deprecated in drupal:9.4.0 and will be removed from drupal:10.0.0.'
          });

          if (options.parse) {
            values = _this.parse(values, options) || {};
          }
        }
      }

      _this._previousValues = {};

      _this.set(values, options);

      _this.changed = {};

      if (_this.preinitialize !== Backbone.Model.prototype.preinitialize) {
        console.error('Drupal.DrupalModel.preinitialize is removed from drupal:9.4.0. Use constructor() instead.');
      }

      if (_this.initialize !== Backbone.Model.prototype.initialize) {
        console.error('Drupal.DrupalModel.preinitialize is removed from drupal:9.4.0. Use constructor() instead.');
      }

      if (_this.defaults) {
        console.error('Drupal.DrupalModel.defaults is removed from drupal:9.4.0. Use constructor() instead.');
      }

      return _this;
    }

    _createClass(_class, [{
      key: "get",
      value: function get(property) {
        return this.values[property];
      }
    }, {
      key: "set",
      value: function set(key, val, options) {
        if (key == null) {
          return this;
        }

        var attrs;

        if (_typeof(key) === 'object') {
          attrs = key;
          options = val;
        } else {
          (attrs = {})[key] = val;
        }

        options || (options = {});
        ['upset', 'silent', 'validate'].forEach(function (option) {
          if (options.hasOwnProperty(option)) {
            Drupal.deprecationError({
              message: "options.".concat(option, " is deprecated in drupal:9.4.0 and will be removed from drupal:10.0.0.")
            });
          }
        });

        if (!this._validate(attrs, options)) {
          return false;
        }

        var unset = options.unset;
        var silent = options.silent;
        var changes = [];
        var changing = this._changing;
        this._changing = true;

        if (!changing) {
          this._previousValues = Object.assign({}, this.values);
          this.changed = {};
        }

        var current = this.values;
        var changed = this.changed;
        var prev = this._previousValues;

        for (var attr in attrs) {
          val = attrs[attr];
          if (!_.isEqual(current[attr], val)) changes.push(attr);

          if (!_.isEqual(prev[attr], val)) {
            changed[attr] = val;
          } else {
            delete changed[attr];
          }

          unset ? delete current[attr] : current[attr] = val;
        }

        if (this.idAttribute in attrs) {
          this.id = this.get(this.idAttribute);
        }

        if (!silent) {
          if (changes.length) {
            this._pending = options;
          }

          for (var i = 0; i < changes.length; i++) {
            this.triggerEvent("model-".concat(this.modelId, "-change"));
            this.triggerEvent("model-".concat(this.modelId, "-change-").concat(changes[i]));

            _get(_getPrototypeOf(_class.prototype), "trigger", this).call(this, 'change:' + changes[i], this, current[changes[i]], options);
          }
        }

        if (changing) {
          return this;
        }

        if (!silent) {
          while (this._pending) {
            options = this._pending;
            this._pending = false;

            _get(_getPrototypeOf(_class.prototype), "trigger", this).call(this, 'change', this, options);
          }
        }

        this._pending = false;
        this._changing = false;
        return this;
      }
    }, {
      key: "triggerEvent",
      value: function triggerEvent(type) {
        var cancelable = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : false;
        var event = new CustomEvent(type, {
          bubbles: true,
          cancelable: cancelable
        });
        return document.dispatchEvent(event);
      }
    }, {
      key: "previous",
      value: function previous(property) {
        return this._previousValues[property];
      }
    }, {
      key: "trigger",
      value: function trigger() {
        Drupal.deprecationError({
          message: "Drupal.DrupalModel.trigger is deprecated in drupal:9.4.0 and will be removed from drupal:10.0.0. Use Drupal.DrupalModel.triggerEvent instead."
        });

        for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
          args[_key] = arguments[_key];
        }

        return _get(_getPrototypeOf(_class.prototype), "trigger", this).apply(this, args);
      }
    }, {
      key: "attributes",
      get: function get() {
        Drupal.deprecationError({
          message: 'Drupal.DrupalModel.attributes is deprecated in drupal:9.4.0 and will be removed from drupal:10.0.0. Use Drupal.DrupalModel.values instead.'
        });
        return this.values;
      }
    }, {
      key: "cid",
      get: function get() {
        Drupal.deprecationError({
          message: 'Drupal.DrupalModel.cid is deprecated in drupal:9.4.0 and will be removed from drupal:10.0.0. Use Drupal.DrupalModel.modelId instead.'
        });
        return this.modelId;
      },
      set: function set(modelId) {
        Drupal.deprecationError({
          message: 'Drupal.DrupalModel.cid is deprecated in drupal:9.4.0 and will be removed from drupal:10.0.0. Use Drupal.DrupalModel.modelId instead.'
        });
        this.modelId = modelId;
      }
    }]);

    return _class;
  }(Backbone.Model);

  deprecatedModelPrototypeProperties.forEach(function (property) {
    if (typeof Drupal.DrupalModel.prototype[property] === 'function') {
      var originalFunction = Drupal.DrupalModel.prototype[property];

      Drupal.DrupalModel.prototype[property] = function () {
        Drupal.deprecationError({
          message: "Drupal.DrupalModel.".concat(property, " is deprecated in drupal:9.4.0 and will be removed from drupal:10.0.0.")
        });

        for (var _len2 = arguments.length, args = new Array(_len2), _key2 = 0; _key2 < _len2; _key2++) {
          args[_key2] = arguments[_key2];
        }

        return originalFunction.apply(this, args);
      };
    }
  });

  Drupal.DrupalView = function (_Backbone$View) {
    _inherits(_class2, _Backbone$View);

    var _super2 = _createSuper(_class2);

    function _class2() {
      var _this2;

      _classCallCheck(this, _class2);

      _this2 = _super2.call(this);
      _this2._$el = null;
      return _this2;
    }

    _createClass(_class2, [{
      key: "setElement",
      value: function setElement(element) {
        return _get(_getPrototypeOf(_class2.prototype), "setElement", this).call(this, element);
      }
    }, {
      key: "addChangeListener",
      value: function addChangeListener(callback, modelProperty) {
        if (!modelProperty) {
          document.addEventListener("model-".concat(this.model.modelId, "-change"), callback());
        } else {
          if (!callback) {
            debugger;
          }

          document.addEventListener("model-".concat(this.model.modelId, "-change-").concat(modelProperty), callback.bind(this));
        }
      }
    }]);

    return _class2;
  }(Backbone.View);

  Drupal.DrupalView.prototype = Drupal.deprecatedProperty({
    target: Drupal.DrupalView.prototype,
    deprecatedProperty: '$el',
    message: 'Drupal.DrupalView.$el is deprecated in drupal:9.4.0 and will be removed from drupal:10.0.0. Use Drupal.DrupalView.el instead.'
  });

  Drupal.DrupalView.prototype._removeElement = function () {
    $(this.el).remove();
  };

  Drupal.DrupalView.prototype.delegate = function (el) {
    $(this.el).on(eventName + '.delegateEvents' + this.cid, selector, listener);
    return this;
  };

  Drupal.DrupalView.prototype.undelegateEvents = function () {
    if (this.el) $(this.el).off('.delegateEvents' + this.cid);
    return this;
  };

  Drupal.DrupalView.prototype.undelegate = function (eventName, selector, listener) {
    $(this.el).off(eventName + '.delegateEvents' + this.cid, selector, listener);
    return this;
  };

  Drupal.DrupalView.prototype._setAttributes = function (attributes) {
    $(this.el).attr(attributes);
  };
})(Drupal, Backbone, jQuery);