/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function"); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, writable: true, configurable: true } }); if (superClass) _setPrototypeOf(subClass, superClass); }

function _setPrototypeOf(o, p) { _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) { o.__proto__ = p; return o; }; return _setPrototypeOf(o, p); }

function _createSuper(Derived) { var hasNativeReflectConstruct = _isNativeReflectConstruct(); return function _createSuperInternal() { var Super = _getPrototypeOf(Derived), result; if (hasNativeReflectConstruct) { var NewTarget = _getPrototypeOf(this).constructor; result = Reflect.construct(Super, arguments, NewTarget); } else { result = Super.apply(this, arguments); } return _possibleConstructorReturn(this, result); }; }

function _possibleConstructorReturn(self, call) { if (call && (_typeof(call) === "object" || typeof call === "function")) { return call; } else if (call !== void 0) { throw new TypeError("Derived constructors may only return object or undefined"); } return _assertThisInitialized(self); }

function _assertThisInitialized(self) { if (self === void 0) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return self; }

function _isNativeReflectConstruct() { if (typeof Reflect === "undefined" || !Reflect.construct) return false; if (Reflect.construct.sham) return false; if (typeof Proxy === "function") return true; try { Boolean.prototype.valueOf.call(Reflect.construct(Boolean, [], function () {})); return true; } catch (e) { return false; } }

function _getPrototypeOf(o) { _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf : function _getPrototypeOf(o) { return o.__proto__ || Object.getPrototypeOf(o); }; return _getPrototypeOf(o); }

(function (Drupal) {
  Drupal.DrupalModel = function (_Backbone$Model) {
    _inherits(_class, _Backbone$Model);

    var _super = _createSuper(_class);

    function _class() {
      var _this;

      _classCallCheck(this, _class);

      _this = _super.call(this);
      _this.modelId = (Math.random() + 1).toString(36).substring(7);
      return _this;
    }

    _createClass(_class, [{
      key: "get",
      value: function get(property) {
        return this[property];
      }
    }, {
      key: "set",
      value: function set() {
        var _this2 = this;

        for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
          args[_key] = arguments[_key];
        }

        if (_typeof(args[0]) === 'object') {
          Object.keys(args[0]).forEach(function (key) {
            _this2.set(key, args[0][key]);
          });
        } else if (args[1]) {
          this[args[0]] = args[1];
          this.triggerEvent("model-".concat(this.modelId, "-change"));
          this.triggerEvent("model-".concat(this.modelId, "-change-").concat(args[0]));
        }
      }
    }, {
      key: "triggerEvent",
      value: function triggerEvent(type) {
        var cancelable = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : false;
        console.log('trigger event type', type);
        var event = new CustomEvent(type, {
          bubbles: true,
          cancelable: cancelable
        });
        return document.dispatchEvent(event);
      }
    }]);

    return _class;
  }(Backbone.Model);

  Drupal.DrupalView = function (_Backbone$View) {
    _inherits(_class2, _Backbone$View);

    var _super2 = _createSuper(_class2);

    function _class2() {
      var _this3;

      _classCallCheck(this, _class2);

      _this3 = _super2.call(this);
      console.log('i am the constructor in lil view.');
      return _this3;
    }

    _createClass(_class2, [{
      key: "addChangeListener",
      value: function addChangeListener(callback, modelProperty) {
        if (!modelProperty) {
          document.addEventListener("model-".concat(this.model.modelId, "-change"), callback());
        } else {
          if (!callback) {
            debugger;
          }

          document.addEventListener("model-".concat(this.model.modelId, "-change-").concat(modelProperty), callback.bind(this));
        }
      }
    }]);

    return _class2;
  }(Backbone.View);
})(Drupal);