<?php

namespace Drupal\user;

use Drupal\Component\Utility\Crypt;
use Drupal\Core\Site\Settings;
use Drupal\Core\Url;

/**
 * User action URL generation and checking service.
 *
 * To make any custom route compatible with this service it may only require the
 * following parameters:
 * - uid: id of the user for the action to affect.
 * - timestamp: the timestamp for the moment the action URL is generated.
 * - hash: the hash generated by this service which can be tested for validity
 *     using the checkHash method on this service.
 *
 * For a usage example, see user_cancel_url() and
 * \Drupal\user\Controller\UserController::confirmCancel().
 */
class UserActionUrl {

  /**
   * Get a user action url using the related route.
   *
   * @param string $route
   * @param \Drupal\user\UserInterface|null $user
   * @param array $options
   *
   * @return \Drupal\Core\Url
   */
  public function fromRoute(string $route, UserInterface $user, array $options = []): Url {
    $timestamp = \Drupal::time()->getRequestTime();
    $langcode = isset($options['langcode']) ? $options['langcode'] : $user->getPreferredLangcode();
    $hash = $this->hashUserPassword($user, $timestamp);

    $url_options = [
      'absolute' => TRUE,
      'language' => \Drupal::languageManager()->getLanguage($langcode),
    ];

    // @todo: Standardize parameter names for user action routes.
    if ($route === 'user.cancel_confirm') {
      $parameters = [
        'user' => $user->id(),
        'timestamp' => $timestamp,
        'hashed_pass' => $hash,
      ];
    }
    else {
      $parameters = [
        'uid' => $user->id(),
        'timestamp' => $timestamp,
        'hash' => $hash,
      ];
    }
    return Url::fromRoute($route, $parameters, $url_options);
  }

  /**
   * Check user password hash validity.
   *
   * Test whether the received hash matches one generated using the same
   * intended inputs.
   *
   * @param string $hash
   * @param \Drupal\user\UserInterface $user
   * @param int $timestamp
   *
   * @return bool
   */
  public function checkHash(string $hash, UserInterface $user, int $timestamp): Bool {
    return hash_equals($hash, $this->hashUserPassword($user, $timestamp));
  }

  /**
   * Creates a unique hash value for use in time-dependent per-user URLs.
   *
   * This hash is normally used to build a unique and secure URL that is sent to
   * the user by email for purposes such as resetting the user's password. In
   * order to validate the URL, the same hash can be generated again, from the
   * same information, and compared to the hash value from the URL. The hash
   * contains the time stamp, the user's last login time, the numeric user ID,
   * and the user's email address.
   *
   * @param \Drupal\user\UserInterface $user
   *   An object containing the user account.
   * @param int $timestamp
   *   A UNIX timestamp, typically REQUEST_TIME.
   *
   * @return string
   *   A string that is safe for use in URLs and SQL statements.
   *
   * @internal
   */
  private function hashUserPassword(UserInterface $user, $timestamp) {
    $data = $timestamp;
    $data .= $user->getLastLoginTime();
    $data .= $user->id();
    $data .= $user->getEmail();
    return Crypt::hmacBase64($data, Settings::getHashSalt() . $user->getPassword());
  }

}
