/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, drupalSettings) {
  Drupal.color = {
    logoChanged: false,
    callback: function callback(context, settings, $form) {
      if (!this.logoChanged) {
        $('.color-preview .color-preview-logo img').attr('src', drupalSettings.color.logo);
        this.logoChanged = true;
      }

      if (drupalSettings.color.logo === null) {
        $('div').remove('.color-preview-logo');
      }

      var $colorPreview = $form.find('.color-preview');
      var $colorPalette = $form.find('.js-color-palette');
      [].forEach.call($colorPreview, function (el) {
        el.style.backgroundColor = $colorPalette.find('input[name="palette[bg]"]').val();
      });
      [].forEach.call($colorPreview.find('.color-preview-main h2, .color-preview .preview-content'), function (el) {
        el.style.color = $colorPalette.find('input[name="palette[text]"]').val();
      });
      [].forEach.call($colorPreview.find('.color-preview-content a'), function (el) {
        el.style.color = $colorPalette.find('input[name="palette[link]"]').val();
      });
      var $colorPreviewBlock = $colorPreview.find('.color-preview-sidebar .color-preview-block');
      [].forEach.call($colorPreviewBlock, function (el) {
        el.style.backgroundColor = $colorPalette.find('input[name="palette[sidebar]"]').val();
        el.style.borderColor = $colorPalette.find('input[name="palette[sidebarborders]"]').val();
      });
      [].forEach.call($colorPreview.find('.color-preview-footer-wrapper'), function (el) {
        el.style.backgroundColor = $colorPalette.find('input[name="palette[footer]"]').val();
      });
      var gradientStart = $colorPalette.find('input[name="palette[top]"]').val();
      var gradientEnd = $colorPalette.find('input[name="palette[bottom]"]').val();
      $colorPreview.find('.color-preview-header').attr('style', "background-color: ".concat(gradientStart, "; background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, from(").concat(gradientStart, "), to(").concat(gradientEnd, ")); background-image: -moz-linear-gradient(-90deg, ").concat(gradientStart, ", ").concat(gradientEnd, ");"));
      [].forEach.call($colorPreview.find('.color-preview-site-name'), function (el) {
        el.style.color = $colorPalette.find('input[name="palette[titleslogan]"]').val();
      });
    }
  };
})(jQuery, Drupal, drupalSettings);