<?php

/**
 * @file
 * Contains user_cancel_test.module
 */

use Drupal\user\UserInterface;

/**
 * Implements hook_user_cancel_methods_alter().
 */
function user_cancel_test_user_cancel_methods_alter(array &$methods) {
  $methods['user_cancel_test'] = [
    'title' => 'User cancel test',
    'description' => 'User cancel test method',
  ];
}

/**
 * Implements hook_user_cancel().
 */
function user_cancel_test_user_cancel($edit, UserInterface $account, $method) {
  if ($method === 'user_cancel_test') {
    \Drupal::messenger()->addStatus('Custom user cancel method executed.');
  }
}
