<?php

/**
 * @file
 * Support module for user form testing.
 */

declare(strict_types=1);

use Drupal\Core\Hook\LegacyHook;
use Drupal\user_form_test\Hook\UserFormTestHooks;

/**
 * Implements hook_form_FORM_ID_alter() for user_cancel_form().
 */
#[LegacyHook]
function user_form_test_form_user_cancel_form_alter(&$form, &$form_state) {
  \Drupal::service(UserFormTestHooks::CLASS)->userFormTestFormUserCancelFormAlter($form, $form_state);
}
