<?php

/**
 * @file
 * Fetch community announcements from www.drupal.org feed.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function announcements_feed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.announcements_feed':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Announcements Feed module notifies users when there is an announcement from the Drupal community. For more information, see the <a href=":documentation">online documentation for the Announcements Feed module</a>.', [':documentation' => 'https://www.drupal.org/docs/core-modules-and-themes/core-modules/announcements-feed']) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl><dt>' . t('Accessing announcements') . '</dt>';
      $output .= '<dd>' . t('Site users with the "View drupal.org announcements" permission may click on the "Announcements" item in the administration toolbar to see all announcements relevant to the Drupal of your site.') . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_toolbar().
 */
function announcements_feed_toolbar() {
  $items['announcement'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#lazy_builder' => [
        'announcements_feed.lazy_builders:renderAnnouncements',
        [],
      ],
      '#create_placeholder' => TRUE,
      '#cache' => [
        'contexts' => ['user'],
        'tags' => [
          'announcements_feed:feed:' . \Drupal::currentUser()->id(),
        ],
      ],
    ],
    '#wrapper_attributes' => [
      'class' => ['announce-toolbar-tab'],
    ],
    '#cache' => ['contexts' => ['user.permissions']],
    '#access' => \Drupal::currentUser()->hasPermission('access announcements'),
    '#weight' => 3399,
  ];
  return $items;
}

/**
 * Implements hook_theme().
 */
function announcements_feed_theme($existing, $type, $theme, $path) {
  return [
    'announcements_feed' => [
      'variables' => [
        'featured' => NULL,
        'standard' => NULL,
        'count' => 0,
      ],
    ],
    'announcements_feed_admin' => [
      'variables' => [
        'featured' => NULL,
        'standard' => NULL,
        'count' => 0,
      ],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function announcements_feed_cron() {
  $config = \Drupal::config('announcements_feed.settings');
  $interval = $config->get('cron_interval');
  $last_check = \Drupal::state()->get('announcements_feed.last_fetch', 0);
  $time = \Drupal::time()->getRequestTime();
  if (($time - $last_check) > $interval) {
    \Drupal::service('announcements_feed.fetcher')->fetch(TRUE);
    \Drupal::state()->set('announcements_feed.last_fetch', $time);
  }
}
