/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, drupalSettings, A11yAutocomplete, once) {
  Drupal.Autocomplete = {};
  Drupal.Autocomplete.instances = {};
  Drupal.Autocomplete.defaultOptions = {
    createLiveRegion: false,
    minCharAssistiveHint: Drupal.t('Type @count or more characters for results'),
    noResultsAssistiveHint: Drupal.t('No results found'),
    someResultsAssistiveHint: Drupal.t('There are @count results available.'),
    oneResultAssistiveHint: Drupal.t('There is one result available.'),
    inputAssistiveHint: Drupal.t('When autocomplete results are available use up and down arrows to review and enter to select.  Touch device users, explore by touch or with swipe gestures.'),
    highlightedAssistiveHint: Drupal.t('@selectedItem @position of @count is highlighted')
  };

  Drupal.Autocomplete.initialize = function (autocompleteInput) {
    var options = Drupal.Autocomplete.defaultOptions || {};

    if (!autocompleteInput.hasAttribute('data-autocomplete-cardinality')) {
      autocompleteInput.setAttribute('data-autocomplete-cardinality', '-1');
    }

    if (autocompleteInput.hasAttribute('data-autocomplete-first-character-blacklist')) {
      options.firstCharacterIgnoreList = autocompleteInput.getAttribute('data-autocomplete-first-character-blacklist');
      Drupal.deprecationError({
        message: 'The data-autocomplete-first-character-blacklist attribute is deprecated in drupal:9.3.0 and is removed from drupal:10.0.0. Use data-autocomplete-first-character-ignore-list instead See https://www.drupal.org/node/3083715'
      });
    }

    var path = autocompleteInput.dataset.autocompletePath;

    if (path) {
      options.source = Drupal.Autocomplete.ajaxSearchProvider(path);
    }

    delete autocompleteInput.dataset.autocompletePath;
    var autocomplete = A11yAutocomplete(autocompleteInput, options);
    var instance = autocomplete._internal_object;
    document.dispatchEvent(new CustomEvent('drupal-autocomplete-init', {
      detail: {
        instance: instance,
        options: options
      }
    }));

    function autocompleteSendToLiveRegion(message) {
      Drupal.announce(message, 'assertive');
    }

    instance.sendToLiveRegion = autocompleteSendToLiveRegion;
    return autocomplete;
  };

  Drupal.behaviors.autocomplete = {
    attach: function attach() {
      if (once('autocomplete-lifecycle', 'body').length) {
        document.addEventListener('autocomplete-destroy', function (e) {
          delete Drupal.Autocomplete.instances[e.detail.autocomplete.id];
        });
        document.addEventListener('autocomplete-created', function (e) {
          Drupal.Autocomplete.instances[e.detail.autocomplete.id] = e.detail.autocomplete;
        });
      }

      once('autocomplete-init', 'input.form-autocomplete').forEach(Drupal.Autocomplete.initialize);
    },
    detach: function detach(context, settings, trigger) {
      if (trigger === 'unload') {
        once.remove('autocomplete-init', 'input.form-autocomplete', context).forEach(function (input) {
          if (input.id in Drupal.Autocomplete.instances) {
            Drupal.Autocomplete.instances[input.id].destroy();
          }
        });
      }
    }
  };

  Drupal.Autocomplete.ajaxSearchProvider = function (path) {
    var cache = {};
    return function (search, results) {
      function sourceCallbackHandler(data) {
        cache[search] = data;
        results(data);
      }

      function error() {
        results([]);
      }

      if (search in cache) {
        results(cache[search]);
      } else {
        var options = $.extend({
          success: sourceCallbackHandler,
          error: error,
          data: {
            q: search
          }
        }, {
          dataType: 'json',
          jsonp: false
        });
        $.ajax(path, options);
      }
    };
  };
})(jQuery, Drupal, drupalSettings, A11yAutocomplete, once);