/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

function _slicedToArray(arr, i) { return _arrayWithHoles(arr) || _iterableToArrayLimit(arr, i) || _unsupportedIterableToArray(arr, i) || _nonIterableRest(); }

function _nonIterableRest() { throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."); }

function _unsupportedIterableToArray(o, minLen) { if (!o) return; if (typeof o === "string") return _arrayLikeToArray(o, minLen); var n = Object.prototype.toString.call(o).slice(8, -1); if (n === "Object" && o.constructor) n = o.constructor.name; if (n === "Map" || n === "Set") return Array.from(o); if (n === "Arguments" || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)) return _arrayLikeToArray(o, minLen); }

function _arrayLikeToArray(arr, len) { if (len == null || len > arr.length) len = arr.length; for (var i = 0, arr2 = new Array(len); i < len; i++) { arr2[i] = arr[i]; } return arr2; }

function _iterableToArrayLimit(arr, i) { var _i = arr == null ? null : typeof Symbol !== "undefined" && arr[Symbol.iterator] || arr["@@iterator"]; if (_i == null) return; var _arr = []; var _n = true; var _d = false; var _s, _e; try { for (_i = _i.call(arr); !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"] != null) _i["return"](); } finally { if (_d) throw _e; } } return _arr; }

function _arrayWithHoles(arr) { if (Array.isArray(arr)) return arr; }

function ownKeys(object, enumerableOnly) { var keys = Object.keys(object); if (Object.getOwnPropertySymbols) { var symbols = Object.getOwnPropertySymbols(object); if (enumerableOnly) { symbols = symbols.filter(function (sym) { return Object.getOwnPropertyDescriptor(object, sym).enumerable; }); } keys.push.apply(keys, symbols); } return keys; }

function _objectSpread(target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i] != null ? arguments[i] : {}; if (i % 2) { ownKeys(Object(source), true).forEach(function (key) { _defineProperty(target, key, source[key]); }); } else if (Object.getOwnPropertyDescriptors) { Object.defineProperties(target, Object.getOwnPropertyDescriptors(source)); } else { ownKeys(Object(source)).forEach(function (key) { Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key)); }); } } return target; }

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

(function ($, Drupal) {
  Drupal.autocompleteShim = {
    overrides: {}
  };
  document.addEventListener('drupal-autocomplete-init', function (e) {
    var _e$detail = e.detail,
        instance = _e$detail.instance,
        options = _e$detail.options;
    Drupal.autocompleteShim.jqueryUiShimInit(instance, options);
  });

  var applyWidgetOverrides = function applyWidgetOverrides(instance, propertyToOverride, overrideWith) {
    if (propertyToOverride.substr(0, 1) === '_') {
      instance[propertyToOverride] = overrideWith;
    }
  };

  Drupal.autocompleteShim.defaultOptions = {};

  Drupal.autocompleteShim.jqueryUiShimInit = function (instance, options) {
    var BCMarkupOptions = {};
    var usingBCMarkup = Drupal.hasOwnProperty('jQueryAutocompleteStableMarkup');

    if (usingBCMarkup) {
      BCMarkupOptions = Drupal.jQueryAutocompleteStableMarkup.options;
    }

    var isContentEditable = instance.input.hasAttribute('contenteditable');
    var attributesToOptions = instance.attributesToOptions();

    if (attributesToOptions.hasOwnProperty('source') && typeof attributesToOptions.source === 'string') {
      attributesToOptions.source = JSON.parse(attributesToOptions.source);
    }

    instance.options = instance.initOptions(instance.options, Drupal.autocompleteShim.defaultOptions, BCMarkupOptions, options, attributesToOptions);

    var jQueryUIAutocompleteNormalizeItem = function jQueryUIAutocompleteNormalizeItem(_ref) {
      var label = _ref.label,
          value = _ref.value,
          item = _ref.item;

      if (typeof item === 'string') {
        return {
          label: label,
          value: value
        };
      }

      return _objectSpread(_objectSpread({}, item), {}, {
        label: label,
        value: value
      });
    };

    instance.applyClasses('input');
    instance.applyClasses('listbox');
    instance.liveRegion = document.querySelector('#drupal-live-announce');
    instance.options.isMultiline = instance.input.tagName === 'TEXTAREA' || instance.input.tagName !== 'INPUT' && isContentEditable;

    if (instance.options.allowRepeatValues === null) {
      instance.options.allowRepeatValues = true;
    }

    function shimmedInputKeyDown(e) {
      if (instance.options.isMultiline) {
        this.input.value = this.input.textContent;
      }

      var keyCode = e.keyCode;

      if (this.isOpened) {
        if (keyCode === this.keyCode.ESC) {
          this.close();
        }

        if (keyCode === this.keyCode.DOWN || keyCode === this.keyCode.UP) {
          e.preventDefault();
          this.preventCloseOnBlur = true;
          var selector = keyCode === this.keyCode.DOWN ? 'li[role="option"]' : 'li[role="option"]:last-child';
          this.highlightItem(this.listboxWrapper.querySelector(selector));
        }

        if (keyCode === this.keyCode.RETURN) {
          var active = instance.listboxWrapper.querySelectorAll('.ui-menu-item-wrapper.ui-state-active');

          if (active.length || instance.listboxWrapper.contains(document.activeElement)) {
            e.preventDefault();
          }
        }
      }

      if (this.input.nodeName === 'INPUT' && !this.isOpened && Array.isArray(this.options.source) && this.options.source.length > 0 && (keyCode === this.keyCode.DOWN || keyCode === this.keyCode.UP)) {
        e.preventDefault();
        this.preventCloseOnBlur = true;
        var typed = this.extractLastInputValue();

        if (!typed && this.options.minChars < 1) {
          var normalizedResults = this.normalizeSuggestionItems(this.options.source);
          this.displayResults(normalizedResults);
        } else {
          this.displayResults(this.suggestions);
        }

        if (this.isOpened) {
          var _selector = keyCode === this.keyCode.DOWN ? 'li[role="option"]' : 'li[role="option"]:last-child';

          this.highlightItem(this.listboxWrapper.querySelector(_selector));
        }
      }

      this.removeAssistiveHint();
    }

    instance.inputKeyDown = shimmedInputKeyDown;

    function jQueryDisplayResults(suggestionItems) {
      var _this = this;

      this.suggestions = suggestionItems;
      this.listboxWrapper.innerHTML = '';

      if (this.suggestions.length) {
        if (this.options.sort !== false) {
          this.suggestions = this.sortSuggestions(this.suggestions);
        }

        this._renderMenu(this.listboxWrapper, this.suggestions.map(jQueryUIAutocompleteNormalizeItem));
      }

      if (this.suggestions.length === 0) {
        this.close();
      } else {
        this.open();
      }

      window.clearTimeout(this.announceTimeOutId);
      this.announceTimeOutId = setTimeout(function () {
        return _this.sendToLiveRegion(_this.resultsMessage(_this.suggestions.length));
      }, 1400);
    }

    instance.displayResults = jQueryDisplayResults;

    instance._renderMenu = function (ul, items) {
      instance.jQuerySuggestionCounter = 0;
      var that = this;
      $.each(items, function (index, item) {
        instance.jQuerySuggestionCounter = index;

        that._renderItemData(ul, item);
      });
    };

    instance._renderItemData = function (ul, item) {
      return this._renderItem(ul, item).data('ui-autocomplete-item', item);
    };

    var suggestionItem = instance.suggestionItem.bind(instance);

    instance.suggestionItem = function jQuerySuggestionItem(_ref2) {
      var label = _ref2.label,
          index = _ref2.index;
      var li = suggestionItem({
        label: label,
        index: index
      });

      if (instance.hasOwnProperty('addBcListItemClasses')) {
        instance.addBcListItemClasses(li, index);
      }

      return li;
    };

    if (!usingBCMarkup) {
      instance._renderItem = function (ul, item) {
        var li = instance.suggestionItem({
          label: item.label,
          index: instance.jQuerySuggestionCounter
        });
        return $(li).appendTo(ul);
      };
    }

    if (isContentEditable) {
      instance.getValue = function () {
        return this.input.textContent;
      };
    }

    var closeOnClickOutside = function closeOnClickOutside(event) {
      var menuElement = instance.listboxWrapper;
      var targetInWidget = event.target === instance.input || event.target === menuElement || $.contains(menuElement, event.target);

      if (!targetInWidget) {
        instance.close();
      }
    };

    instance.input.addEventListener('autocomplete-open', function () {
      document.body.addEventListener('mousedown', closeOnClickOutside);
      $(instance.listboxWrapper).position({
        of: instance.input,
        my: 'left top',
        at: 'left bottom',
        collision: 'none'
      });
    });
    instance.input.addEventListener('autocomplete-close', function () {
      document.body.removeEventListener('mousedown', closeOnClickOutside);
    });
    instance.listboxWrapper.addEventListener('mousedown', function (e) {
      e.preventDefault();
    });
    Object.keys(Drupal.autocompleteShim.overrides).forEach(function (propertyToOverride) {
      var overrideWith = Drupal.autocompleteShim.overrides[propertyToOverride];
      applyWidgetOverrides(instance, propertyToOverride, overrideWith);
    });
  };

  var oldAutocomplete = $.fn.autocomplete;
  $.fn.extend({
    autocomplete: function autocomplete() {
      var _this2 = this;

      for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
        args[_key] = arguments[_key];
      }

      if (oldAutocomplete && (!this.length || !this[0].classList.contains('form-autocomplete'))) {
        if (typeof this.data('ui-autocomplete') === 'undefined') {}

        return oldAutocomplete.apply(this, args);
      }

      Drupal.deprecationError({
        message: 'The autocomplete() function is deprecated in drupal:9.4.0 and is removed from drupal:10.0.0. Use the API provided by core/a11y_autocomplete instead. See https://www.drupal.org/node/3083715'
      });
      var id = this.attr('id');
      var optionMapping = {
        autoFocus: 'autoFocus',
        classes: null,
        delay: 'searchDelay',
        disabled: 'disabled',
        minLength: 'minChars',
        position: null,
        source: null
      };

      if (typeof args[0] === 'string') {
        if (!Drupal.Autocomplete.instances[id]) {
          return;
        }

        var instance = Drupal.Autocomplete.instances[id]._internal_object;
        var method = args[0];

        switch (method) {
          case 'widget':
            return $(instance.listboxWrapper);

          case 'instance':
            var instanceToReturn = {
              document: $(document),
              element: $(instance.input),
              menu: {
                element: $(instance.listboxWrapper)
              },
              liveRegion: $(instance.liveRegion),
              isMultiLine: instance.options.isMultiLine,
              isNewMenu: null,
              options: instance.options,
              window: window
            };
            ['bindings', 'eventNamespace', 'classesElementLookup', 'focusable', 'hoverable', 'uuid', 'source', 'valueMethod'].forEach(function (property) {
              Object.defineProperty(instanceToReturn, property, {
                get: function get() {
                  return console.warn("The ".concat(property, " property is not supported beginning with 9.3, as jQuery UI Autocomplete is no longer part of core. See https://www.drupal.org/node/3083715"));
                }
              });
            });
            return instanceToReturn;

          case 'disable':
            this.autocomplete('option', 'disabled', true);
            break;

          case 'enable':
            this.autocomplete('option', 'disabled', false);
            break;

          case 'search':
            instance.input.focus();

            if (typeof args[1] === 'string') {
              instance.input.value = args[1];

              if (instance.input.hasAttribute('contenteditable')) {
                instance.input.textContent = args[1];
              }
            } else if (instance.input.hasAttribute('contenteditable')) {
              instance.input.value = instance.input.textContent;
            }

            if (instance.input.value.length === 0 && instance.options.minChars === 0 && Array.isArray(instance.options.source) && instance.options.source.length > 0) {
              var normalizedResults = instance.normalizeSuggestionItems(instance.options.source);
              instance.displayResults(normalizedResults);
            } else {
              instance.doSearch($.Event('keydown'));
            }

            break;

          case 'option':
            if (typeof args[2] === 'undefined' && args[1] === 'object') {
              Object.keys(args[1]).forEach(function (key) {
                _this2.autocomplete('option', key, args[1][key]);
              });
            }

            if (typeof args[2] !== 'undefined' && typeof args[1] === 'string') {
              var optionName = args[1],
                  optionValue = args[2];
              var listBoxId = instance.listboxWrapper.getAttribute('id');

              switch (optionName) {
                case 'appendTo':
                  var appendTo = null;

                  if (typeof optionValue === 'string') {
                    appendTo = document.querySelector(optionValue);
                  } else if (optionValue instanceof jQuery) {
                    appendTo = optionValue.length > 0 ? optionValue[0] : null;
                  } else {
                    appendTo = optionValue;
                  }

                  if (!appendTo) {
                    var closestUiFront = $(instance.input).closest('.ui-front, dialog');

                    if (closestUiFront.length > 0) {
                      var _closestUiFront = _slicedToArray(closestUiFront, 1);

                      appendTo = _closestUiFront[0];
                    }
                  }

                  if (appendTo) {
                    if (!appendTo.contains(instance.listboxWrapper)) {
                      appendTo.appendChild(instance.listboxWrapper);
                    }

                    instance.listboxWrapper = appendTo.querySelector("#".concat(listBoxId));
                  }

                  instance.input.setAttribute('data-autocomplete-list-appended', true);
                  break;

                case 'classes':
                  Object.keys(optionValue).forEach(function (key) {
                    if (key === 'ui-autocomplete' || key === 'ui-autocomplete-input') {
                      var element = key === 'ui-autocomplete' ? instance.listboxWrapper : instance.input;
                      instance.addClasses(element, optionValue[key]);
                      instance.removeClasses(element, key);
                    }
                  });
                  break;

                case 'classes.ui-autocomplete':
                  instance.addClasses(instance.listboxWrapper, optionValue);
                  instance.removeClasses(instance.listboxWrapper, 'ui-autocomplete');
                  break;

                case 'classes.ui-autocomplete-input':
                  instance.addClasses(instance.input, optionValue);
                  instance.removeClasses(instance.input, 'ui-autocomplete-input');
                  break;

                case 'disabled':
                  instance.options.disabled = optionValue;
                  $(instance.listboxWrapper).toggleClass('ui-autocomplete-disabled', optionValue);
                  break;

                case 'position':
                  $(instance.listboxWrapper).position(_objectSpread({
                    of: instance.input,
                    my: 'left top',
                    at: 'left bottom',
                    collision: 'none'
                  }, optionValue));
                  break;

                case 'source':
                  if (typeof optionValue === 'function') {
                    instance.options.source = function (search, results) {
                      optionValue({
                        term: search
                      }, results);
                    };
                  } else if (typeof optionValue === 'string') {
                    instance.options.source = Drupal.Autocomplete.ajaxSearchProvider(optionValue);
                  } else {
                    instance.options.source = optionValue;
                  }

                  break;

                default:
                  if (['change', 'close', 'create', 'focus', 'open', 'response', 'search', 'select'].includes(optionName)) {
                    this.on("autocomplete".concat(optionName), optionValue);
                  }

                  if (optionMapping.hasOwnProperty(optionName)) {
                    instance.options[optionMapping[optionName]] = optionValue;
                    instance.options[optionName] = optionValue;
                  }

                  break;
              }
            } else if (typeof args[1] === 'string') {
              return instance.options(args[1]);
            }

            break;

          default:
            if (typeof instance[method] === 'function') {
              instance[method]();
            }

            break;
        }
      } else {
        var _id = this.attr('id');

        if (!Drupal.Autocomplete.instances[_id]) {
          Drupal.Autocomplete.initialize(this[0]);
        }

        if (_typeof(args[0]) === 'object') {
          Object.keys(args[0]).forEach(function (key) {
            if (key === 'widgetOverrides') {
              var widgetOverrides = args[0].widgetOverrides;
              Object.keys(widgetOverrides).forEach(function (propertyToOverride) {
                var overrideWith = widgetOverrides[propertyToOverride];
                var instance = Drupal.Autocomplete.instances[_id]._internal_object;
                applyWidgetOverrides(instance, propertyToOverride, overrideWith);
              });
            } else {
              _this2.autocomplete('option', key, args[0][key]);
            }
          });
        }
      }

      return this;
    }
  });

  if (!$.ui.hasOwnProperty('autocomplete')) {
    $.ui.autocomplete = function () {
      console.warn('$.ui.autocomplete no longer exists due to its removal in Drupal 9.4.0. Existing uses of $().autocomplete() will continue to work. See https://www.drupal.org/node/3083715');
    };

    $.ui.autocomplete.shimmed = true;
  }
})(jQuery, Drupal);