<?php

namespace Drupal\file\Controller;

use Drupal\Core\DependencyInjection\ContainerInjectionInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\Core\Session\SessionManagerInterface;
use Drupal\Core\StringTranslation\StringTranslationTrait;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * Defines a controller to respond to file widget AJAX requests.
 */
class FileWidgetAjaxController implements ContainerInjectionInterface {

  use StringTranslationTrait;

  /**
   * The PHP session handler.
   *
   * @var string
   */
  protected $PHPSessionHandler;

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    return new static($container->get('session_manager'));
  }

  /**
   * Constructs a FileWidgetAjaxController object.
   *
   * @param \Drupal\Core\Session\SessionManagerInterface $session_manager
   *   The session manager.
   */
  public function __construct(SessionManagerInterface $session_manager) {
    if (method_exists($session_manager, 'getPHPSessionHandler')) {
      $this->PHPSessionHandler = $session_manager->getPHPSessionHandler();
    }
    else {
      $this->PHPSessionHandler = 'files';
    }
  }

  /**
   * Returns the progress status for a file upload process.
   *
   * @param string $key
   *   The unique key for this upload process.
   *
   * @return \Symfony\Component\HttpFoundation\JsonResponse
   *   A JsonResponse object.
   */
  public function progress($key) {
    $progress = [
      'message' => $this->t('Starting upload...'),
      'percentage' => -1,
    ];

    $implementation = file_progress_implementation();
    if ($implementation == 'uploadprogress') {
      $status = uploadprogress_get_info($key);
      if (isset($status['bytes_uploaded']) && !empty($status['bytes_total'])) {
        $progress['message'] = $this->t('Uploading... (@current of @total)', [
          '@current' => format_size($status['bytes_uploaded']),
          '@total' => format_size($status['bytes_total']),
        ]);
        $progress['percentage'] = round(100 * $status['bytes_uploaded'] / $status['bytes_total']);
      }
    }
    elseif ($implementation == 'session') {
      // PHP saves file upload data to the session before Drupal starts.  This
      // works only if the default session name has been configured to match the
      // one generated by Drupal so PHP can recognize the browser’s cookie
      // before Drupal starts.

      // Get upload status from the PHP session.
      $status = [];
      session_module_name($this->PHPSessionHandler);
      $var = \Drupal::request()->get('status');
      if (isset($_SESSION[$var])) {
        $status = $_SESSION[$var];
      }

      if (isset($status['bytes_processed']) && !empty($status['content_length'])) {
        $progress['message'] = t('Uploading... (@current of @total)', ['@current' => format_size($status['bytes_processed']), '@total' => format_size($status['content_length'])]);
        $progress['percentage'] = round(100 * $status['bytes_processed'] / $status['content_length']);
      }
    }

    return new JsonResponse($progress);
  }

}
