<?php

/**
 * @file
 * Enables users to rename URLs.
 */

declare(strict_types = 1);

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\path_alias\Form\SystemInformationFormAlter;
use Drupal\path_alias\Plugin\Condition\PathAliasRequestPath;

/**
 * Implements hook_help().
 */
function path_alias_help($route_name, RouteMatchInterface $route_match): string {
  switch ($route_name) {
    case 'help.page.path_alias':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      // @todo put something meaningful here.
      $output .= '<p>' . t('The Path alias module foo bar baz') . '</p>';
      $output .= '<p>' . t('For more information, see the <a href=":path_alias">online documentation for the Path alias module</a>.', [':path_alias' => 'https://www.drupal.org/documentation/modules/path_alias']);
      return $output;
  }
  return '';
}

/**
 * Implements hook_condition_info_alter().
 */
function path_alias_condition_info_alter(array &$definitions): void {
  if (isset($definitions['request_path'])) {
    $definitions['request_path']['class'] = PathAliasRequestPath::class;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function path_alias_form_system_site_information_settings_alter(array &$form): void {
  Drupal::classResolver()
    ->getInstanceFromDefinition(SystemInformationFormAlter::class)
    ->alterForm($form);
}
