<?php

/**
 * @file
 * Install, update and uninstall functions for the Path alias module.
 */

use Drupal\Core\Entity\Sql\SqlContentEntityStorage;
use Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema;

/**
 * Implements hook_update_dependencies().
 */
function path_alias_update_dependencies() {
  $dependencies = [];
  $dependencies['path_alias'][10001] = [
    'system' => 10001,
  ];
  return $dependencies;
}

/**
 * Make various path alias fields required at the storage level.
 *
 * The SQL content entity schema no longer uses entity keys to mark their
 * corresponding fields as NOT NULL in the database, so we need to update the
 * respective fields manually.
 */
function path_alias_update_10001() {
  $entity_type_manager = \Drupal::entityTypeManager();

  $entity_type_id = 'path_alias';
  $storage = $entity_type_manager->getStorage($entity_type_id);
  if ($storage instanceof SqlContentEntityStorage) {
    $ref_get_storage_schema = new \ReflectionMethod($storage, 'getStorageSchema');
    $ref_get_storage_schema->setAccessible(TRUE);
    /** @var \Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema $storage_schema */
    $storage_schema = $ref_get_storage_schema->invoke($storage);
    if ($storage_schema instanceof SqlContentEntityStorageSchema) {
      $storage_schema::updateToStorageSchemaV2($entity_type_id);
    }
  }
}
