/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.jQueryAutocompleteStableMarkup = {};
  document.addEventListener('drupal-autocomplete-init', function (e) {
    var _e$detail = e.detail,
        instance = _e$detail.instance,
        options = _e$detail.options;
    Drupal.jQueryAutocompleteStableMarkup.options = {
      inputClass: 'ui-autocomplete-input',
      ulClass: 'ui-menu ui-widget ui-widget-content ui-autocomplete ui-front',
      loadingClass: 'ui-autocomplete-loading',
      itemClass: 'ui-menu-item'
    };
    Drupal.jQueryAutocompleteStableMarkup.init(instance, options);
  });

  Drupal.jQueryAutocompleteStableMarkup.init = function (instance, options) {
    instance.options = Object.assign(instance.options, Drupal.autocompleteShim.stableOptions);
    instance.implementInput();
    instance.implementList();

    if (!instance.input.hasAttribute('data-autocomplete-list-appended')) {
      var listBoxId = instance.ul.getAttribute('id');
      var uiFront = $(instance.input).closest('.ui-front, dialog');
      var appendTo = uiFront.length > 0 ? uiFront[0] : document.querySelector('body');
      appendTo.appendChild(instance.ul);
      instance.ul = document.querySelector("#".concat(listBoxId));
    }

    instance._renderItem = function (ul, item) {
      var propertyToDisplay = instance.options.displayLabels ? 'label' : 'value';
      return $('<li>').append($('<a>').html(item[propertyToDisplay])).appendTo(ul);
    };

    instance.addBcListItemClasses = function (li, index) {
      var a = li.querySelector('a');
      a.classList.add('ui-menu-item-wrapper');
      a.setAttribute('id', "ui-id-".concat(index));
    };

    instance.input.addEventListener('focus', function () {
      instance.ul.querySelectorAll('.ui-menu-item-wrapper.ui-state-active').forEach(function (element) {
        element.classList.remove('ui-state-active');
      });
    });
    instance.input.addEventListener('autocomplete-highlight', function () {
      instance.ul.querySelectorAll('.ui-menu-item-wrapper.ui-state-active').forEach(function (element) {
        element.classList.remove('ui-state-active');
      });
      document.activeElement.querySelector('.ui-menu-item-wrapper').classList.add('ui-state-active');
    });
    $(instance.input).unwrap('[data-autocomplete-wrapper]');
    $(instance.input).data('ui-autocomplete', instance);
  };
})(jQuery, Drupal);