# Schema for the configuration files of the Olivero theme.

olivero.settings:
  type: theme_settings
  label: 'olivero settings'
  mapping:
    mobile_menu_all_widths:
      type: integer
      label: 'Mobile menu all widths'
    site_branding_bg_color:
      type: string
      label: 'Site branding background color'
    base_primary_color:
      type: color_hex
      label: 'Base Primary Color'
