<?php

/**
 * @file
 * Install, update and uninstall functions for the dblog module.
 */

use Drupal\user\Entity\Role;
use Drupal\views\Entity\View;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_schema().
 */
function dblog_schema(): array {
  $schema['watchdog'] = [
    'description' => 'Table that contains logs of all system events.',
    'fields' => [
      'wid' => [
        'type' => 'serial',
        'not null' => TRUE,
        'size' => 'big',
        'description' => 'Primary Key: Unique watchdog event ID.',
      ],
      'uid' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The {users}.uid of the user who triggered the event.',
      ],
      'type' => [
        'type' => 'varchar_ascii',
        'length' => 64,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Type of log message, for example "user" or "page not found."',
      ],
      'message' => [
        'type' => 'text',
        'not null' => TRUE,
        'size' => 'big',
        'description' => 'Text of log message to be passed into the t() function.',
      ],
      'variables' => [
        'type' => 'blob',
        'not null' => TRUE,
        'size' => 'big',
        'description' => 'Serialized array of variables that match the message string and that is passed into the t() function.',
      ],
      'severity' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'size' => 'tiny',
        'description' => 'The severity level of the event; ranges from 0 (Emergency) to 7 (Debug)',
      ],
      'link' => [
        'type' => 'text',
        'not null' => FALSE,
        'description' => 'Link to view the result of the event.',
      ],
      'location'  => [
        'type' => 'text',
        'not null' => TRUE,
        'description' => 'URL of the origin of the event.',
      ],
      'referer' => [
        'type' => 'text',
        'not null' => FALSE,
        'description' => 'URL of referring page.',
      ],
      'hostname' => [
        'type' => 'varchar_ascii',
        'length' => 128,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Hostname of the user who triggered the event.',
      ],
      'timestamp' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Unix timestamp of when event occurred.',
        'size' => 'big',
      ],
    ],
    'primary key' => ['wid'],
    'indexes' => [
      'type' => ['type'],
      'uid' => ['uid'],
      'severity' => ['severity'],
    ],
  ];

  return $schema;
}

/**
 * Implements hook_update_last_removed().
 */
function dblog_update_last_removed(): int {
  return 10101;
}

/**
 * Add access dblog reports permission to roles with access site reports permission.
 */
function dblog_update_112001(&$sandbox): void {
  // Get all installed roles.
  $roles = Role::loadMultiple();

  // Iterate over all installed roles.
  foreach ($roles as $role) {
    if ($role->hasPermission('access site reports')) {
      // Add the access dblog reports permission.
      $role->grantPermission('access dblog reports');

      // Save the role.
      $role->save();
    }
  }
}

/**
 * Update permission on the Watchdog view (if it uses the default).
 */
function dblog_update_112002(&$sandbox): void {
  // Load the Watchdog view.
  $watchdog_view = View::load('watchdog');

  if ($watchdog_view instanceof ViewExecutable) {
    // Get the permission used on the default display.
    $current_perm = $watchdog_view
      ->getDisplay('default')
      ->getOption('access')['options']['perm'];

    if ($current_perm == 'access site reports') {
      // Set the permission on the default display to 'access dblog reports' if
      // the permission is currently the old default, 'access site reports'.
      $watchdog_view->getDisplay('default')->setOption('access', [
        'type' => 'perm',
        'options' => [
          'perm' => 'access dblog reports',
        ],
      ]);

      // Save the view.
      $watchdog_view->save();
    }
  }
}
