# Schema for the configuration files of the Automated cron module.

automated_cron.settings:
  type: config_object
  label: 'Automated cron settings'
  constraints:
    FullyValidatable: ~
  mapping:
    interval:
      type: integer
      label: 'Run cron every'
      constraints:
        Range:
          min: 0
    max_concurrent_queue_process:
      type: integer
      label: 'Maximum number of concurrent queue processing'
      requiredKey: false
      constraints:
        Range:
          min: 1
    max_items_to_process:
      type: integer
      label: 'Number of items to process. Set to 0 disable instant queue processing'
      requiredKey: false
      constraints:
        Range:
          min: 0
