<?php

declare(strict_types=1);

namespace Drupal\Core\Database;

trait JsonpathGeneratedFieldTrait {

  /**
   * Prefix for auto-generated fields.
   *
   * @todo Convert this to a constant when the minimum PHP version is >= 8.2.
   */
  protected static string $autoGeneratedFieldPrefix = 'auto_gen_';

  /**
   * Get the name for an automatically-created generated column for a jsonpath.
   *
   * @param string $field
   *   Source field.
   * @param string $jsonpath
   *   The jsonpath.
   *
   * @return string
   *   The column name.
   */
  public static function getJsonpathGeneratedFieldName(string $field, string $jsonpath): string {
    return sprintf(
      '%s_%s',
      self::getJsonpathGeneratedFieldPrefix($field),
      sha1($jsonpath),
    );
  }

  /**
   * Get the prefix for auto-generated fields for a given source field.
   *
   * @param string $field
   *   Source field.
   *
   * @return string
   *   Prefix for auto-generated fields.
   */
  public static function getJsonpathGeneratedFieldPrefix(string $field): string {
    return sprintf('%s%s', self::$autoGeneratedFieldPrefix, $field);
  }

  /**
   * Get the expression to retrieve a JSON value at a given jsonpath.
   *
   * This is database-specific.
   *
   * @param string $field
   *   Field name.
   * @param string $jsonpath
   *   Jsonpath.
   *
   * @return string
   *   Database expression to retrieve data at this jsonpath.
   */
  abstract protected static function getJsonExtractValueExpression(string $field, string $jsonpath): string;

  /**
   * Generate SQL statement(s) for generated fields derived from JSON hotpaths.
   *
   * @param string $field_name
   *   Field name.
   * @param array $table
   *   Table definition.
   * @param string $table_name
   *   Table name.
   *
   * @return array
   *   Array of SQL statements for the auto-generated fields.
   */
  protected function processJsonpathGeneratedFields(string $field_name, array &$table, string $table_name): array {
    $statements = [];
    $field = $table['fields'][$field_name];
    if (!empty($field['json_hotpaths'])) {
      // JSON fields may contain a list of jsonpath expressions that are known
      // to be regularly accessed and should be optimized through an index.
      foreach ($field['json_hotpaths'] as $hotpath) {
        $hotpath_name = static::getJsonpathGeneratedFieldName($field_name, $hotpath['jsonpath']);
        $hotpath_field_spec = [
          'type' => $hotpath['type'],
          'as' => static::getJsonExtractValueExpression($field_name, $hotpath['jsonpath']),
          'description' => 'Automatically-created generated column for JSON data indexing.',
        ];
        $statements[] = $this->createFieldSql($hotpath_name, $this->processField($hotpath_field_spec));
        // The index creation code needs the field spec.
        $table['fields'][$hotpath_name] = $hotpath_field_spec;
        $table['indexes'][$hotpath_name] = [$hotpath_name];
      }
    }
    return $statements;
  }

}
