<?php

/**
 * @file
 * Install, update and uninstall functions for the Config module.
 */

/**
 * Adds default value for the mail_notification config parameter.
 */
function config_update_10100() {
  $configFactory = \Drupal::configFactory();
  $config = $configFactory->getEditable('system.site');
  // If the value doesn't exist it always returns NULL.
  if (is_null($config->get('mail_notification'))) {
    $config->set('mail_notification', NULL)->save();
  }
}
