<?php

/**
 * @file
 * Install, update, and uninstall functions for the announcements_feed module.
 */

/**
 * Implements hook_install().
 */
function announcements_feed_install() {
  // Creating the default values.
  variable_set('announcements_feed_max_age', 86400);
  variable_set('announcements_feed_cron_interval', 21600);
  variable_set('announcements_feed_limit', 10);
  variable_set('announcements_feed_json_url', 'https://www.drupal.org/announcements.json');
  variable_set('announcements_feed_link', 'https://www.drupal.org/about/announcements');
}

/**
 * Implements hook_uninstall().
 */
function announcements_feed_uninstall() {
  // Delete the announcements_feed module variables.
  variable_del('announcements_feed_limit');
  variable_del('announcements_feed_cron_interval');
  variable_del('announcements_feed_max_age');
  variable_del('announcements_feed_json_url');
  variable_del('announcements_feed_link');
  variable_del('announcements_feed_last_fetch');
}
