<?php

/**
 * @file
 * Install, update, and uninstall functions for the announcements_feed module.
 */

/**
 * Implements hook_schema().
 */
function announcements_feed_schema() {
  $schema['cache_announce'] = drupal_get_schema_unprocessed('system', 'cache');
  $schema['cache_announce']['description'] = 'Cache table for the announce module to store the recent announcements, fetched from central server.';
  return $schema;
}

/**
 * Implements hook_install().
 */
function announcements_feed_install() {
  // Creating the default values.
  variable_set('max_age', 1400);
  variable_set('feed_url', 'https://www.drupal.org/announcements.json');
  variable_set('feed_link', 'https://www.drupal.org/about/announcements');
}

/**
 * Implements hook_uninstall().
 */
function announcements_feed_uninstall() {
  // Deleting the announcements_feed variable.
  variable_del('max_age');
  variable_del('feed_url');
  variable_del('feed_link');
}
