/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, drupalSettings) {
  var options = $.extend({
    breakpoints: {
      'toolbar.narrow': '',
      'toolbar.standard': '',
      'toolbar.wide': ''
    }
  }, drupalSettings.toolbar, {
    strings: {
      horizontal: Drupal.t('Horizontal orientation'),
      vertical: Drupal.t('Vertical orientation')
    }
  });
  var ToolbarBehaviors = {
    onTabClick: function onTabClick() {
      console.log('vanilla: onTabClick()');
    },
    renderToolbarVisualView: function renderToolbarVisualView() {
      console.log('vanilla: render() in ToolbarVisualView');
    },
    renderMenuVisualView: function renderMenuVisualView() {
      console.log('vanilla: render() in MenuVisualView');
    },
    updateTabs: function updateTabs() {
      console.log('vanilla: updateTabs() in ToolbarVisualView');
    },
    onActiveTrayChange: function onActiveTrayChange() {
      console.log('vanilla: onActiveTrayChange in ToolbarVisualView');
    },
    renderBodyVisual: function renderBodyVisual() {
      console.log('vanilla: render() in BodyVisualView');
    },
    updateTrayOrientation: function updateTrayOrientation() {
      console.log('vanilla: updateTrayOrientation() in ToolbarVisualView');
    },
    updateBarAttributes: function updateBarAttributes() {
      console.log('vanilla: updateBarAttributes() in ToolbarVisualView');
    },
    updateToolbarHeight: function updateToolbarHeight() {
      console.log('vanilla: updateToolbarHeight() in ToolbarVisualView');
    },
    triggerDisplace: function triggerDisplace() {
      console.log('vanilla: triggerDisplace() in ToolbarVisualView');
    },
    adjustPlacement: function adjustPlacement() {
      console.log('vanilla: adjustPlacement() in ToolbarVisualView');
    },
    onOrientationToggleClick: function onOrientationToggleClick() {
      console.log('vanilla: onOrientationToggleClick()');
    },
    onOrientationChange: function onOrientationChange() {
      console.log('vanilla: onOrientationChange() in ToolbarAuralView');
    },
    loadSubtrees: function loadSubtrees() {
      console.log('vanilla: loadSubtrees()');
    },
    isBlah: false
  };
  Drupal.behaviors.toolbar = {
    attach: function attach(context) {
      if (!window.matchMedia('only screen').matches) {
        return;
      }

      once('toolbar', '#toolbar-administration', context).forEach(function (toolbar) {
        var toolbarTab = document.querySelector('.toolbar-bar .toolbar-tab .trigger');
        toolbarTab.addEventListener('click', function () {
          return ToolbarBehaviors.onTabClick();
        });
        toolbarTab.addEventListener('click', function () {
          return ToolbarBehaviors.renderToolbarVisualView();
        });
        toolbarTab.addEventListener('click', function () {
          return ToolbarBehaviors.updateTabs();
        });
        toolbarTab.addEventListener('click', function () {
          return ToolbarBehaviors.onActiveTrayChange();
        });
        toolbarTab.addEventListener('click', function () {
          return ToolbarBehaviors.renderBodyVisual();
        });
        toolbarTab.addEventListener('click', function () {
          return ToolbarBehaviors.updateTrayOrientation();
        });
        toolbarTab.addEventListener('click', function () {
          return ToolbarBehaviors.updateBarAttributes();
        });
        toolbarTab.addEventListener('click', function () {
          return ToolbarBehaviors.updateToolbarHeight();
        });
        toolbarTab.addEventListener('click', function () {
          return ToolbarBehaviors.triggerDisplace();
        });
        toolbarTab.addEventListener('click', function () {
          return ToolbarBehaviors.adjustPlacement();
        });
        toolbarTab.addEventListener('click', function () {
          return ToolbarBehaviors.loadSubtrees();
        });
        var model = new Drupal.toolbar.ToolbarModel({
          locked: JSON.parse(localStorage.getItem('Drupal.toolbar.trayVerticalLocked')),
          activeTab: document.getElementById(JSON.parse(localStorage.getItem('Drupal.toolbar.activeTabID'))),
          height: $('#toolbar-administration').outerHeight()
        });
        Drupal.toolbar.models.toolbarModel = model;
        Object.keys(options.breakpoints).forEach(function (label) {
          var mq = options.breakpoints[label];
          var mql = window.matchMedia(mq);
          Drupal.toolbar.mql[label] = mql;
          mql.addListener(Drupal.toolbar.mediaQueryChangeHandler.bind(null, model, label));
          Drupal.toolbar.mediaQueryChangeHandler.call(null, model, label, mql);
        });
        Drupal.toolbar.views.toolbarVisualView = new Drupal.toolbar.ToolbarVisualView({
          el: toolbar,
          model: model,
          strings: options.strings
        });
        Drupal.toolbar.views.toolbarAuralView = new Drupal.toolbar.ToolbarAuralView({
          el: toolbar,
          model: model,
          strings: options.strings
        });
        Drupal.toolbar.views.bodyVisualView = new Drupal.toolbar.BodyVisualView({
          el: toolbar,
          model: model
        });
        model.trigger('change:isFixed', model, model.get('isFixed'));
        model.trigger('change:activeTray', model, model.get('activeTray'));
        var toolbarOrientationButton = document.querySelector('.toolbar-toggle-orientation button');
        toolbarOrientationButton.addEventListener('click', function () {
          return ToolbarBehaviors.onOrientationToggleClick();
        });
        toolbarOrientationButton.addEventListener('click', function () {
          return ToolbarBehaviors.renderToolbarVisualView();
        });
        toolbarOrientationButton.addEventListener('click', function () {
          return ToolbarBehaviors.updateTabs();
        });
        toolbarOrientationButton.addEventListener('click', function () {
          return ToolbarBehaviors.updateTrayOrientation();
        });
        toolbarOrientationButton.addEventListener('click', function () {
          return ToolbarBehaviors.updateBarAttributes();
        });
        toolbarOrientationButton.addEventListener('click', function () {
          return ToolbarBehaviors.updateToolbarHeight();
        });
        toolbarOrientationButton.addEventListener('click', function () {
          return ToolbarBehaviors.triggerDisplace();
        });
        toolbarOrientationButton.addEventListener('click', function () {
          return ToolbarBehaviors.onOrientationChange();
        });
        toolbarOrientationButton.addEventListener('click', function () {
          return ToolbarBehaviors.adjustPlacement();
        });
        var menuModel = new Drupal.toolbar.MenuModel();
        Drupal.toolbar.models.menuModel = menuModel;
        Drupal.toolbar.views.menuVisualView = new Drupal.toolbar.MenuVisualView({
          el: $(toolbar).find('.toolbar-menu-administration').get(0),
          model: menuModel,
          strings: options.strings
        });
        Drupal.toolbar.setSubtrees.done(function (subtrees) {
          menuModel.set('subtrees', subtrees);
          var theme = drupalSettings.ajaxPageState.theme;
          localStorage.setItem("Drupal.toolbar.subtrees.".concat(theme), JSON.stringify(subtrees));
          model.set('areSubtreesLoaded', true);
        });
        Drupal.toolbar.views.toolbarVisualView.loadSubtrees();
        $(document).on('drupalViewportOffsetChange.toolbar', function (event, offsets) {
          model.set('offsets', offsets);
        });
        model.on('change:orientation', function (model, orientation) {
          $(document).trigger('drupalToolbarOrientationChange', orientation);
        }).on('change:activeTab', function (model, tab) {
          $(document).trigger('drupalToolbarTabChange', tab);
        }).on('change:activeTray', function (model, tray) {
          $(document).trigger('drupalToolbarTrayChange', tray);
        });

        if (Drupal.toolbar.models.toolbarModel.get('orientation') === 'horizontal' && Drupal.toolbar.models.toolbarModel.get('activeTab') === null) {
          Drupal.toolbar.models.toolbarModel.set({
            activeTab: $('.toolbar-bar .toolbar-tab:not(.home-toolbar-tab) a').get(0)
          });
        }

        $(window).on({
          'dialog:aftercreate': function dialogAftercreate(event, dialog, $element, settings) {
            var $toolbar = $('#toolbar-bar');
            $toolbar.css('margin-top', '0');

            if (settings.drupalOffCanvasPosition === 'top') {
              var height = Drupal.offCanvas.getContainer($element).outerHeight();
              $toolbar.css('margin-top', "".concat(height, "px"));
              $element.on('dialogContentResize.off-canvas', function () {
                var newHeight = Drupal.offCanvas.getContainer($element).outerHeight();
                $toolbar.css('margin-top', "".concat(newHeight, "px"));
              });
            }
          },
          'dialog:beforeclose': function dialogBeforeclose() {
            $('#toolbar-bar').css('margin-top', '0');
          }
        });
      });
    }
  };
  Drupal.toolbar = {
    views: {},
    models: {},
    mql: {},
    setSubtrees: new $.Deferred(),
    mediaQueryChangeHandler: function mediaQueryChangeHandler(model, label, mql) {
      console.log('mediaQueryChangeHandler in toolbar.es6');

      switch (label) {
        case 'toolbar.narrow':
          model.set({
            isOriented: mql.matches,
            isTrayToggleVisible: false
          });

          if (!mql.matches || !model.get('orientation')) {
            model.set({
              orientation: 'vertical'
            }, {
              validate: true
            });
          }

          break;

        case 'toolbar.standard':
          model.set({
            isFixed: mql.matches
          });
          break;

        case 'toolbar.wide':
          model.set({
            orientation: mql.matches && !model.get('locked') ? 'horizontal' : 'vertical'
          }, {
            validate: true
          });
          model.set({
            isTrayToggleVisible: mql.matches
          });
          break;

        default:
          break;
      }
    }
  };

  Drupal.theme.toolbarOrientationToggle = function () {
    return '<div class="toolbar-toggle-orientation"><div class="toolbar-lining">' + '<button class="toolbar-icon" type="button"></button>' + '</div></div>';
  };

  Drupal.AjaxCommands.prototype.setToolbarSubtrees = function (ajax, response, status) {
    Drupal.toolbar.setSubtrees.resolve(response.subtrees);
  };
})(jQuery, Drupal, drupalSettings);