/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, drupalSettings) {
  var options = $.extend({
    breakpoints: {
      'toolbar.narrow': '',
      'toolbar.standard': '',
      'toolbar.wide': ''
    }
  }, drupalSettings.toolbar, {
    strings: {
      horizontal: Drupal.t('Horizontal orientation'),
      vertical: Drupal.t('Vertical orientation')
    }
  });
  var toolbarBehaviors = {
    _subtrees: {},

    get subtrees() {
      return this._subtrees;
    },

    set subtrees(value) {
      this._subtrees = value;
      this.renderMenu();
      this.renderBody();
    },

    _activeTab: JSON.parse(localStorage.getItem('Drupal.toolbar.activeTabID')) ? "#".concat(JSON.parse(localStorage.getItem('Drupal.toolbar.activeTabID'))) : null,

    get activeTab() {
      return this._activeTab;
    },

    set activeTab(value) {
      if (value !== this.activeTab) {
        if (this.activeTab) {
          var tabElement = document.querySelector(this.activeTab);
          tabElement.classList.remove('is-active');
          tabElement.setAttribute('aria-pressed', 'false');
        }

        if (this.activeTray) {
          var trayElement = document.querySelector(this.activeTray);
          trayElement.classList.remove('is-active');
        }
      } else {
        var _tabElement = document.querySelector(this.activeTab);

        _tabElement.classList.remove('is-active');

        _tabElement.setAttribute('aria-pressed', 'false');

        if (this.activeTray) {
          var name = document.querySelector(this.activeTab).getAttribute('data-toolbar-tray');
          var tray = "[data-toolbar-tray=\"".concat(name, "\"].toolbar-tray");

          var _trayElement = document.querySelector(tray);

          _trayElement.classList.remove('is-active');
        }
      }

      this._activeTab = value;
      this.renderToolbar();
      this.updateToolbarHeight();
      $(document).trigger('drupalToolbarTabChange', this.activeTab);
    },

    _activeTray: null,

    get activeTray() {
      return this._activeTray;
    },

    set activeTray(value) {
      if (value !== this.activeTray) {
        this._activeTray = value;
        this.renderBody();
        this.onActiveTrayChange(value);
        $(document).trigger('drupalToolbarTrayChange', this.activeTray);
      }
    },

    _isOriented: false,

    get isOriented() {
      return this._isOriented;
    },

    set isOriented(value) {
      if (value !== this.isOriented) {
        this._isOriented = value;
        this.renderToolbar();
        this.updateToolbarHeight();
      }
    },

    _isFixed: false,

    get isFixed() {
      return this._isFixed;
    },

    set isFixed(value) {
      this._isFixed = value;
      this.isToolbarFixed();
    },

    _areSubtreesLoaded: false,

    get areSubtreesLoaded() {
      return this._areSubtreesLoaded;
    },

    set areSubtreesLoaded(value) {
      this._areSubtreesLoaded = value;
    },

    _isViewportOverflowConstrained: false,

    get isViewportOverflowConstrained() {
      return this._isViewportOverflowConstrained;
    },

    set isViewportOverflowConstrained(value) {
      this._isViewportOverflowConstrained = value;
      this.isToolbarFixed();
    },

    _orientation: 'horizontal',

    get orientation() {
      return this._orientation;
    },

    set orientation(value) {
      if (value !== this.orientation && value !== null) {
        this._orientation = value;
        this.renderToolbar();
        this.updateToolbarHeight();
        this.onOrientationChange();
        $(document).trigger('drupalToolbarOrientationChange', this.orientation);
      }
    },

    _locked: false,

    get locked() {
      return this._locked;
    },

    set locked(value) {
      if (value !== this.locked && value !== null) {
        this._locked = value;
      }
    },

    _isTrayToggleVisible: true,

    get isTrayToggleVisible() {
      return this._isTrayToggleVisible;
    },

    set isTrayToggleVisible(value) {
      if (value !== this.isTrayToggleVisible && value !== null) {
        this._isTrayToggleVisible = value;
        this.renderToolbar();
      }
    },

    _height: null,

    get height() {
      return this._height;
    },

    set height(value) {
      this._height = value;
    },

    _offsets: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0
    },

    get offsets() {
      return this._offsets;
    },

    set offsets(value) {
      this._offsets = value;
      this.adjustPlacement();
    },

    onTabClick: function onTabClick(e) {
      e.preventDefault();
      e.stopPropagation();

      if (e.target.hasAttribute('data-toolbar-tray')) {
        var activeTab = toolbarBehaviors.activeTab;
        var clickedTab = e.currentTarget;
        var clicked = clickedTab.getAttribute('data-toolbar-tray');

        if (!activeTab || "#".concat(clickedTab.id) !== activeTab) {
          this.activeTab = "#".concat(clickedTab.id);
        } else {
          this.activeTab = null;
        }
      }
    },
    renderToolbar: function renderToolbar() {
      this.updateTabs();
      this.updateTrayOrientation();
      this.updateBarAttributes();
      document.querySelector('body').classList.remove('toolbar-loading');

      if (this.orientation === 'vertical' || this.activeTab) {
        this.loadSubtrees();
      }
    },
    renderMenu: function renderMenu() {
      var subtrees = toolbarBehaviors.subtrees;
      var menu = document.querySelector('.toolbar-menu-administration');
      Object.keys(subtrees || {}).forEach(function (id) {
        $(once('toolbar-subtrees', menu.querySelector("#toolbar-link-".concat(id)))).after(subtrees[id]);
      });

      if ('drupalToolbarMenu' in $.fn) {
        $(menu).children('.toolbar-menu').drupalToolbarMenu();
      }
    },
    updateTabs: function updateTabs() {
      var tab = this.activeTab;

      if (tab) {
        if (tab.length > 0) {
          var tabElement = document.querySelector(tab);
          tabElement.classList.add('is-active');
          tabElement.setAttribute('aria-pressed', 'true');
          tabElement.ariaPressed = true;
          var id = tabElement.id;

          if (id) {
            localStorage.setItem('Drupal.toolbar.activeTabID', JSON.stringify(id));
          }

          var name = document.querySelector(this.activeTab).getAttribute('data-toolbar-tray');
          var tray = "[data-toolbar-tray=\"".concat(name, "\"].toolbar-tray");
          var trayElement = document.querySelector(tray);

          if (trayElement) {
            trayElement.classList.add('is-active');
            this.activeTray = tray;
          } else {
            this.activeTray = null;
          }
        } else {
          this.activeTray = null;
          localStorage.removeItem('Drupal.toolbar.activeTabID');
        }
      }
    },
    onActiveTrayChange: function onActiveTrayChange() {
      var relevantTray = this.activeTray;

      if (!relevantTray) {
        return;
      }

      var action = this.activeTray === null ? Drupal.t('closed') : Drupal.t('opened');
      var trayNameElement = document.querySelector(relevantTray);
      var trayName = trayNameElement.querySelector('.toolbar-tray-name');
      var text;

      if (trayNameElement !== null) {
        text = Drupal.t('Tray "@tray" @action.', {
          '@tray': trayName.textContent,
          '@action': action
        });
      } else {
        text = Drupal.t('Tray @action.', {
          '@action': action
        });
      }

      Drupal.announce(text);
    },
    renderBody: function renderBody() {
      $('body').toggleClass('toolbar-tray-open', !!this.activeTray);
    },
    updateTrayOrientation: function updateTrayOrientation() {
      var _this = this;

      var orientation = toolbarBehaviors.orientation;
      var antiOrientation = orientation === 'vertical' ? 'horizontal' : 'vertical';
      $('body').toggleClass('toolbar-vertical', orientation === 'vertical').toggleClass('toolbar-horizontal', orientation === 'horizontal');
      var removeClass = antiOrientation === 'horizontal' ? 'toolbar-tray-horizontal' : 'toolbar-tray-vertical';
      var toolbar = document.querySelector('#toolbar-administration');
      toolbar.querySelectorAll('.toolbar-tray').forEach(function (tray) {
        tray.classList.remove(removeClass);
        tray.classList.add("toolbar-tray-".concat(orientation));
      });
      var trays = toolbar.querySelectorAll('.toolbar-tray');
      var iconClass = "toolbar-icon-toggle-".concat(orientation);
      var iconAntiClass = "toolbar-icon-toggle-".concat(antiOrientation);
      var $orientationToggle = $('body').find('.toolbar-toggle-orientation');
      toolbar.querySelectorAll('.toolbar-toggle-orientation').forEach(function (tray) {
        if (_this.isTrayToggleVisible) {
          tray.hidden = false;
        } else {
          tray.hidden = true;
        }
      });
      $orientationToggle.find('button').val(antiOrientation).attr('title', options.strings[antiOrientation]).text(options.strings[antiOrientation]).removeClass(iconClass).addClass(iconAntiClass);
      var dir = document.documentElement.dir;
      var edge = dir === 'rtl' ? 'right' : 'left';
      $(trays).removeAttr('data-offset-left data-offset-right data-offset-top');
      $(trays).filter('.toolbar-tray-vertical.is-active').attr("data-offset-".concat(edge), '');
      $(trays).filter('.toolbar-tray-horizontal.is-active').attr('data-offset-top', '');
    },
    updateBarAttributes: function updateBarAttributes() {
      var isOriented = toolbarBehaviors.isOriented;
      var toolbar = document.querySelector('#toolbar-administration');

      if (isOriented) {
        toolbar.querySelector('#toolbar-bar').setAttribute('data-offset-top', '');
      } else {
        toolbar.querySelector('#toolbar-bar').removeAttribute('data-offset-top');
      }

      if (isOriented) {
        toolbar.classList.add('toolbar-oriented');
      } else {
        toolbar.classList.remove('toolbar-oriented');
      }
    },
    updateToolbarHeight: function updateToolbarHeight() {
      var toolbarTabOuterHeight = $('#toolbar-bar').find('.toolbar-tab').outerHeight() || 0;
      var toolbarTrayHorizontalOuterHeight = $('.is-active.toolbar-tray-horizontal').outerHeight() || 0;
      this.height = toolbarTabOuterHeight + toolbarTrayHorizontalOuterHeight;
      $('body').css({
        'padding-top': this.height
      });
      $('html').css({
        'scroll-padding-top': this.height
      });
      this.triggerDisplace();
    },
    triggerDisplace: function triggerDisplace() {
      _.defer(function () {
        Drupal.displace(true);
      });
    },
    adjustPlacement: function adjustPlacement() {
      var toolbar = document.querySelector('#toolbar-administration');

      if (!this.isOriented) {
        toolbar.querySelectorAll('.toolbar-tray').forEach(function (tray) {
          tray.classList.remove('toolbar-tray-horizontal');
          tray.classList.add('toolbar-tray-vertical');
        });
      }
    },
    onOrientationToggleClick: function onOrientationToggleClick(e) {
      e.preventDefault();
      e.stopPropagation();
      var orientation = this.orientation;
      var antiOrientation = orientation === 'vertical' ? 'horizontal' : 'vertical';
      var locked = antiOrientation === 'vertical';

      if (locked) {
        localStorage.setItem('Drupal.toolbar.trayVerticalLocked', 'true');
      } else {
        localStorage.removeItem('Drupal.toolbar.trayVerticalLocked');
      }

      this.orientation = antiOrientation;
      this.locked = locked;
    },
    onOrientationChange: function onOrientationChange() {
      Drupal.announce(Drupal.t('Tray orientation changed to @orientation.', {
        '@orientation': this.orientation
      }));
    },
    isToolbarFixed: function isToolbarFixed() {
      var isViewportOverflowConstrained = this.isViewportOverflowConstrained;
      $('body').toggleClass('toolbar-fixed', isViewportOverflowConstrained || this.isFixed);
    },
    loadSubtrees: function loadSubtrees() {
      var $activeTab = $(this.activeTab);
      var orientation = toolbarBehaviors.orientation;

      if (!this.areSubtreesLoaded && typeof $activeTab.data('drupal-subtrees') !== 'undefined' && orientation === 'vertical') {
        var subtreesHash = drupalSettings.toolbar.subtreesHash;
        var theme = drupalSettings.ajaxPageState.theme;
        var endpoint = Drupal.url("toolbar/subtrees/".concat(subtreesHash));
        var cachedSubtreesHash = localStorage.getItem("Drupal.toolbar.subtreesHash.".concat(theme));
        var cachedSubtrees = JSON.parse(localStorage.getItem("Drupal.toolbar.subtrees.".concat(theme)));
        var isVertical = this.orientation === 'vertical';

        if (isVertical && subtreesHash === cachedSubtreesHash && cachedSubtrees) {
          Drupal.toolbar.setSubtrees.resolve(cachedSubtrees);
        } else if (isVertical) {
          localStorage.removeItem("Drupal.toolbar.subtreesHash.".concat(theme));
          localStorage.removeItem("Drupal.toolbar.subtrees.".concat(theme));
          Drupal.ajax({
            url: endpoint
          }).execute();
          localStorage.setItem("Drupal.toolbar.subtreesHash.".concat(theme), subtreesHash);
        }
      }
    },
    touchEndToClick: function touchEndToClick(e) {
      e.preventDefault();
      e.target.click();
    }
  };
  Drupal.behaviors.toolbar = {
    attach: function attach(context) {
      if (!window.matchMedia('only screen').matches) {
        return;
      }

      once('toolbar', '#toolbar-administration', context).forEach(function (toolbar) {
        var model = new Drupal.toolbar.ToolbarModel({
          locked: JSON.parse(localStorage.getItem('Drupal.toolbar.trayVerticalLocked')),
          activeTab: document.getElementById(JSON.parse(localStorage.getItem('Drupal.toolbar.activeTabID'))),
          height: $('#toolbar-administration').outerHeight()
        });
        var bar = document.querySelector('#toolbar-administration');
        var trays = bar.querySelectorAll('.toolbar-tray .toolbar-lining');
        toolbar.querySelectorAll('.toolbar-tray .toolbar-lining').forEach(function (toolbarLining) {
          $(toolbarLining).append(Drupal.theme('toolbarOrientationToggle'));
        });

        if (toolbarBehaviors.orientation === 'horizontal' && toolbarBehaviors.activeTab === null) {
          toolbarBehaviors.activeTab = '.toolbar-bar .toolbar-tab:not(.home-toolbar-tab) a';
        }

        document.querySelectorAll('.toolbar-bar .toolbar-tab .trigger').forEach(function (toolbarTab) {
          toolbarTab.addEventListener('click', function (e) {
            return toolbarBehaviors.onTabClick(e);
          });
        });
        document.querySelectorAll('.toolbar-toggle-orientation button').forEach(function (button) {
          button.addEventListener('click', function (e) {
            return toolbarBehaviors.onOrientationToggleClick(e);
          });
        });
        document.querySelectorAll('.toolbar-bar .toolbar-tab .trigger').forEach(function (toolbarTab) {
          toolbarTab.addEventListener('touchend', function (e) {
            return toolbarBehaviors.touchEndToClick(e);
          });
        });
        document.querySelectorAll('.toolbar-toggle-orientation button').forEach(function (toolbarTab) {
          toolbarTab.addEventListener('touchend', function (e) {
            return toolbarBehaviors.touchEndToClick(e);
          });
        });
        toolbarBehaviors.locked = JSON.parse(localStorage.getItem('Drupal.toolbar.trayVerticalLocked'));
        toolbarBehaviors.height = $('#toolbar-administration').outerHeight();
        Drupal.toolbar.models.toolbarModel = model;
        Object.keys(options.breakpoints).forEach(function (label) {
          var mq = options.breakpoints[label];
          var mql = window.matchMedia(mq);
          Drupal.toolbar.mql[label] = mql;
          mql.addListener(Drupal.toolbar.mediaQueryChangeHandler.bind(null, model, label));
          Drupal.toolbar.mediaQueryChangeHandler.call(null, model, label, mql);
        });
        Drupal.toolbar.views.toolbarVisualView = new Drupal.toolbar.ToolbarVisualView({
          el: toolbar,
          model: model,
          strings: options.strings
        });
        Drupal.toolbar.views.toolbarAuralView = new Drupal.toolbar.ToolbarAuralView({
          el: toolbar,
          model: model,
          strings: options.strings
        });
        Drupal.toolbar.views.bodyVisualView = new Drupal.toolbar.BodyVisualView({
          el: toolbar,
          model: model
        });
        toolbar;
        model.trigger('change:isFixed', model, model.get('isFixed'));
        model.trigger('change:activeTray', model, model.get('activeTray'));
        var menuModel = new Drupal.toolbar.MenuModel();
        Drupal.toolbar.models.menuModel = menuModel;
        Drupal.toolbar.views.menuVisualView = new Drupal.toolbar.MenuVisualView({
          el: $(toolbar).find('.toolbar-menu-administration').get(0),
          model: menuModel,
          strings: options.strings
        });
        Drupal.toolbar.setSubtrees.done(function (subtrees) {
          menuModel.set('subtrees', subtrees);
          var theme = drupalSettings.ajaxPageState.theme;
          localStorage.setItem("Drupal.toolbar.subtrees.".concat(theme), JSON.stringify(subtrees));
          model.set('areSubtreesLoaded', true);
        });
        Drupal.toolbar.views.toolbarVisualView.loadSubtrees();
        $(document).on('drupalViewportOffsetChange.toolbar', function (event, offsets) {
          model.set('offsets', offsets);
        });
        model.on('change:orientation', function (model, orientation) {
          $(document).trigger('drupalToolbarOrientationChange', orientation);
        }).on('change:activeTab', function (model, tab) {
          $(document).trigger('drupalToolbarTabChange', tab);
        }).on('change:activeTray', function (model, tray) {
          $(document).trigger('drupalToolbarTrayChange', tray);
        });

        if (Drupal.toolbar.models.toolbarModel.get('orientation') === 'horizontal' && Drupal.toolbar.models.toolbarModel.get('activeTab') === null) {
          Drupal.toolbar.models.toolbarModel.set({
            activeTab: $('.toolbar-bar .toolbar-tab:not(.home-toolbar-tab) a').get(0)
          });
        }

        $(window).on({
          'dialog:aftercreate': function dialogAftercreate(event, dialog, $element, settings) {
            var $toolbar = $('#toolbar-bar');
            $toolbar.css('margin-top', '0');

            if (settings.drupalOffCanvasPosition === 'top') {
              var height = Drupal.offCanvas.getContainer($element).outerHeight();
              $toolbar.css('margin-top', "".concat(height, "px"));
              $element.on('dialogContentResize.off-canvas', function () {
                var newHeight = Drupal.offCanvas.getContainer($element).outerHeight();
                $toolbar.css('margin-top', "".concat(newHeight, "px"));
              });
            }
          },
          'dialog:beforeclose': function dialogBeforeclose() {
            $('#toolbar-bar').css('margin-top', '0');
          }
        });
      });
    }
  };
  Drupal.toolbar = {
    views: {},
    models: {},
    mql: {},
    setSubtrees: new $.Deferred(),
    mediaQueryChangeHandler: function mediaQueryChangeHandler(model, label, mql) {
      switch (label) {
        case 'toolbar.narrow':
          model.set({
            isOriented: mql.matches,
            isTrayToggleVisible: false
          });

          if (!mql.matches || !model.get('orientation')) {
            model.set({
              orientation: 'vertical'
            }, {
              validate: true
            });
          }

          break;

        case 'toolbar.standard':
          model.set({
            isFixed: mql.matches
          });
          break;

        case 'toolbar.wide':
          model.set({
            orientation: mql.matches && !model.get('locked') ? 'horizontal' : 'vertical'
          }, {
            validate: true
          });
          model.set({
            isTrayToggleVisible: mql.matches
          });
          break;

        default:
          break;
      }
    }
  };

  Drupal.theme.toolbarOrientationToggle = function () {
    return '<div class="toolbar-toggle-orientation"><div class="toolbar-lining">' + '<button class="toolbar-icon" type="button"></button>' + '</div></div>';
  };

  Drupal.AjaxCommands.prototype.setToolbarSubtrees = function (ajax, response, status) {
    Drupal.toolbar.setSubtrees.resolve(response.subtrees);
  };
})(jQuery, Drupal, drupalSettings);