/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, drupalSettings) {
  var options = $.extend({
    breakpoints: {
      'toolbar.narrow': '',
      'toolbar.standard': '',
      'toolbar.wide': ''
    }
  }, drupalSettings.toolbar, {
    strings: {
      horizontal: Drupal.t('Horizontal orientation'),
      vertical: Drupal.t('Vertical orientation')
    }
  });
  Drupal.behaviors.toolbar = {
    attach: function attach(context) {
      if (!window.matchMedia('only screen').matches) {
        return;
      }

      once('toolbar', '#toolbar-administration', context).forEach(function (toolbar) {
        var model = new Drupal.toolbar._ToolbarModel({
          locked: JSON.parse(localStorage.getItem('Drupal.toolbar.trayVerticalLocked')),
          activeTab: document.getElementById(JSON.parse(localStorage.getItem('Drupal.toolbar.activeTabID'))),
          height: $('#toolbar-administration').outerHeight()
        });
        Drupal.toolbar.models.toolbarModel = new Proxy(model, {
          get: function get(target, prop, receiver) {
            Drupal.deprecationError({
              message: 'Drupal.toolbar.models.toolbarModel will be marked as internal in drupal:10.0.0.'
            });
            return Reflect.get.apply(Reflect, arguments);
          }
        });
        Object.keys(options.breakpoints).forEach(function (label) {
          var mq = options.breakpoints[label];
          var mql = window.matchMedia(mq);
          Drupal.toolbar.mql[label] = mql;
          mql.addListener(Drupal.toolbar.mediaQueryChangeHandler.bind(null, model, label));
          Drupal.toolbar.mediaQueryChangeHandler.call(null, model, label, mql);
        });
        var toolbarVisualView = new Drupal.toolbar.ToolbarVisualView({
          el: toolbar,
          model: model,
          strings: options.strings
        });
        Drupal.toolbar.views.toolbarVisualView = new Proxy(toolbarVisualView, {
          get: function get(target, prop, receiver) {
            Drupal.deprecationError({
              message: 'Drupal.toolbar.views.toolbarVisualView will be marked as internal in drupal:10.0.0.'
            });
            return Reflect.get.apply(Reflect, arguments);
          }
        });
        var toolbarAuralView = new Drupal.toolbar.ToolbarAuralView({
          el: toolbar,
          model: model,
          strings: options.strings
        });
        Drupal.toolbar.views.toolbarAuralView = new Proxy(toolbarAuralView, {
          get: function get(target, prop, receiver) {
            Drupal.deprecationError({
              message: 'Drupal.toolbar.views.toolbarAuralView will be marked as internal in drupal:10.0.0.'
            });
            return Reflect.get.apply(Reflect, arguments);
          }
        });
        var bodyVisualView = new Drupal.toolbar.BodyVisualView({
          el: toolbar,
          model: model
        });
        Drupal.toolbar.views.bodyVisualView = new Proxy(bodyVisualView, {
          get: function get(target, prop, receiver) {
            Drupal.deprecationError({
              message: 'Drupal.toolbar.views.bodyVisualView will be marked as internal in drupal:10.0.0.'
            });
            return Reflect.get.apply(Reflect, arguments);
          }
        });
        toolbarVisualView.render();
        model.triggerEvent("model-".concat(model.modelId, "-change-isFixed"));
        model.triggerEvent("model-".concat(model.modelId, "-change-activeTray"));
        var menuModel = new Drupal.toolbar._MenuModel();
        Drupal.toolbar.models.menuModel = new Proxy(menuModel, {
          get: function get(target, prop, receiver) {
            Drupal.deprecationError({
              message: 'Drupal.toolbar.models.menuModel will be marked as internal in drupal:10.0.0.'
            });
            return Reflect.get.apply(Reflect, arguments);
          }
        });
        var menuVisualView = new Drupal.toolbar.MenuVisualView({
          el: $(toolbar).find('.toolbar-menu-administration').get(0),
          model: menuModel,
          strings: options.strings
        });
        Drupal.toolbar.views.menuVisualView = new Proxy(menuVisualView, {
          get: function get(target, prop, receiver) {
            Drupal.deprecationError({
              message: 'Drupal.toolbar.views.menuVisualView will be marked as internal in drupal:10.0.0.'
            });
            return Reflect.get.apply(Reflect, arguments);
          }
        });
        Drupal.toolbar.setSubtrees.done(function (subtrees) {
          menuModel.set('subtrees', subtrees);
          var theme = drupalSettings.ajaxPageState.theme;
          localStorage.setItem("Drupal.toolbar.subtrees.".concat(theme), JSON.stringify(subtrees));
          model.set('areSubtreesLoaded', true);
        });
        toolbarVisualView.loadSubtrees();
        $(document).on('drupalViewportOffsetChange.toolbar', function (event, offsets) {
          model.set('offsets', offsets);
        });

        if (model.get('orientation') === 'horizontal' && model.get('activeTab') === null) {
          model.set({
            activeTab: $('.toolbar-bar .toolbar-tab:not(.home-toolbar-tab) a').get(0)
          });
        }

        document.addEventListener("model-".concat(model.modelId, "-change-orientation"), function () {
          $(document).trigger('drupalToolbarOrientationChange', model.get('orientation'));
        });
        document.addEventListener("model-".concat(model.modelId, "-change-activeTab"), function () {
          $(document).trigger('drupalToolbarTabChange', model.get('activeTab'));
        });
        document.addEventListener("model-".concat(model.modelId, "-change-activeTray"), function () {
          $(document).trigger('drupalToolbarTrayChange', model.get('activeTray'));
        });
        $(window).on({
          'dialog:aftercreate': function dialogAftercreate(event, dialog, $element, settings) {
            var $toolbar = $('#toolbar-bar');
            $toolbar.css('margin-top', '0');

            if (settings.drupalOffCanvasPosition === 'top') {
              var height = Drupal.offCanvas.getContainer($element).outerHeight();
              $toolbar.css('margin-top', "".concat(height, "px"));
              $element.on('dialogContentResize.off-canvas', function () {
                var newHeight = Drupal.offCanvas.getContainer($element).outerHeight();
                $toolbar.css('margin-top', "".concat(newHeight, "px"));
              });
            }
          },
          'dialog:beforeclose': function dialogBeforeclose() {
            $('#toolbar-bar').css('margin-top', '0');
          }
        });
      });
    }
  };
  Drupal.toolbar = {
    views: {},
    models: {},
    mql: {},
    setSubtrees: new $.Deferred(),
    mediaQueryChangeHandler: function mediaQueryChangeHandler(model, label, mql) {
      switch (label) {
        case 'toolbar.narrow':
          model.set({
            isOriented: mql.matches,
            isTrayToggleVisible: false
          });

          if (!mql.matches || !model.get('orientation')) {
            model.set({
              orientation: 'vertical'
            }, {
              validate: true
            });
          }

          break;

        case 'toolbar.standard':
          model.set({
            isFixed: mql.matches
          });
          break;

        case 'toolbar.wide':
          model.set({
            orientation: mql.matches && !model.get('locked') ? 'horizontal' : 'vertical'
          }, {
            validate: true
          });
          model.set({
            isTrayToggleVisible: mql.matches
          });
          break;

        default:
          break;
      }
    }
  };

  Drupal.theme.toolbarOrientationToggle = function () {
    return '<div class="toolbar-toggle-orientation"><div class="toolbar-lining">' + '<button class="toolbar-icon" type="button"></button>' + '</div></div>';
  };

  Drupal.AjaxCommands.prototype.setToolbarSubtrees = function (ajax, response, status) {
    Drupal.toolbar.setSubtrees.resolve(response.subtrees);
  };
})(jQuery, Drupal, drupalSettings);