/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

Drupal.toolbar = {
  models: {}
};
Drupal.toolbar.models.toolbarModel = {
  get: function get(property) {
    switch (property) {
      case 'activeTab':
        console.log("The get property for Toolbar is not supported beginning with Drupal 10. But ".concat(property, " can be accessed directly using Drupal.toolbar.models.toolbarModel.").concat(property, " instead."));
        return Drupal.toolbar.models.toolbarModel.activeTab();

      case 'orientation':
        console.log("The get property for Toolbar is not supported beginning with Drupal 10. But ".concat(property, " can be accessed directly using Drupal.toolbar.models.toolbarModel.").concat(property, " instead."));
        return Drupal.toolbar.models.toolbarModel.orientation();

      default:
        console.log("The get property for Toolbar is not supported beginning with Drupal 10. But ".concat(property, " can be accessed directly using Drupal.toolbar.models.toolbarModel.").concat(property, " instead."));
    }
  },
  set: function set(a) {
    if (arguments.length <= 1 ? 0 : arguments.length - 1) {
      if (a === 'activeTab') {
        console.log("The set property for Toolbar is not supported beginning with Drupal 10. But ".concat(a, " can be set directly using Drupal.toolbar.models.toolbarModel.").concat(a, " instead."));
        Drupal.toolbar.toolbarBehaviors.activeTab = arguments.length <= 1 ? undefined : arguments[1];
      }
    } else {
      var prop = Object.keys(a)[0];
      var value = a[prop];

      if (prop === 'activeTab') {
        console.log("The set property for Toolbar is not supported beginning with Drupal 10. But ".concat(prop, " can be set directly using Drupal.toolbar.models.toolbarModel.").concat(prop, " instead."));
        Drupal.toolbar.toolbarBehaviors.activeTab = value;
      }
    }
  }
};
Drupal.toolbar.MenuModel = {
  subtrees: {}
};
Drupal.toolbar.ToolbarVisualView = {
  prototype: Drupal.toolbar.toolbarBehaviors
};