<?php

/**
 * @file
 * Primary module hooks for navigation module.
 */

use Drupal\Component\Plugin\PluginBase;
use Drupal\Component\Utility\Html;
use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\navigation\NavigationBlockListBuilder;
use Drupal\navigation\NavigationContentLinks;
use Drupal\navigation\NavigationRenderer;
use Drupal\system\MenuInterface;

/**
 * Implements hook_help().
 */
function navigation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.navigation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Navigation module provides mockup of a left-aligned, collapsible, vertical sidebar navigation. For more information, see the <a href=":docs">online documentation for the Navigation module</a>.', [
        ':docs' => 'https://www.drupal.org/project/navigation',
      ]) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_page_top().
 */
function navigation_page_top(array &$page_top) {
  $navigation_renderer = \Drupal::service('navigation.renderer');
  assert($navigation_renderer instanceof NavigationRenderer);
  $navigation_renderer->removeToolbar($page_top);
  $navigation_renderer->buildNavigation($page_top);
  $navigation_renderer->buildTopBar($page_top);
}

/**
 * Implements hook_module_implements_alter().
 */
function navigation_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'page_top') {
    $group = $implementations['navigation'];
    unset($implementations['navigation']);
    $implementations['navigation'] = $group;
  }
}

/**
 * Implements hook_theme().
 */
function navigation_theme($existing, $type, $theme, $path) {
  $items['top_bar'] = [
    'variables' => [
      'local_tasks' => [],
    ],
  ];

  $items['top_bar_local_tasks'] = [
    'variables' => [
      'local_tasks' => [],
    ],
  ];

  $items['top_bar_local_task'] = [
    'variables' => [
      'link' => [],
    ],
  ];

  $items['navigation'] = [
    'variables' => [
      'hide_logo' => FALSE,
      'logo_path' => FALSE,
      'logo_width' => 40,
      'logo_height' => 40,
      'menu_content' => [],
      'menu_footer' => [],
    ],
  ];

  $items['navigation_menu'] = [
    'base hook' => 'menu',
    'variables' => [
      'menu_name' => NULL,
      'items' => [],
      'attributes' => [],
    ],
  ];

  $items['menu_region__footer'] = [
    'variables' => [
      'help' => NULL,
      'items' => [],
      'title' => NULL,
      'menu_name' => NULL,
      'path' => \Drupal::service('extension.list.module')->getPath('navigation'),
    ],
  ];

  return $items;
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function navigation_menu_links_discovered_alter(&$links) {
  $navigation_links = \Drupal::classResolver(NavigationContentLinks::class);
  assert($navigation_links instanceof NavigationContentLinks);
  $navigation_links->addMenuLinks($links);
  $navigation_links->removeAdminContentLink($links);
  $navigation_links->removeHelpLink($links);
}

/**
 * Implements hook_block_build_BASE_BLOCK_ID_alter().
 */
function navigation_block_build_local_tasks_block_alter(array &$build, BlockPluginInterface $block) {
  $navigation_renderer = \Drupal::service('navigation.renderer');
  assert($navigation_renderer instanceof NavigationRenderer);
  $navigation_renderer->removeLocalTasks($build, $block);
}

/**
 * Implements hook_ENTITY_TYPE_insert() for menu.
 */
function navigation_menu_insert(MenuInterface $menu) {
  // @todo This code should be moved to Drupal\system\Entity\Menu::save() once
  // Navigation lands in core, in a similar way BlockManager cache is
  // invalidated there.
  \Drupal::service('plugin.manager.navigation_block')
    ->clearCachedDefinitions();
}

/**
 * Implements hook_ENTITY_TYPE_update() for menu.
 */
function navigation_menu_update(MenuInterface $menu) {
  // @todo This code should be moved to Drupal\system\Entity\Menu::save() once
  // Navigation lands in core, in a similar way BlockManager cache is
  // invalidated there.
  \Drupal::service('plugin.manager.navigation_block')
    ->clearCachedDefinitions();
}

/**
 * Implements hook_ENTITY_TYPE_delete() for menu.
 */
function navigation_menu_delete(MenuInterface $menu) {
  // @todo This code should be moved to Drupal\system\Entity\Menu::delete() once
  // Navigation lands in core, in a similar way BlockManager cache is
  // invalidated there.
  \Drupal::service('plugin.manager.navigation_block')
    ->clearCachedDefinitions();
}

/**
 * Implements hook_preprocess_html().
 */
function navigation_preprocess_html(&$variables) {
  $module_path = \Drupal::request()->getBasePath() . '/' . \Drupal::service('extension.list.module')->getPath('navigation');
  $asset_url = $module_path . '/assets/fonts/inter-var.woff2';
  $variables['#attached']['html_head_link'][] = [
    [
      'rel' => 'preload',
      'href' => $asset_url,
      'as' => 'font',
      'crossorigin' => 'anonymous',
    ],
  ];
}

/**
 * Implements hook_block_alter().
 */
function navigation_block_alter(&$definitions): void {
  // Mark blocks that are supported by the navigation module as such.
  $navigation_safe = [
    'shortcuts',
    'system_menu_block',
    'navigation_user',
  ];
  $matching_ids = array_filter(array_keys($definitions), static function (string $plugin_id) use ($navigation_safe): bool {
    [$base_plugin_id] = explode(PluginBase::DERIVATIVE_SEPARATOR, $plugin_id);
    return in_array($base_plugin_id, $navigation_safe, TRUE);
  });
  foreach ($matching_ids as $plugin_id) {
    $definitions[$plugin_id]['supports_navigation'] = TRUE;
  }
  // Hide the navigation user block from the normal block UI.
  $definitions['navigation_user']['_block_ui_hidden'] = TRUE;
}

/**
 * Implements hook_entity_type_build().
 */
function navigation_entity_type_build(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  if (array_key_exists('block', $entity_types)) {
    $entity_types['block']->setHandlerClass('navigation_block_list', NavigationBlockListBuilder::class);
  }
}
