<?php

/**
 * @file
 * Contains main module functionality.
 */

declare(strict_types=1);

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_bundle_field_info().
 */
function views_entity_test_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'entity_test') {
    $definitions['test_text_access'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Test access'))
      ->setTranslatable(FALSE)
      ->setSetting('max_length', 64)
      ->setDisplayOptions('form', [
        'type' => 'string_textfield',
        'weight' => 10,
      ]);
    return $definitions;
  }
}
