/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(Drupal => {
  function findActiveStep(steps) {
    for (let i = 0; i < steps.length; i++) {
      if (steps[i].className === 'is-active') {
        return i + 1;
      }
    }

    if (steps[steps.length - 1].className === 'done') {
      return steps.length;
    }

    return 0;
  }

  function installStepsSetup() {
    const steps = document.querySelectorAll('.task-list li');

    if (steps.length) {
      const header = document.querySelector('header[role="banner"]');
      const stepIndicator = document.createElement('div');
      stepIndicator.className = 'step-indicator';
      const auralView = Drupal.t('Install Step @step of @total_steps', {
        '@step': findActiveStep(steps),
        '@total_steps': steps.length
      });
      stepIndicator.innerHTML = `
        <span class="visually-hidden">${auralView}</span>
        <span aria-hidden="true">${findActiveStep(steps)}/${steps.length}</span>
      `;
      header.appendChild(stepIndicator);
    }
  }

  if (document.addEventListener) {
    document.addEventListener('DOMContentLoaded', installStepsSetup);
  }
})(Drupal);