<?php

/**
 * @file
 * Support module for user hooks testing.
 */

use Drupal\Component\Render\FormattableMarkup;
use Drupal\Core\Session\AccountInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_user_format_name_alter().
 */
function user_hooks_test_user_format_name_alter(&$name, AccountInterface $account) {
  if (\Drupal::state()->get('user_hooks_test_user_format_name_alter', FALSE)) {
    if (\Drupal::state()->get('user_hooks_test_user_format_name_alter_safe', FALSE)) {
      $name = new FormattableMarkup('<em>@uid</em>', ['@uid' => $account->id()]);
    }
    else {
      $name = '<em>' . $account->id() . '</em>';
    }
  }
}

/**
 * Implements hook_user_login().
 */
function user_hooks_test_user_login(UserInterface $account) {
  if (!\Drupal::state()->get('user_hooks_test_user_login', FALSE)) {
    \Drupal::state()->set('user_hooks_test_user_login', $account->id());
  }
}

/**
 * Implements hook_user_logout().
 */
function user_hooks_test_user_logout(AccountInterface $account) {
  if (!\Drupal::state()->get('user_hooks_test_user_logout', FALSE)) {
    \Drupal::state()->set('user_hooks_test_user_logout', $account->id());
  }
}
