<?php

/**
 * @file
 * Support module for user hooks testing.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Session\AccountInterface;
use Drupal\user_hooks_test\Hook\UserHooksTestHooks;

/**
 * Implements hook_user_format_name_alter().
 */
#[LegacyHook]
function user_hooks_test_user_format_name_alter(&$name, AccountInterface $account) {
  \Drupal::service(UserHooksTestHooks::CLASS)->userHooksTestUserFormatNameAlter($name, $account);
}
