<?php

/**
 * @file
 * Install, update and uninstall functions for the user module.
 */

// cspell:ignore jsonpaths

/**
 * Implements hook_schema().
 */
function user_data_test_schema() {
  $schema['users_data_json'] = [
    'description' => 'Stores module data as key/value pairs per user.',
    'fields' => [
      'data' => [
        'description' => 'Data, keyed by module name.',
        'type' => 'json',
        // Where are the hotpaths? They're likely unnecessary. In production
        // environments running MySQL or Postgres, the optimizer is able to
        // filter based on keys and array members in jsonpaths, and we use
        // functions such as JSON_CONTAINS_PATH() in the example service.
        // (Or in the case of Postgres, the automatically-created whole-column
        // index will provide similar optimization.) This is a good example
        // of understanding the operation of the underlying database driver
        // with respect to your specific needs, particularly when accessing
        // database-specific functions or syntax not yet supported by the
        // query builder.
        // @see https://dev.mysql.com/doc/refman/8.0/en/json.html
      ],
      'uid' => [
        'description' => 'The {users}.uid this record affects.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ],
    ],
    'foreign keys' => [
      'data_user' => [
        'table' => 'users',
        'columns' => [
          'uid' => 'uid',
        ],
      ],
    ],
  ];

  return $schema;
}
