<?php

/**
 * @file
 * Dummy module implementing hook_user_access() to test if entity access is respected.
 */

declare(strict_types=1);

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Hook\LegacyHook;
use Drupal\Core\Session\AccountInterface;
use Drupal\user\Entity\User;
use Drupal\user_access_test\Hook\UserAccessTestHooks;

/**
 * Implements hook_ENTITY_TYPE_access() for entity type "user".
 */
#[LegacyHook]
function user_access_test_user_access(User $entity, $operation, $account) {
  \Drupal::service(UserAccessTestHooks::CLASS)->userAccessTestUserAccess($entity, $operation, $account);
}

/**
 * Implements hook_entity_create_access().
 */
#[LegacyHook]
function user_access_test_entity_create_access(AccountInterface $account, array $context, $entity_bundle) {
  \Drupal::service(UserAccessTestHooks::CLASS)->userAccessTestEntityCreateAccess($account, $context, $entity_bundle);
}

/**
 * Implements hook_entity_field_access().
 */
#[LegacyHook]
function user_access_test_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, ?FieldItemListInterface $items = NULL) {
  \Drupal::service(UserAccessTestHooks::CLASS)->userAccessTestEntityFieldAccess($operation, $field_definition, $account, $items);
}
