<?php

/**
 * @file
 * Install, update and uninstall functions for the shortcut module.
 */

use Drupal\Core\Entity\Sql\SqlContentEntityStorage;
use Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema;

/**
 * Implements hook_schema().
 */
function shortcut_schema() {
  $schema['shortcut_set_users'] = [
    'description' => 'Maps users to shortcut sets.',
    'fields' => [
      'uid' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The {users}.uid for this set.',
      ],
      'set_name' => [
        'type' => 'varchar_ascii',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
        'description' => "The {shortcut_set}.set_name that will be displayed for this user.",
      ],
    ],
    'primary key' => ['uid'],
    'indexes' => [
      'set_name' => ['set_name'],
    ],
    'foreign keys' => [
      'set_user' => [
        'table' => 'users',
        'columns' => ['uid' => 'uid'],
      ],
      'set_name' => [
        'table' => 'shortcut_set',
        'columns' => ['set_name' => 'set_name'],
      ],
    ],
  ];

  return $schema;
}

/**
 * Implements hook_install().
 */
function shortcut_install() {
  // Theme settings are not configuration entities and cannot depend on modules
  // so to set a module-specific setting, we need to set it with logic.
  if (\Drupal::service('theme_handler')->themeExists('claro')) {
    \Drupal::configFactory()
      ->getEditable("claro.settings")
      ->set('third_party_settings.shortcut.module_link', TRUE)
      ->save(TRUE);
  }
}

/**
 * Implements hook_uninstall().
 */
function shortcut_uninstall() {
  // Theme settings are not configuration entities and cannot depend on modules
  // so to unset a module-specific setting, we need to unset it with logic.
  if (\Drupal::service('theme_handler')->themeExists('claro')) {
    \Drupal::configFactory()
      ->getEditable("claro.settings")
      ->clear('third_party_settings.shortcut')
      ->save(TRUE);
  }
}

/**
 * Implements hook_update_dependencies().
 */
function shortcut_update_dependencies() {
  $dependencies = [];
  $dependencies['shortcut'][10101] = [
    'system' => 10101,
  ];
  return $dependencies;
}

/**
 * Make various shortcut fields required at the storage level.
 *
 * The SQL content entity schema no longer uses entity keys to mark their
 * corresponding fields as NOT NULL in the database, so we need to update the
 * respective fields manually.
 */
function shortcut_update_10101() {
  $entity_type_manager = \Drupal::entityTypeManager();

  $entity_type_id = 'shortcut';
  $storage = $entity_type_manager->getStorage($entity_type_id);
  if ($storage instanceof SqlContentEntityStorage) {
    $ref_get_storage_schema = new \ReflectionMethod($storage, 'getStorageSchema');
    $ref_get_storage_schema->setAccessible(TRUE);
    /** @var \Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema $storage_schema */
    $storage_schema = $ref_get_storage_schema->invoke($storage);
    if ($storage_schema instanceof SqlContentEntityStorageSchema) {
      $storage_schema::updateToStorageSchemaV2($entity_type_id);
    }
  }
}
