# Schema for the configuration files of the Editor module.

editor.editor.*:
  type: config_entity
  label: 'Text editor'
  mapping:
    format:
      type: string
      label: 'Name'
    editor:
      type: string
      label: 'Text editor'
      constraints:
        PluginExists:
          manager: plugin.manager.editor
          interface: Drupal\editor\Plugin\EditorPluginInterface
    settings:
      type: editor.settings.[%parent.editor]
    image_upload:
      type: mapping
      label: 'Image upload settings'
      mapping:
        status:
          type: boolean
          label: 'Status'
        scheme:
          type: optional_type.string.image_upload_status_[%parent.status]
          label: 'File storage'
        directory:
          type: optional_type.string.image_upload_status_[%parent.status]
          label: 'Upload directory'
        max_size:
          type: optional_type.string.image_upload_status_[%parent.status]
          label: 'Maximum file size'
        max_dimensions:
          type: optional_type.mapping.image_upload_status_[%parent.status]
          label: 'Maximum dimensions'
          mapping:
            width:
              type: integer
              nullable: true
              label: 'Maximum width'
            height:
              type: integer
              nullable: true
              label: 'Maximum height'

optional_type.string.*:
  type: string

optional_type.mapping.*:
  type: mapping

optional_type.string.image_upload_status_0:
  type: string
  requiredKey: false
optional_type.mapping.image_upload_status_0:
  type: mapping
  requiredKey: false
