<?php

/**
 * @file
 * Primary module hooks for image_field_property_constraint_validation module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function image_field_property_constraint_validation_entity_bundle_field_info_alter($fields, EntityTypeInterface $entity_type): void {
  if ($entity_type->id() == 'node' && !empty($fields['field_image'])) {
    /** @var \Drupal\field\Entity\FieldConfig[] $fields */
    $fields['field_image']->addPropertyConstraints('alt', ['AltTextContainsLlamas' => []]);
  }
}
