<?php

/**
 * @file
 * Helper module for the Content Translation tests.
 */

declare(strict_types=1);

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Form submission handler for custom field added based on a request parameter.
 *
 * @see content_translation_test_form_node_article_form_alter()
 */
function content_translation_test_form_node_form_submit($form, FormStateInterface $form_state) {
  \Drupal::state()->set('test_field_only_en_fr', $form_state->getValue('test_field_only_en_fr'));
}
