<<<<<<< HEAD
/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (_ref) {
  var offCanvas = _ref.offCanvas;
  var originalResetSize = offCanvas.resetSize;

  offCanvas.resetSize = function (event) {
    originalResetSize(event);
    event.data.$element.attr('data-resize-done', 'true');
  };
})(Drupal);
=======
(function ({ offCanvas }) {
  const originalResetSize = offCanvas.resetSize;

  /**
   * Wraps the Drupal.offCanvas.resetSize() method.
   *
   * @param {jQuery.Event} event
   *   The event triggered.
   * @param {object} event.data
   *   Data attached to the event.
   */
  offCanvas.resetSize = (event) => {
    originalResetSize(event);
    // Set an attribute so that tests can reliably detect when the off-canvas
    // area has been resized.
    event.data.$element.attr('data-resize-done', 'true');
  };
})(Drupal);
>>>>>>> upstream/11.x
