<?php

declare(strict_types=1);

namespace Drupal\Tests\node\FunctionalJavascript;

use Drupal\FunctionalJavascriptTests\WebDriverTestBase;

/**
 * Tests node form summaries generated by Drupal.behaviors.nodeDetailsSummaries.
 *
 * @group node
 */
class NodeDetailsSummariesTest extends WebDriverTestBase {

  /**
   * {@inheritdoc}
   */
  protected static $modules = ['node'];

  /**
   * {@inheritdoc}
   */
  protected $defaultTheme = 'stark';

  /**
   * {@inheritdoc}
   */
  protected function setUp(): void {
    parent::setUp();

    $this->drupalCreateContentType([
      'type' => 'page',
      'name' => 'Basic page',
    ]);
  }

  /**
   * Tests summary output generated by Drupal.behaviors.nodeDetailsSummaries.
   */
  public function testNodeDetailsSummaries(): void {
    $assertSession = $this->assertSession();
    $user = $this->createUser([
      'edit any page content',
      'administer nodes',
    ]);
    $this->drupalLogin($user);
    $node = $this->drupalCreateNode([
      'title' => $this->randomMachineName(),
      'type' => 'page',
      // Hardcode created date for assertion below.
      'created' => 1743476776,
    ]);
    $this->drupalGet($node->toUrl('edit-form'));

    $assertSession->waitForElement('css', '.node-form-author summary span.summary');
    $assertSession->pageTextContains(\sprintf('By %s (%s) on 4/1/2025', $user->getAccountName(), $user->id()));
    $assertSession->waitForElement('css', '.node-form-options summary span.summary');
    $assertSession->pageTextContains('Promoted to front page');
  }

}
