<?php

/**
 * @file
 * Contains install and update functions for Layout Builder.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\ContentEntityType;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Site\Settings;
use Drupal\Core\StringTranslation\PluralTranslatableMarkup;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\layout_builder\Entity\LayoutBuilderEntityViewDisplay;
use Drupal\layout_builder\Section;

/**
 * Implements hook_install().
 */
function layout_builder_install() {
  $display_changed = FALSE;

  $displays = LayoutBuilderEntityViewDisplay::loadMultiple();
  /** @var \Drupal\layout_builder\Entity\LayoutEntityDisplayInterface[] $displays */
  foreach ($displays as $display) {
    // Create the first section from any existing Field Layout settings.
    $field_layout = $display->getThirdPartySettings('field_layout');
    if (isset($field_layout['id'])) {
      $field_layout += ['settings' => []];
      $display
        ->enableLayoutBuilder()
        ->appendSection(new Section($field_layout['id'], $field_layout['settings']))
        ->save();
      $display_changed = TRUE;
    }
  }

  // Clear the rendered cache to ensure the new layout builder flow is used.
  // While in many cases the above change will not affect the rendered output,
  // the cacheability metadata will have changed and should be processed to
  // prepare for future changes.
  if ($display_changed) {
    Cache::invalidateTags(['rendered']);
  }
}

/**
 * Implements hook_schema().
 */
function layout_builder_schema() {
  $schema['inline_block_usage'] = [
    'description' => 'Track where a block_content entity is used.',
    'fields' => [
      'block_content_id' => [
        'description' => 'The block_content entity ID.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'layout_entity_type' => [
        'description' => 'The entity type of the parent entity.',
        'type' => 'varchar_ascii',
        'length' => EntityTypeInterface::ID_MAX_LENGTH,
        'not null' => FALSE,
        'default' => '',
      ],
      'layout_entity_id' => [
        'description' => 'The ID of the parent entity.',
        'type' => 'varchar_ascii',
        'length' => 128,
        'not null' => FALSE,
        'default' => 0,
      ],
    ],
    'primary key' => ['block_content_id'],
    'indexes' => [
      'type_id' => ['layout_entity_type', 'layout_entity_id'],
    ],
  ];
  return $schema;
}

/**
 * Implements hook_update_last_removed().
 */
function layout_builder_update_last_removed() {
  return 8602;
}

function layout_builder_update_9001(&$sandbox) {
  $db = \Drupal::database();
  if (!isset($sandbox['tables'])) {
    // Get a list of content entities.
    $entity_types = array_filter(\Drupal::entityTypeManager()->getDefinitions(), function ($value) {
      return $value instanceof ContentEntityType;
    });

    $tables = [];

    // Compile a list of tables to update.
    /** @var Drupal\Core\Entity\ContentEntityType $entity_type */
    foreach ($entity_types as $key => $entity_type) {
      if ($db->schema()->tableExists("{$key}__layout_builder__layout")) {
        $tables[] = "{$key}__layout_builder__layout";
      }
      if ($entity_type->isRevisionable() && $db->schema()->tableExists("{$key}_revision__layout_builder__layout")) {
        $tables[] = "{$key}_revision__layout_builder__layout";
      }
    }
    $sandbox['tables'] = $tables;
    $sandbox['total'] = count($sandbox['tables']);
    $sandbox['temp_store_updated'] = FALSE;
  }

  $section_column = 'layout_builder__layout_section';

  $tables = array_splice($sandbox['tables'], 0, (int) Settings::get('entity_update_batch_size', 50));
  foreach ($tables as $table_name) {
    // Select records that the column name.
    $query = $db->select($table_name, 't')
      ->fields('t', ['entity_id', 'revision_id', 'delta', $section_column]);

    $results = $query->execute();

    // Loop through the results.
    foreach ($results as $record) {
      // Unserialize the section field into it's class object.
      /** @var \Drupal\layout_builder\Section $section */
      $section = unserialize($record->layout_builder__layout_section);

      $section_array = $section->toArray();
      $section_array['uuid'] = \Drupal::service('uuid')->generate();
      $section_array['weight'] = $record->delta;
      $section = Section::fromArray($section_array);

      // Serialize section component and update section component db record.
      // Replace the old section with our newly created one.
      $db->update($table_name)
        ->condition('revision_id', $record->revision_id)
        ->condition('delta', $record->delta)
        ->fields([
          $section_column => serialize($section),
        ])
        ->execute();
    }
  }

  // Check if we need to update key_value_expire.
  if (!$sandbox['temp_store_updated'] && $db->schema()->tableExists('key_value_expire')) {
    // Check if we have a temp store records that need to be updated.
    // Temp store is saved in the db in the key_value_expire,
    // And holds a serialized blob with the unsaved changes.
    $query = $db->select('key_value_expire', 'kve')
      ->fields('kve', ['name', 'value', 'expire'])
      ->condition('collection', 'tempstore.shared.layout_builder.section_storage.overrides', '=');

    $results = $query
      ->execute();

    foreach ($results as $record) {
      // Un-serialize the section storage.
      $stored_data = unserialize($record->value);
      // @todo Could this be another type of section storage?
      /** @var \Drupal\layout_builder\Plugin\SectionStorage\OverridesSectionStorage $section_storage */
      $section_storage = $stored_data->data['section_storage'];

      // Loop through sections in the storage.
      foreach ($section_storage->getSections() as $delta => &$section) {
        $section_array = $section->toArray();
        $section_array['uuid'] = \Drupal::service('uuid')->generate();
        $section_array['weight'] = $delta;
        $section = Section::fromArray($section_array);
      }
      $stored_data->data['section_storage'] = $section_storage;

      // Insert the updated tempstore.
      $db->update('key_value_expire')
        ->condition('name', $record->name, '=')
        ->condition('expire', $record->expire, '=')
        ->fields([
          'value' => serialize($stored_data),
        ])
        ->execute();
    }
    $sandbox['temp_store_updated'] = TRUE;
  }

  $sandbox['#finished'] = empty($sandbox['total']) || empty($sandbox['tables']) ? 1 : ($sandbox['total'] - count($sandbox['tables'])) / $sandbox['total'];
  if ($sandbox['#finished'] === 1) {
    return new TranslatableMarkup('Update finished.');
  }
  return new PluralTranslatableMarkup($sandbox['total'] - count($sandbox['tables']),
    'Processed @count entry of @total.',
    'Processed @count entries of @total.',
    ['@total' => $sandbox['total']],
  );
}
