<?php

/**
 * @file
 * Contains install and update functions for Block.
 */

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_install().
 */
function block_install() {
  // Because the Block module upon installation unconditionally overrides all
  // HTML output by selecting a different page display variant, we must
  // invalidate all cached HTML output.
  Cache::invalidateTags(['rendered']);
}

/**
 * Implements hook_update_last_removed().
 */
function block_update_last_removed() {
  return 8003;
}

/**
 * Change label_display value to boolean.
 */
function block_update_10100(&$sandbox) {
  $blockEntityTypeManager = \Drupal::entityTypeManager()->getStorage('block');
  $blocks = $blockEntityTypeManager->loadMultiple();
  foreach ($blocks as $block) {
    $settings = $block->get('settings');
    switch ($settings['label_display']) {
      case '0':
        $settings['label_display'] = FALSE;
        break;
      case '1':
      case 'visible':
        $settings['label_display'] = TRUE;
    }
    $block->set('settings', $settings);
    $block->save();
  }
}
