<?php

/**
 * @file
 * Contains install and update functions for Block.
 */

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_install().
 */
function block_install() {
  // Because the Block module upon installation unconditionally overrides all
  // HTML output by selecting a different page display variant, we must
  // invalidate all cached HTML output.
  Cache::invalidateTags(['rendered']);
}

/**
 * Implements hook_update_last_removed().
 */
function block_update_last_removed() {
  return 8003;
}

/**
 *  Add 'contextualize_title' setting for page title blocks.
 */
function block_update_11100() {
  $config_factory = \Drupal::configFactory();
  foreach ($config_factory->listAll('block.block.') as $block_config_name) {
    if(!str_contains($block_config_name, 'page_title')){
      continue;
    }
    $block = $config_factory->getEditable($block_config_name);

    $settings = $block->get('settings');
    if(str_contains($block->getName(), 'claro')){
      $settings['contextualize_title'] = TRUE;
    }
    else {
      $settings['contextualize_title'] = FALSE;
    }
    $block->set('settings', $settings);

    // Mark the resulting configuration as trusted data. This avoids issues with
    // future schema changes.
    $block->save(TRUE);
  }
}
