<?php

/**
 * @file
 * Helper module for the Batch API tests.
 */

/**
 * Batch 8: Throws an exception.
 */
function _batch_test_batch_8(): array {
  $batch_builder = (new BatchBuilder())
    ->setFile(\Drupal::service('extension.list.module')->getPath('batch_test') . '/batch_test.callbacks.inc')
    ->addOperation('_batch_test_callback_8', [FALSE])
    ->addOperation('_batch_test_callback_8', [TRUE]);
  return $batch_builder->toArray() + ['batch_test_id' => 'batch_8'];
}

/**
 * Implements callback_batch_operation().
 *
 * Tests the progress page theme.
 */
function _batch_test_theme_callback() {
  // Because drupalGet() steps through the full progressive batch before
  // returning control to the test function, we cannot test that the correct
  // theme is being used on the batch processing page by viewing that page
  // directly. Instead, we save the theme being used in a variable here, so
  // that it can be loaded and inspected in the thread running the test.
  $theme = \Drupal::theme()->getActiveTheme()->getName();
  \Drupal::service('batch_test.batch_test_stack')->batchTestStack($theme);
}

/**
 * Tests the title on the progress page by performing a batch callback.
 */
function _batch_test_title_callback() {
  // Because drupalGet() steps through the full progressive batch before
  // returning control to the test function, we cannot test that the correct
  // title is being used on the batch processing page by viewing that page
  // directly. Instead, we save the title being used in a variable here, so
  // that it can be loaded and inspected in the thread running the test.
  $request = \Drupal::request();
  $route_match = \Drupal::routeMatch();
  $title = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
  \Drupal::service('batch_test.batch_test_stack')->batchTestStack($title);
}
