<?php

/**
 * @file
 * Helper module for the Media Embed text editor plugin tests.
 */

declare(strict_types=1);

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function media_test_embed_preprocess_media_embed_error(&$variables) {
  $variables['attributes']['class'][] = 'this-error-message-is-themeable';
}
