<?php

/**
 * @file
 * Install, update and uninstall functions for the toolbar module.
 */

/**
 * Add toolbar settings with default menu depth.
 */
function toolbar_update_10101() {
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->getEditable('toolbar.settings');
  if (empty($config->get('menu_depth'))) {
    $config->set('menu_depth', 4);
    $config->save(TRUE);
  }
}
