<?php

/**
 * @file
 * Helper module for the Common tests.
 */

declare(strict_types=1);

/**
 * Implements hook_module_implements_alter().
 *
 * @see block_drupal_alter_foo_alter()
 */
function common_test_module_implements_alter(&$implementations, $hook) {
  // For
  // \Drupal::moduleHandler()->alter(array('drupal_alter', 'drupal_alter_foo'), ...),
  // make the block module implementations run after all the other modules. Note
  // that when \Drupal::moduleHandler->alter() is called with an array of types,
  // the first type is considered primary and controls the module order.
  if ($hook == 'drupal_alter_alter' && isset($implementations['block'])) {
    $group = $implementations['block'];
    unset($implementations['block']);
    $implementations['block'] = $group;
  }
}

/**
 * Implements MODULE_preprocess().
 *
 * @see RenderTest::testDrupalRenderThemePreprocessAttached()
 */
function common_test_preprocess(&$variables, $hook) {
  if (!\Drupal::state()->get('theme_preprocess_attached_test', FALSE)) {
    return;
  }
  $variables['#attached']['library'][] = 'test/generic_preprocess';
}

/**
 * Implements MODULE_preprocess_HOOK().
 *
 * @see RenderTest::testDrupalRenderThemePreprocessAttached()
 */
function common_test_preprocess_common_test_render_element(&$variables) {
  if (!\Drupal::state()->get('theme_preprocess_attached_test', FALSE)) {
    return;
  }
  $variables['#attached']['library'][] = 'test/specific_preprocess';
}
