/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, settings, document, Shepherd) {
  var queryString = decodeURI(window.location.search);
  Drupal.tour = Drupal.tour || {
    models: {},
    views: {},
    currentTour: []
  };
  Drupal.behaviors.tour = {
    attach: function attach(context) {
      once('tour', 'body').forEach(function () {
        console.log("2inside once");
        var shepherdTour = new Shepherd.Tour(settings.tourShepherdConfig);

        if (settings._tour_internal) {
          $(context).find('#toolbar-tab-tour').toggleClass('hidden', false);
          $(context).find('#toolbar-tab-tour')[0].addEventListener('click', function () {
            shepherdTour.start();
          }, false);
          console.log("settings tour internal is true");
          Drupal.tour.currentTour = settings._tour_internal;
        }

        var tourItems = Drupal.tour.currentTour;
        tourItems.forEach(function (tourStepConfig, index) {
          var tourItemOptions = {
            title: tourStepConfig.title ? Drupal.checkPlain(tourStepConfig.title) : null,
            text: function text() {
              return Drupal.theme('tourItemContent', tourStepConfig);
            },
            attachTo: tourStepConfig.attachTo,
            buttons: [Drupal.tour.nextButton(shepherdTour, tourStepConfig)],
            classes: tourStepConfig.classes,
            index: index
          };
          shepherdTour.addStep(tourItemOptions);
        });
        shepherdTour.on('cancel', function () {
          console.log("tour is cancelled");
        });
        shepherdTour.on('complete', function () {
          console.log("tour is complete");
        });
      });
    }
  };

  Drupal.tour.nextButton = function (shepherdTour, tourStepConfig) {
    return {
      classes: 'button button--primary',
      text: tourStepConfig.cancelText ? tourStepConfig.cancelText : Drupal.t('Next'),
      action: tourStepConfig.cancelText ? shepherdTour.cancel : shepherdTour.next
    };
  };

  Drupal.theme.tourItemContent = function (tourStepConfig) {
    return "".concat(tourStepConfig.body, "<div class=\"tour-progress\">").concat(tourStepConfig.counter, "</div>");
  };
})(jQuery, Drupal, drupalSettings, document, window.Shepherd);