/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, settings, document, Shepherd) {
  var queryString = decodeURI(window.location.search);
  Drupal.tour = Drupal.tour || {
    currentTour: [],
    isActive: false,
    activeTour: []
  };

  function _removeIrrelevantTourItems(tourItems) {
    var tips = /tips=([^&]+)/.exec(queryString);
    var filteredTour = tourItems.filter(function (tourItem) {
      if (tips && tourItem.hasOwnProperty('classes') && !tourItem.classes.includes(tips[1])) {
        return false;
      }

      return !(tourItem.selector && !document.querySelector(tourItem.selector));
    });

    if (tourItems.length !== filteredTour.length) {
      filteredTour.forEach(function (filteredTourItem, filteredTourItemId) {
        filteredTour[filteredTourItemId].counter = Drupal.t('!tour_item of !total', {
          '!tour_item': filteredTourItemId + 1,
          '!total': filteredTour.length
        });

        if (filteredTourItemId === filteredTour.length - 1) {
          filteredTour[filteredTourItemId].cancelText = Drupal.t('End tour');
        }
      });
      Drupal.tour.currentTour = filteredTour;
    }
  }

  function toggleTour() {
    if (Drupal.tour.isActive) {
      Drupal.tour.activeTour.cancel();
      return;
    }

    _removeIrrelevantTourItems(Drupal.tour.currentTour);

    var shepherdTour = new Shepherd.Tour(settings.tourShepherdConfig);
    shepherdTour.on('cancel', function () {
      Drupal.tour.isActive = false;
    });
    shepherdTour.on('complete', function () {
      Drupal.tour.isActive = false;
    });
    var tourItems = Drupal.tour.currentTour;

    if (!tourItems.length) {
      return;
    }

    settings.tourShepherdConfig.defaultStepOptions.popperOptions.modifiers.push({
      name: 'moveArrowJoyridePosition',
      enabled: true,
      phase: 'write',
      fn: function fn(_ref) {
        var state = _ref.state;
        var arrow = state.elements.arrow;
        var placement = state.placement;

        if (arrow && /^top|bottom/.test(placement) && /-start|-end$/.test(placement)) {
          var horizontalPosition = placement.split('-')[1];
          var offset = horizontalPosition === 'start' ? 28 : state.elements.popper.clientWidth - 56;
          arrow.style.transform = "translate3d(".concat(offset, "px, 0px, 0px)");
        }
      }
    });
    tourItems.forEach(function (tourStepConfig, index) {
      var tourItemOptions = {
        title: tourStepConfig.title ? Drupal.checkPlain(tourStepConfig.title) : null,
        text: function text() {
          return Drupal.theme('tourItemContent', tourStepConfig);
        },
        attachTo: tourStepConfig.attachTo,
        buttons: [Drupal.tour.nextButton(shepherdTour, tourStepConfig)],
        classes: tourStepConfig.classes,
        index: index
      };
      tourItemOptions.when = {
        show: function show() {
          var nextButton = shepherdTour.currentStep.el.querySelector('footer button');
          nextButton.focus();

          if (Drupal.tour.hasOwnProperty('convertToJoyrideMarkup')) {
            Drupal.tour.convertToJoyrideMarkup(shepherdTour);
          }
        }
      };
      shepherdTour.addStep(tourItemOptions);
    });
    shepherdTour.start();
    Drupal.tour.isActive = true;
    Drupal.tour.activeTour = shepherdTour;
  }

  Drupal.behaviors.tour = {
    attach: function attach(context) {
      once('tour', 'body').forEach(function () {
        Drupal.tour.currentTour = settings._tour_internal;

        if (settings._tour_internal) {
          $(context).find('#toolbar-tab-tour').toggleClass('hidden', false);
          context.querySelector('#toolbar-tab-tour > button').addEventListener('click', function () {
            toggleTour();
          }, false);
        }

        if (/tour=?/i.test(queryString)) {
          toggleTour();
        }
      });
    }
  };

  Drupal.tour.nextButton = function (shepherdTour, tourStepConfig) {
    return {
      classes: 'button button--primary',
      text: tourStepConfig.cancelText ? tourStepConfig.cancelText : Drupal.t('Next'),
      action: tourStepConfig.cancelText ? shepherdTour.cancel : shepherdTour.next
    };
  };

  Drupal.theme.tourItemContent = function (tourStepConfig) {
    return "".concat(tourStepConfig.body, "<div class=\"tour-progress\">").concat(tourStepConfig.counter, "</div>");
  };
})(jQuery, Drupal, drupalSettings, document, window.Shepherd);