<?php

/**
 * @file
 * Simulates a custom module with a local po file.
 */

declare(strict_types=1);

/**
 * Implements hook_modules_installed().
 *
 * @see \Drupal\Tests\locale\Functional\LocaleConfigTranslationImportTest::testConfigTranslationWithForeignLanguageDefault
 */
function locale_test_translate_modules_installed($modules, $is_syncing) {
  // Ensure that writing to configuration during install does not cause
  // \Drupal\locale\LocaleConfigSubscriber to create incorrect translations due
  // the configuration langcode and data being out-of-sync.
  Drupal::configFactory()->getEditable('locale_test_translate.settings')->set('key_set_during_install', TRUE)->save();
}
