<?php

/**
 * @file
 * Module for testing the Announcements Feed functionality.
 */

/**
 * Implements hook_menu().
 */
function announce_feed_test_menu() {
  $items['announcements-feed-json/%'] = array(
    'title' => 'Announcements Feed test',
    'page callback' => 'announce_feed_test_set_feed_config',
    'page arguments' => array(1),
    // In unit tests, restrictions not required.
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Helper function to set announcements feed url.
 */
function announce_feed_test_set_feed_config($json_name) {
  $file = __DIR__ . "/announce_feed/$json_name.json";
  if (!is_file($file)) {
    // Return an empty response.
    drupal_not_found();
  }

  $contents = file_get_contents($file);
  drupal_json_output(drupal_json_decode($contents));
}
