<?php

declare(strict_types=1);

namespace Drupal\Tests\sqlite\Kernel\sqlite;

use Drupal\KernelTests\Core\Database\AutoGeneratedFieldTestTrait;
use Drupal\KernelTests\Core\Database\AutoGeneratedIndexTestTrait;
use Drupal\KernelTests\Core\Database\DriverSpecificSchemaTestBase;

/**
 * Tests schema API for the SQLite driver.
 *
 * @group Database
 */
class SchemaTest extends DriverSpecificSchemaTestBase {

  use AutoGeneratedFieldTestTrait;
  use AutoGeneratedIndexTestTrait;

  /**
   * {@inheritdoc}
   */
  public function checkSchemaComment(string $description, string $table, ?string $column = NULL): void {
    // The sqlite driver schema does not support fetching table/column
    // comments.
  }

  /**
   * {@inheritdoc}
   */
  protected function tryInsertExpectsIntegrityConstraintViolationException(string $tableName): void {
    // Sqlite does not throw an IntegrityConstraintViolationException here.
  }

  /**
   * {@inheritdoc}
   */
  public function testTableWithSpecificDataType(): void {
    $table_specification = [
      'description' => 'Schema table description.',
      'fields' => [
        'timestamp'  => [
          'sqlite_type' => 'datetime',
          'not null' => FALSE,
          'default' => NULL,
        ],
      ],
    ];
    $this->schema->createTable('test_timestamp', $table_specification);
    $this->assertTrue($this->schema->tableExists('test_timestamp'));
  }

  /**
   * @covers \Drupal\sqlite\Driver\Database\sqlite\Schema::introspectIndexSchema
   */
  public function testIntrospectIndexSchema(): void {
    $table_specification = [
      'fields' => [
        'id'  => [
          'type' => 'int',
          'not null' => TRUE,
          'default' => 0,
        ],
        'test_field_1'  => [
          'type' => 'int',
          'not null' => TRUE,
          'default' => 0,
        ],
        'test_field_2'  => [
          'type' => 'int',
          'default' => 0,
        ],
        'test_field_3'  => [
          'type' => 'int',
          'default' => 0,
        ],
        'test_field_4'  => [
          'type' => 'int',
          'default' => 0,
        ],
        'test_field_5'  => [
          'type' => 'int',
          'default' => 0,
        ],
      ],
      'primary key' => ['id', 'test_field_1'],
      'unique keys' => [
        'test_field_2' => ['test_field_2'],
        'test_field_3_test_field_4' => ['test_field_3', 'test_field_4'],
      ],
      'indexes' => [
        'test_field_4' => ['test_field_4'],
        'test_field_4_test_field_5' => ['test_field_4', 'test_field_5'],
      ],
    ];

    $table_name = strtolower($this->getRandomGenerator()->name());
    $this->schema->createTable($table_name, $table_specification);

    unset($table_specification['fields']);

    $introspect_index_schema = new \ReflectionMethod(get_class($this->schema), 'introspectIndexSchema');
    $index_schema = $introspect_index_schema->invoke($this->schema, $table_name);

    $this->assertEquals($table_specification, $index_schema);
  }

  /**
   * Tests JSON schema type.
   *
   * @see https://www.sqlite.org/json1.html#jptr
   */
  public function testJsonSchema(): void {
    $this->doTestJsonSchema();
    foreach (self::JSON_TEST_DATA as $path => $expected) {
      $query = $this->connection->select('test_json');
      $query->addExpression('json_extract([test_field], :path, "$._")', NULL, [
        ':path' => $path,
      ]);
      $actual = json_decode($query->execute()->fetchField(), TRUE)[0];
      $this->assertSame($expected, $actual);
    }
  }

  /**
   * Test generated column support, depending on DB version.
   */
  public function testGeneratedColumn(): void {
    if (!$this->connection->supportsGeneratedColumns()) {
      $this->markTestSkipped(sprintf('Version %s of SQLite does not support generated columns.', $this->connection->version()));
    }
    parent::testGeneratedColumn();
  }

  /**
   * Tests automatic optimization to use a JSON-based index.
   */
  public function testJsonOptimization(): void {
    if (!$this->connection->supportsGeneratedColumns()) {
      $this->markTestSkipped(sprintf('Version %s of SQLite does not support generated columns.', $this->connection->version()));
    }
    $this->schema->createTable('test_json', static::JSON_TABLE_SPECIFICATION);
    $query = $this->connection->select('test_json');
    $query->jsonCondition('test_field', '$.number', 0);
    $query->addExpression('id');
    $explained = $this->connection->query(
      'EXPLAIN QUERY PLAN ' . $query,
      $query->getArguments(),
      // This would normally get pulled through automatically, however since we
      // are doing EXPLAIN here, we need to re-set it explicitly for _this_
      // query.
      ['strict_params' => $query->usesStrictParameters()]
    )->fetchAssoc();
    $this->assertStringContainsString('USING INDEX', $explained['detail'], 'Auto-generated index not used in query.');
  }

}
