<?php

/**
 * @file
 * Help Page Test module to test the help page.
 */

declare(strict_types=1);

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function help_page_test_help($route_name, RouteMatchInterface $route_match): string {

  switch ($route_name) {
    case 'help.page.help_page_test':
      // Make the help text conform to core standards. See
      // \Drupal\system\Tests\Functional\GenericModuleTestBase::assertHookHelp().
      return '<p>' . t('Read the <a href=":url">online documentation for the Help Page Test module</a>.', [
        ':url' => 'http://www.example.com',
      ]) . '</p>';

    case 'help_page_test.has_help':
      return '<p>' . t('I have help!') . '</p>';

    case 'help_page_test.test_array':
      return '<p>Help text from help_page_test_help module.</p>';

    default:
      return '';
  }

  // Ensure that hook_help() can return an empty string and not cause the block
  // to display.
  return '';
}
