<?php

/**
 * @file
 * Drupal database update API.
 *
 * This file contains functions to perform database updates for a Drupal
 * installation. It is included and used extensively by update.php.
 */

use Drupal\Core\Update\DeprecatedUpdate;
use Drupal\Core\Update\Update;

/**
 * Returns whether the minimum schema requirement has been satisfied.
 *
 * @return array
 *   A requirements info array.
 *
 * @deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use
 *   \Drupal\Core\Update\DeprecatedUpdate::systemSchemaRequirements() instead.
 *
 * @see https://www.drupal.org/node/3013060
 * @see \Drupal\Core\Update\DeprecatedUpdate::systemSchemaRequirements()
 */
function update_system_schema_requirements() {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use \Drupal\Core\Update\DeprecatedUpdate::systemSchemaRequirements() instead. See https://www.drupal.org/node/3013060', E_USER_DEPRECATED);
  /** @var \Drupal\Core\Update\DeprecatedUpdate $update */
  $update = \Drupal::service(DeprecatedUpdate::class);
  return $update->systemSchemaRequirements();
}

/**
 * Checks update requirements and reports errors and (optionally) warnings.
 *
 * @deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use
 *   \Drupal\Core\Update\Update::getRequirements() instead.
 *
 * @see https://www.drupal.org/node/3013060
 * @see \Drupal\Core\Update\Update::getRequirements()
 */
function update_check_requirements() {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use \Drupal\Core\Update\Update::getRequirements() instead. See https://www.drupal.org/node/3013060', E_USER_DEPRECATED);
  /** @var \Drupal\Core\Update\Update $update */
  $update = \Drupal::service(Update::class);
  return $update->getRequirements();
}

/**
 * Helper to detect and fix 'missing' schema information.
 *
 * Repairs the case where a module has no schema version recorded.
 * This has to be done prior to updates being run, otherwise the update
 * system would detect and attempt to run all historical updates for a
 * module.
 *
 * @todo: remove in a major version after
 *   https://www.drupal.org/project/drupal/issues/3130037 has been fixed.
 *
 * @deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use
 *   \Drupal\Core\Update\DeprecatedUpdate::fixMissingSchema() instead.
 *
 * @see https://www.drupal.org/node/3013060
 * @see \Drupal\Core\Update\DeprecatedUpdate::fixMissingSchema()
 */
function _update_fix_missing_schema() {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use \Drupal\Core\Update\DeprecatedUpdate::fixMissingSchema() instead. See https://www.drupal.org/node/3013060', E_USER_DEPRECATED);
  /** @var \Drupal\Core\Update\DeprecatedUpdate $update */
  $update = \Drupal::service(DeprecatedUpdate::class);
  $update->fixMissingSchema();
}

/**
 * Implements callback_batch_operation().
 *
 * Performs one update and stores the results for display on the results page.
 *
 * If an update function completes successfully, it should return a message
 * as a string indicating success, for example:
 * @code
 * return t('New index added successfully.');
 * @endcode
 *
 * Alternatively, it may return nothing. In that case, no message
 * will be displayed at all.
 *
 * If it fails for whatever reason, it should throw an instance of
 * Drupal\Core\Utility\UpdateException with an appropriate error message, for
 * example:
 * @code
 * use Drupal\Core\Utility\UpdateException;
 * throw new UpdateException('Description of what went wrong');
 * @endcode
 *
 * If an exception is thrown, the current update and all updates that depend on
 * it will be aborted. The schema version will not be updated in this case, and
 * all the aborted updates will continue to appear on update.php as updates
 * that have not yet been run.
 *
 * If an update function needs to be re-run as part of a batch process, it
 * should accept the $sandbox array by reference as its first parameter
 * and set the #finished property to the percentage completed that it is, as a
 * fraction of 1.
 *
 * @param $module
 *   The module whose update will be run.
 * @param $number
 *   The update number to run.
 * @param $dependency_map
 *   An array whose keys are the names of all update functions that will be
 *   performed during this batch process, and whose values are arrays of other
 *   update functions that each one depends on.
 * @param $context
 *   The batch context array.
 *
 * @deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use
 *   \Drupal\Core\Update\Update::doOne() instead.
 *
 * @see https://www.drupal.org/node/3013060
 * @see \Drupal\Core\Update\Update::doOne()
 * @see \Drupal\Core\Update\Update::resolveDependencies()
 */
function update_do_one($module, $number, $dependency_map, &$context) {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use \Drupal\Core\Update\Update::doOne() instead. See https://www.drupal.org/node/3013060', E_USER_DEPRECATED);
  /** @var \Drupal\Core\Update\Update $update */
  $update = \Drupal::service(Update::class);
  $update->doOne($module, $number, $dependency_map, $context);
}

/**
 * Executes a single hook_post_update_NAME().
 *
 * @param string $function
 *   The function name, that should be executed.
 * @param array $context
 *   The batch context array.
 *
 * @deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use
 *   \Drupal\Core\Update\Update::invokePostUpdate() instead.
 *
 * @see https://www.drupal.org/node/3013060
 * @see \Drupal\Core\Update\Update::invokePostUpdate()
 */
function update_invoke_post_update($function, &$context) {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use \Drupal\Core\Update\Update::invokePostUpdate() instead. See https://www.drupal.org/node/3013060', E_USER_DEPRECATED);
  /** @var \Drupal\Core\Update\Update $update */
  $update = \Drupal::service(Update::class);
  $update->invokePostUpdate($function, $context);
}

/**
 * Returns a list of all the pending database updates.
 *
 * @return array
 *   An associative array keyed by module name which contains all information
 *   about database updates that need to be run, and any updates that are not
 *   going to proceed due to missing requirements. The system module will
 *   always be listed first.
 *
 *   The subarray for each module can contain the following keys:
 *   - start: The starting update that is to be processed. If this does not
 *       exist then do not process any updates for this module as there are
 *       other requirements that need to be resolved.
 *   - warning: Any warnings about why this module can not be updated.
 *   - pending: An array of all the pending updates for the module including
 *       the update number and the description from source code comment for
 *       each update function. This array is keyed by the update number.
 *
 * @deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use
 *   \Drupal\Core\Update\Update::getList() instead.
 *
 * @see https://www.drupal.org/node/3013060
 * @see \Drupal\Core\Update\Update::getList()
 */
function update_get_update_list() {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use \Drupal\Core\Update\Update::getList() instead. See https://www.drupal.org/node/3013060', E_USER_DEPRECATED);
  /** @var \Drupal\Core\Update\Update $update */
  $update = \Drupal::service(Update::class);
  return $update->getList();
}

/**
 * Resolves dependencies in a set of module updates, and orders them correctly.
 *
 * This function receives a list of requested module updates and determines an
 * appropriate order to run them in such that all update dependencies are met.
 * Any updates whose dependencies cannot be met are included in the returned
 * array but have the key 'allowed' set to FALSE; the calling function should
 * take responsibility for ensuring that these updates are ultimately not
 * performed.
 *
 * In addition, the returned array also includes detailed information about the
 * dependency chain for each update, as provided by the depth-first search
 * algorithm in Drupal\Component\Graph\Graph::searchAndSort().
 *
 * @param $starting_updates
 *   An array whose keys contain the names of modules with updates to be run
 *   and whose values contain the number of the first requested update for that
 *   module.
 *
 * @return array
 *   An array whose keys are the names of all update functions within the
 *   provided modules that would need to be run in order to fulfill the
 *   request, arranged in the order in which the update functions should be
 *   run. (This includes the provided starting update for each module and all
 *   subsequent updates that are available.) The values are themselves arrays
 *   containing all the keys provided by the
 *   Drupal\Component\Graph\Graph::searchAndSort() algorithm, which encode
 *   detailed information about the dependency chain for this update function
 *   (for example: 'paths', 'reverse_paths', 'weight', and 'component'), as
 *   well as the following additional keys:
 *   - 'allowed': A boolean which is TRUE when the update function's
 *     dependencies are met, and FALSE otherwise. Calling functions should
 *     inspect this value before running the update.
 *   - 'missing_dependencies': An array containing the names of any other
 *     update functions that are required by this one but that are unavailable
 *     to be run. This array will be empty when 'allowed' is TRUE.
 *   - 'module': The name of the module that this update function belongs to.
 *   - 'number': The number of this update function within that module.
 *
 * @deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use
 *   \Drupal\Core\Update\Update::resolveDependencies() instead.
 *
 * @see https://www.drupal.org/node/3013060
 * @see \Drupal\Core\Update\Update::resolveDependencies()
 * @see \Drupal\Component\Graph\Graph::searchAndSort()
 */
function update_resolve_dependencies($starting_updates) {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use \Drupal\Core\Update\Update::resolveDependencies() instead. See https://www.drupal.org/node/3013060', E_USER_DEPRECATED);
  /** @var \Drupal\Core\Update\Update $update */
  $update = \Drupal::service(Update::class);
  return $update->resolveDependencies($starting_updates);
}

/**
 * Returns an organized list of update functions for a set of modules.
 *
 * @param $starting_updates
 *   An array whose keys contain the names of modules and whose values contain
 *   the number of the first requested update for that module.
 *
 * @return array
 *   An array containing all the update functions that should be run for each
 *   module, including the provided starting update and all subsequent updates
 *   that are available. The keys of the array contain the module names, and
 *   each value is an ordered array of update functions, keyed by the update
 *   number.
 *
 * @deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use
 *   \Drupal\Core\Update\Update::getUpdateFunctionList() instead.
 *
 * @see https://www.drupal.org/node/3013060
 * @see \Drupal\Core\Update\Update::getUpdateFunctionList()
 * @see \Drupal\Core\Update\Update::resolveDependencies()
 */
function update_get_update_function_list($starting_updates) {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use \Drupal\Core\Update\Update::getUpdateFunctionList() instead. See https://www.drupal.org/node/3013060', E_USER_DEPRECATED);
  /** @var \Drupal\Core\Update\Update $update */
  $update = \Drupal::service(Update::class);
  return $update->getUpdateFunctionList($starting_updates);
}

/**
 * Constructs a graph which encodes the dependencies between module updates.
 *
 * This function returns an associative array which contains a "directed graph"
 * representation of the dependencies between a provided list of update
 * functions, as well as any outside update functions that they directly depend
 * on but that were not in the provided list. The vertices of the graph
 * represent the update functions themselves, and each edge represents a
 * requirement that the first update function needs to run before the second.
 * For example, consider this graph:
 *
 * system_update_8001 ---> system_update_8002 ---> system_update_8003
 *
 * Visually, this indicates that system_update_8001() must run before
 * system_update_8002(), which in turn must run before system_update_8003().
 *
 * The function takes into account standard dependencies within each module, as
 * shown above (i.e., the fact that each module's updates must run in numerical
 * order), but also finds any cross-module dependencies that are defined by
 * modules which implement hook_update_dependencies(), and builds them into the
 * graph as well.
 *
 * @param $update_functions
 *   An organized array of update functions, in the format returned by
 *   update_get_update_function_list().
 *
 * @return array
 *   A multidimensional array representing the dependency graph, suitable for
 *   passing in to Drupal\Component\Graph\Graph::searchAndSort(), but with extra
 *   information about each update function also included. Each array key
 *   contains the name of an update function, including all update functions
 *   from the provided list as well as any outside update functions which they
 *   directly depend on. Each value is an associative array containing the
 *   following keys:
 *   - 'edges': A representation of any other update functions that immediately
 *     depend on this one. See Drupal\Component\Graph\Graph::searchAndSort() for
 *     more details on the format.
 *   - 'module': The name of the module that this update function belongs to.
 *   - 'number': The number of this update function within that module.
 *
 * @deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use
 *   \Drupal\Core\Update\Update::buildDependencyGraph() instead.
 *
 * @see https://www.drupal.org/node/3013060
 * @see \Drupal\Core\Update\Update::buildDependencyGraph()
 * @see \Drupal\Component\Graph\Graph::searchAndSort()
 * @see \Drupal\Core\Update\Update::resolveDependencies()
 */
function update_build_dependency_graph($update_functions) {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use \Drupal\Core\Update\Update::buildDependencyGraph() instead. See https://www.drupal.org/node/3013060', E_USER_DEPRECATED);
  /** @var \Drupal\Core\Update\Update $update */
  $update = \Drupal::service(Update::class);
  return $update->buildDependencyGraph($update_functions);
}

/**
 * Determines if a module update is missing or unavailable.
 *
 * @param $module
 *   The name of the module.
 * @param $number
 *   The number of the update within that module.
 * @param $update_functions
 *   An organized array of update functions, in the format returned by
 *   update_get_update_function_list(). This should represent all module
 *   updates that are requested to run at the time this function is called.
 *
 * @return bool
 *   TRUE if the provided module update is not installed or is not in the
 *   provided list of updates to run; FALSE otherwise.
 *
 * @deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use
 *   \Drupal\Core\Update\Update::isMissing() instead.
 *
 * @see https://www.drupal.org/node/3013060
 * @see \Drupal\Core\Update\Update::isMissing()
 */
function update_is_missing($module, $number, $update_functions) {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use \Drupal\Core\Update\Update::isMissing() instead. See https://www.drupal.org/node/3013060', E_USER_DEPRECATED);
  /** @var \Drupal\Core\Update\Update $update */
  $update = \Drupal::service(Update::class);
  return $update->isMissing($module, $number, $update_functions);
}

/**
 * Determines if a module update has already been performed.
 *
 * @param $module
 *   The name of the module.
 * @param $number
 *   The number of the update within that module.
 *
 * @return bool
 *   TRUE if the database schema indicates that the update has already been
 *   performed; FALSE otherwise.
 *
 * @deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use
 *   \Drupal\Core\Update\Update::isAlreadyPerformed() instead.
 *
 * @see https://www.drupal.org/node/3013060
 * @see \Drupal\Core\Update\Update::isAlreadyPerformed()
 */
function update_already_performed($module, $number) {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use \Drupal\Core\Update\Update::isAlreadyPerformed() instead. See https://www.drupal.org/node/3013060', E_USER_DEPRECATED);
  /** @var \Drupal\Core\Update\Update $update */
  $update = \Drupal::service(Update::class);
  return $update->isAlreadyPerformed($module, $number);
}

/**
 * Invokes hook_update_dependencies() in all installed modules.
 *
 * This function is similar to \Drupal::moduleHandler()->invokeAll(), with the
 * main difference that it does not require that a module be enabled to invoke
 * its hook, only that it be installed. This allows the update system to
 * properly perform updates even on modules that are currently disabled.
 *
 * @return array
 *   An array of return values obtained by merging the results of the
 *   hook_update_dependencies() implementations in all installed modules.
 *
 * @deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use
 *   \Drupal\Core\Update\Update::retrieveDependencies() instead.
 *
 * @see https://www.drupal.org/node/3013060
 * @see \Drupal\Core\Update\Update::retrieveDependencies()
 * @see \Drupal\Core\Extension\ModuleHandlerInterface::invokeAll()
 * @see hook_update_dependencies()
 */
function update_retrieve_dependencies() {
  @trigger_error(__FUNCTION__ . '() is deprecated in drupal:10.2.0 and is removed from drupal:11.0.0. Use \Drupal\Core\Update\Update::retrieveDependencies() instead. See https://www.drupal.org/node/3013060', E_USER_DEPRECATED);
  /** @var \Drupal\Core\Update\Update $update */
  $update = \Drupal::service(Update::class);
  return $update->retrieveDependencies();
}
