<?php

/**
 * @file
 */

declare(strict_types=1);

/**
 * @file
 */

/**
 * Implements hook_test_hook().
 */
function hk_c_test_test_hook(): string {
  return __FUNCTION__;
}

/**
 * Implements hook_procedural_alter().
 */
function hk_c_test_procedural_alter(array &$calls): void {
  $calls[] = __FUNCTION__;
}

/**
 * Implements hook_procedural_subtype_alter().
 */
function hk_c_test_procedural_subtype_alter(array &$calls): void {
  $calls[] = __FUNCTION__;
}
