<?php

/**
 * Implements hook_procedural_alter().
 *
 * @param list<string> $calls
 *   Parameter to collect called function names.
 */
function hk_c_test_procedural_alter(array &$calls): void {
  $calls[] = __FUNCTION__;
}

/**
 * Implements hook_procedural_subtype_alter().
 *
 * @param list<string> $calls
 *   Parameter to collect called function names.
 */
function hk_c_test_procedural_subtype_alter(array &$calls): void {
  $calls[] = __FUNCTION__;
}
