<?php

/**
 * @file
 * Install, update and uninstall functions for the user module.
 */

/**
 * Implements hook_schema().
 */
function user_schema() {
  $schema['users_data'] = [
    'description' => 'Stores module data as key/value pairs per user.',
    'fields' => [
      'uid' => [
        'description' => 'The {users}.uid this record affects.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ],
      'module' => [
        'description' => 'The name of the module declaring the variable.',
        'type' => 'varchar_ascii',
        'length' => DRUPAL_EXTENSION_NAME_MAX_LENGTH,
        'not null' => TRUE,
        'default' => '',
      ],
      'name' => [
        'description' => 'The identifier of the data.',
        'type' => 'varchar_ascii',
        'length' => 128,
        'not null' => TRUE,
        'default' => '',
      ],
      'value' => [
        'description' => 'The value.',
        'type' => 'blob',
        'not null' => FALSE,
        'size' => 'big',
      ],
      'serialized' => [
        'description' => 'Whether value is serialized.',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'default' => 0,
      ],
    ],
    'primary key' => ['uid', 'module', 'name'],
    'indexes' => [
      'module' => ['module'],
      'name' => ['name'],
    ],
    'foreign keys' => [
      'data_user' => [
        'table' => 'users',
        'columns' => [
          'uid' => 'uid',
        ],
      ],
    ],
  ];

  return $schema;
}

/**
 * Implements hook_install().
 */
function user_install() {
  $storage = \Drupal::entityTypeManager()->getStorage('user');
  // Insert a row for the anonymous user.
  $storage
    ->create([
      'uid' => 0,
      'status' => 0,
      'name' => '',
    ])
    ->save();

  // We need some placeholders here as name and mail are unique.
  // This will be changed by the settings form in the installer.
  $storage
    ->create([
      'uid' => 1,
      'name' => 'placeholder-for-uid-1',
      'mail' => 'placeholder-for-uid-1',
      'status' => TRUE,
    ])
    ->save();
}

/**
 * Implements hook_update_last_removed().
 */
function user_update_last_removed() {
  return 9301;
}

/**
 * Update user 'login' and 'access' fields.
 */
function user_update_10100(array &$sandbox): string {
  $fields = ['access', 'login'];
  $storage = \Drupal::entityTypeManager()->getStorage('user');
  $key_value = \Drupal::keyValue('user.timestamp');

  if (!isset($sandbox['last_uid'])) {
    $sandbox['uids'] = array_values(
      $storage->getQuery()
        ->condition('uid', 0, '>')
        ->accessCheck(FALSE)
        ->execute()
    );
    $sandbox['processed'] = 0;
    $sandbox['total'] = count($sandbox['uids']);
  }

  $uids = array_splice($sandbox['uids'], 0, 50);
  foreach ($storage->loadMultiple($uids) as $uid => $account) {
    foreach ($fields as $field) {
      $key_value->set("$uid:$field", $account->get($field)->value);
    }
  }
  $sandbox['processed'] += count($uids);

  $sandbox['#finished'] = $sandbox['processed'] / $sandbox['total'];
  if ($sandbox['#finished']) {
    // Uninstall field storages.
    $manager = \Drupal::entityDefinitionUpdateManager();
    foreach ($fields as $field) {
      $definition = $manager->getFieldStorageDefinition($field, 'user');
      $manager->uninstallFieldStorageDefinition($definition);
    }
  }

  return t('Processed @current out of @total users', [
    '@current' => $sandbox['processed'],
    '@total' => $sandbox['total'],
  ]);
}
