<?php

/**
 * @file
 * Enables the user registration and login system.
 */

use Drupal\Component\Utility\Unicode;
use Drupal\Core\Access\AccessibleInterface;
use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Render\Element;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Session\AnonymousUserSession;
use Drupal\Core\Url;
use Drupal\filter\FilterFormatInterface;
use Drupal\user\Hook\UserHooks;
use Drupal\user\RoleInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_help().
 */
#[LegacyHook]
function user_help($route_name, RouteMatchInterface $route_match) {
  \Drupal::service(UserHooks::CLASS)->userHelp($route_name, $route_match);
}

/**
 * Implements hook_theme().
 */
#[LegacyHook]
function user_theme() {
  \Drupal::service(UserHooks::CLASS)->userTheme();
}

/**
 * Implements hook_js_settings_alter().
 */
#[LegacyHook]
function user_js_settings_alter(&$settings, AttachedAssetsInterface $assets) {
  \Drupal::service(UserHooks::CLASS)->userJsSettingsAlter($settings, $assets);
}

/**
 * Returns whether this site supports the default user picture feature.
 *
 * This approach preserves compatibility with node/comment templates. Alternate
 * user picture implementations (e.g., Gravatar) should provide their own
 * add/edit/delete forms and populate the 'picture' variable during the
 * preprocess stage.
 */
#[LegacyHook]
function user_picture_enabled() {
  \Drupal::service(UserHooks::CLASS)->userPictureEnabled();
}

/**
 * Implements hook_entity_extra_field_info().
 */
#[LegacyHook]
function user_entity_extra_field_info() {
  \Drupal::service(UserHooks::CLASS)->userEntityExtraFieldInfo();
}

/**
 * Implements hook_ENTITY_TYPE_presave() for user entities.
 *
 * @todo https://www.drupal.org/project/drupal/issues/3112704 Move to
 *   \Drupal\user\Entity\User::preSave().
 */
#[LegacyHook]
function user_user_presave(UserInterface $account) {
  \Drupal::service(UserHooks::CLASS)->userUserPresave($account);
}

/**
 * Fetches a user object by email address.
 *
 * @param string $mail
 *   String with the account's email address.
 *
 * @return \Drupal\user\UserInterface|false
 *   A fully-loaded $user object upon successful user load or FALSE if user
 *   cannot be loaded.
 *
 * @see \Drupal\user\Entity\User::loadMultiple()
 */
#[LegacyHook]
function user_load_by_mail($mail) {
  \Drupal::service(UserHooks::CLASS)->userLoadByMail($mail);
}

/**
 * Fetches a user object by account name.
 *
 * @param string $name
 *   String with the account's user name.
 *
 * @return \Drupal\user\UserInterface|false
 *   A fully-loaded $user object upon successful user load or FALSE if user
 *   cannot be loaded.
 *
 * @see \Drupal\user\Entity\User::loadMultiple()
 */
#[LegacyHook]
function user_load_by_name($name) {
  \Drupal::service(UserHooks::CLASS)->userLoadByName($name);
}

/**
 * Verify the syntax of the given name.
 *
 * @param string $name
 *   The user name to validate.
 *
 * @return string|null
 *   A translated violation message if the name is invalid or NULL if the name
 *   is valid.
 *
 * @deprecated in drupal:10.3.0 and is removed from drupal:12.0.0. Use
 *   \Drupal\user\UserNameValidator::validateName() instead.
 *
 * @see https://www.drupal.org/node/3431205
 */
#[LegacyHook]
function user_validate_name($name) {
  \Drupal::service(UserHooks::CLASS)->userValidateName($name);
}

/**
 * Checks for usernames blocked by user administration.
 *
 * @param string $name
 *   A string containing a name of the user.
 *
 * @return bool
 *   TRUE if the user is blocked, FALSE otherwise.
 *
 * @deprecated in drupal:11.0.0 and is removed from drupal:12.0.0. Use
 * Drupal\user\UserInterface::isBlocked() instead.
 * @see https://www.drupal.org/node/3411040
 */
#[LegacyHook]
function user_is_blocked($name) {
  \Drupal::service(UserHooks::CLASS)->userIsBlocked($name);
}

/**
 * Implements hook_ENTITY_TYPE_view() for user entities.
 */
#[LegacyHook]
function user_user_view(array &$build, UserInterface $account, EntityViewDisplayInterface $display) {
  \Drupal::service(UserHooks::CLASS)->userUserView($build, $account, $display);
}

/**
 * Implements hook_ENTITY_TYPE_view_alter() for user entities.
 *
 * This function adds a default alt tag to the user_picture field to maintain
 * accessibility.
 */
#[LegacyHook]
function user_user_view_alter(array &$build, UserInterface $account, EntityViewDisplayInterface $display) {
  \Drupal::service(UserHooks::CLASS)->userUserViewAlter($build, $account, $display);
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
#[LegacyHook]
function user_preprocess_block(&$variables) {
  \Drupal::service(UserHooks::CLASS)->userPreprocessBlock($variables);
}

/**
 * Implements hook_template_preprocess_default_variables_alter().
 *
 * @see user_user_login()
 * @see user_user_logout()
 */
#[LegacyHook]
function user_template_preprocess_default_variables_alter(&$variables) {
  \Drupal::service(UserHooks::CLASS)->userTemplatePreprocessDefaultVariablesAlter($variables);
}

/**
 * Prepares variables for username templates.
 *
 * Default template: username.html.twig.
 *
 * Modules that make any changes to variables like 'name' or 'extra' must ensure
 * that the final string is safe.
 *
 * @param array $variables
 *   An associative array containing:
 *   - account: The user account (\Drupal\Core\Session\AccountInterface).
 */
function template_preprocess_username(&$variables) {
  $account = $variables['account'] ?: new AnonymousUserSession();

  $variables['extra'] = '';
  $variables['uid'] = $account->id();
  if (empty($variables['uid'])) {
    if (theme_get_setting('features.comment_user_verification')) {
      $variables['extra'] = ' (' . t('not verified') . ')';
    }
  }

  // Set the name to a formatted name that is safe for printing and
  // that won't break tables by being too long. Keep an un-shortened,
  // unsanitized version, in case other preprocess functions want to implement
  // their own shortening logic or add markup. If they do so, they must ensure
  // that $variables['name'] is safe for printing.
  $name = $account->getDisplayName();
  $variables['name_raw'] = $account->getAccountName();
  if (mb_strlen($name) > 20) {
    $name = Unicode::truncate($name, 15, FALSE, TRUE);
    $variables['truncated'] = TRUE;
  }
  else {
    $variables['truncated'] = FALSE;
  }
  $variables['name'] = $name;
  if ($account instanceof AccessibleInterface) {
    $variables['profile_access'] = $account->access('view');
  }
  else {
    $variables['profile_access'] = \Drupal::currentUser()->hasPermission('access user profiles');
  }

  $external = FALSE;
  // Populate link path and attributes if appropriate.
  if ($variables['uid'] && $variables['profile_access']) {
    // We are linking to a local user.
    $variables['attributes']['title'] = t('View user profile.');
    $variables['link_path'] = 'user/' . $variables['uid'];
  }
  elseif (!empty($account->homepage)) {
    // Like the 'class' attribute, the 'rel' attribute can hold a
    // space-separated set of values, so initialize it as an array to make it
    // easier for other preprocess functions to append to it.
    $variables['attributes']['rel'] = 'nofollow';
    $variables['link_path'] = $account->homepage;
    $variables['homepage'] = $account->homepage;
    $external = TRUE;
  }
  // We have a link path, so we should generate a URL.
  if (isset($variables['link_path'])) {
    if ($external) {
      $variables['attributes']['href'] = Url::fromUri($variables['link_path'], $variables['link_options'])
        ->toString();
    }
    else {
      $variables['attributes']['href'] = Url::fromRoute('entity.user.canonical', [
        'user' => $variables['uid'],
      ])->toString();
    }
  }
}

/**
 * Finalizes the login process and logs in a user.
 *
 * The function logs in the user, records a watchdog message about the new
 * session, saves the login timestamp, calls hook_user_login(), and generates a
 * new session.
 *
 * The current user is replaced with the passed in account.
 *
 * @param \Drupal\user\UserInterface $account
 *   The account to log in.
 *
 * @see hook_user_login()
 * @see \Drupal\user\Authentication\Provider\Cookie
 */
#[LegacyHook]
function user_login_finalize(UserInterface $account) {
  \Drupal::service(UserHooks::CLASS)->userLoginFinalize($account);
}

/**
 * Implements hook_user_login().
 */
#[LegacyHook]
function user_user_login(UserInterface $account) {
  \Drupal::service(UserHooks::CLASS)->userUserLogin($account);
}

/**
 * Implements hook_user_logout().
 */
#[LegacyHook]
function user_user_logout(AccountInterface $account) {
  \Drupal::service(UserHooks::CLASS)->userUserLogout($account);
}

/**
 * Generates a unique URL for a user to log in and reset their password.
 *
 * @param \Drupal\user\UserInterface $account
 *   An object containing the user account.
 * @param array $options
 *   (optional) A keyed array of settings. Supported options are:
 *   - langcode: A language code to be used when generating locale-sensitive
 *    URLs. If langcode is NULL the users preferred language is used.
 *
 * @return string
 *   A unique URL that provides a one-time log in for the user, from which
 *   they can change their password.
 */
#[LegacyHook]
function user_pass_reset_url($account, $options = []) {
  \Drupal::service(UserHooks::CLASS)->userPassResetUrl($account, $options);
}

/**
 * Generates a URL to confirm an account cancellation request.
 *
 * @param \Drupal\user\UserInterface $account
 *   The user account object.
 * @param array $options
 *   (optional) A keyed array of settings. Supported options are:
 *   - langcode: A language code to be used when generating locale-sensitive
 *     URLs. If langcode is NULL the users preferred language is used.
 *
 * @return string
 *   A unique URL that may be used to confirm the cancellation of the user
 *   account.
 *
 * @see user_mail_tokens()
 * @see \Drupal\user\Controller\UserController::confirmCancel()
 */
#[LegacyHook]
function user_cancel_url(UserInterface $account, $options = []) {
  \Drupal::service(UserHooks::CLASS)->userCancelUrl($account, $options);
}

/**
 * Creates a unique hash value for use in time-dependent per-user URLs.
 *
 * This hash is normally used to build a unique and secure URL that is sent to
 * the user by email for purposes such as resetting the user's password. In
 * order to validate the URL, the same hash can be generated again, from the
 * same information, and compared to the hash value from the URL. The hash
 * contains the time stamp, the user's last login time, the numeric user ID,
 * and the user's email address.
 * For a usage example, see user_cancel_url() and
 * \Drupal\user\Controller\UserController::confirmCancel().
 *
 * @param \Drupal\user\UserInterface $account
 *   An object containing the user account.
 * @param int $timestamp
 *   A UNIX timestamp, typically \Drupal::time()->getRequestTime().
 *
 * @return string
 *   A string that is safe for use in URLs and SQL statements.
 */
#[LegacyHook]
function user_pass_rehash(UserInterface $account, $timestamp) {
  \Drupal::service(UserHooks::CLASS)->userPassRehash($account, $timestamp);
}

/**
 * Cancel a user account.
 *
 * Since the user cancellation process needs to be run in a batch, either
 * Form API will invoke it, or batch_process() needs to be invoked after calling
 * this function and should define the path to redirect to.
 *
 * @param array $edit
 *   An array of submitted form values.
 * @param int $uid
 *   The user ID of the user account to cancel.
 * @param string $method
 *   The account cancellation method to use.
 *
 * @see _user_cancel()
 */
#[LegacyHook]
function user_cancel($edit, $uid, $method) {
  \Drupal::service(UserHooks::CLASS)->userCancel($edit, $uid, $method);
}

/**
 * Implements callback_batch_operation().
 *
 * Last step for cancelling a user account.
 *
 * Since batch and session API require a valid user account, the actual
 * cancellation of a user account needs to happen last.
 *
 * @param array $edit
 *   An array of submitted form values.
 * @param \Drupal\user\UserInterface $account
 *   The user ID of the user account to cancel.
 * @param string $method
 *   The account cancellation method to use.
 *
 * @see user_cancel()
 */
function _user_cancel($edit, $account, $method) {
  $logger = \Drupal::logger('user');

  switch ($method) {
    case 'user_cancel_block':
    case 'user_cancel_block_unpublish':
    default:
      // Send account blocked notification if option was checked.
      if (!empty($edit['user_cancel_notify'])) {
        _user_mail_notify('status_blocked', $account);
      }
      $account->block();
      $account->save();
      \Drupal::messenger()->addStatus(t('Account %name has been disabled.', ['%name' => $account->getDisplayName()]));
      $logger->notice('Blocked user: %name %email.', ['%name' => $account->getAccountName(), '%email' => '<' . $account->getEmail() . '>']);
      break;

    case 'user_cancel_reassign':
    case 'user_cancel_delete':
      // Send account canceled notification if option was checked.
      if (!empty($edit['user_cancel_notify'])) {
        _user_mail_notify('status_canceled', $account);
      }
      $account->delete();
      \Drupal::messenger()->addStatus(t('Account %name has been deleted.', ['%name' => $account->getDisplayName()]));
      $logger->notice('Deleted user: %name %email.', ['%name' => $account->getAccountName(), '%email' => '<' . $account->getEmail() . '>']);
      break;
  }

  // After cancelling account, ensure that user is logged out. We can't destroy
  // their session though, as we might have information in it, and we can't
  // regenerate it because batch API uses the session ID, we will regenerate it
  // in _user_cancel_session_regenerate().
  if ($account->id() == \Drupal::currentUser()->id()) {
    \Drupal::currentUser()->setAccount(new AnonymousUserSession());
  }
}

/**
 * Implements callback_batch_finished().
 *
 * Finished batch processing callback for cancelling a user account.
 *
 * @see user_cancel()
 */
function _user_cancel_session_regenerate() {
  // Regenerate the users session instead of calling session_destroy() as we
  // want to preserve any messages that might have been set.
  \Drupal::service('session')->migrate();
}

/**
 * Helper function to return available account cancellation methods.
 *
 * See documentation of hook_user_cancel_methods_alter().
 *
 * @return array
 *   An array containing all account cancellation methods as form elements.
 *
 * @see hook_user_cancel_methods_alter()
 * @see user_admin_settings()
 */
#[LegacyHook]
function user_cancel_methods() {
  \Drupal::service(UserHooks::CLASS)->userCancelMethods();
}

/**
 * Implements hook_mail().
 */
#[LegacyHook]
function user_mail($key, &$message, $params) {
  \Drupal::service(UserHooks::CLASS)->userMail($key, $message, $params);
}

/**
 * Token callback to add unsafe tokens for user mails.
 *
 * This function is used by \Drupal\Core\Utility\Token::replace() to set up
 * some additional tokens that can be used in email messages generated by
 * user_mail().
 *
 * @param array $replacements
 *   An associative array variable containing mappings from token names to
 *   values (for use with strtr()).
 * @param array $data
 *   An associative array of token replacement values. If the 'user' element
 *   exists, it must contain a user account object with the following
 *   properties:
 *   - login: The UNIX timestamp of the user's last login.
 *   - pass: The hashed account login password.
 * @param array $options
 *   A keyed array of settings and flags to control the token replacement
 *   process. See \Drupal\Core\Utility\Token::replace().
 */
#[LegacyHook]
function user_mail_tokens(&$replacements, $data, $options) {
  \Drupal::service(UserHooks::CLASS)->userMailTokens($replacements, $data, $options);
}

/**
 * Implements hook_ENTITY_TYPE_insert() for user_role entities.
 */
#[LegacyHook]
function user_user_role_insert(RoleInterface $role) {
  \Drupal::service(UserHooks::CLASS)->userUserRoleInsert($role);
}

/**
 * Implements hook_ENTITY_TYPE_delete() for user_role entities.
 */
#[LegacyHook]
function user_user_role_delete(RoleInterface $role) {
  \Drupal::service(UserHooks::CLASS)->userUserRoleDelete($role);
}

/**
 * Change permissions for a user role.
 *
 * This function may be used to grant and revoke multiple permissions at once.
 * For example, when a form exposes checkboxes to configure permissions for a
 * role, the form submit handler may directly pass the submitted values for the
 * checkboxes form element to this function.
 *
 * @param mixed $rid
 *   The ID of a user role to alter.
 * @param array $permissions
 *   (optional) An associative array, where the key holds the permission name
 *   and the value determines whether to grant or revoke that permission. Any
 *   value that evaluates to TRUE will cause the permission to be granted.
 *   Any value that evaluates to FALSE will cause the permission to be
 *   revoked.
 *   @code
 *     [
 *       'administer nodes' => 0,                // Revoke 'administer nodes'
 *       'administer blocks' => FALSE,           // Revoke 'administer blocks'
 *       'access user profiles' => 1,            // Grant 'access user profiles'
 *       'access content' => TRUE,               // Grant 'access content'
 *       'access comments' => 'access comments', // Grant 'access comments'
 *     ]
 *   @endcode
 *   Existing permissions are not changed, unless specified in $permissions.
 *
 * @see user_role_grant_permissions()
 * @see user_role_revoke_permissions()
 */
#[LegacyHook]
function user_role_change_permissions($rid, array $permissions = []) {
  \Drupal::service(UserHooks::CLASS)->userRoleChangePermissions($rid, $permissions);
}

/**
 * Grant permissions to a user role.
 *
 * @param mixed $rid
 *   The ID of a user role to alter.
 * @param array $permissions
 *   (optional) A list of permission names to grant.
 *
 * @see user_role_change_permissions()
 * @see user_role_revoke_permissions()
 */
#[LegacyHook]
function user_role_grant_permissions($rid, array $permissions = []) {
  \Drupal::service(UserHooks::CLASS)->userRoleGrantPermissions($rid, $permissions);
}

/**
 * Revoke permissions from a user role.
 *
 * @param mixed $rid
 *   The ID of a user role to alter.
 * @param array $permissions
 *   (optional) A list of permission names to revoke.
 *
 * @see user_role_change_permissions()
 * @see user_role_grant_permissions()
 */
#[LegacyHook]
function user_role_revoke_permissions($rid, array $permissions = []) {
  \Drupal::service(UserHooks::CLASS)->userRoleRevokePermissions($rid, $permissions);
}

/**
 * Creates and sends a notification email following a change to a user account.
 *
 * @param string $op
 *   The operation being performed on the account. Possible values:
 *   - 'register_admin_created': Welcome message for user created by the admin.
 *   - 'register_no_approval_required': Welcome message when user
 *     self-registers.
 *   - 'register_pending_approval': Welcome message, user pending admin
 *     approval.
 *   - 'password_reset': Password recovery request.
 *   - 'status_activated': Account activated.
 *   - 'status_blocked': Account blocked.
 *   - 'cancel_confirm': Account cancellation request.
 *   - 'status_canceled': Account canceled.
 * @param \Drupal\Core\Session\AccountInterface $account
 *   The user object of the account being notified. Must contain at
 *   least the fields 'uid', 'name', and 'mail'.
 *
 * @return array
 *   An array containing various information about the message.
 *   See \Drupal\Core\Mail\MailManagerInterface::mail() for details.
 *
 * @see user_mail_tokens()
 */
function _user_mail_notify($op, AccountInterface $account) {

  if (\Drupal::config('user.settings')->get('notify.' . $op)) {
    $params['account'] = $account;
    // Get the custom site notification email to use as the from email address
    // if it has been set.
    $site_mail = \Drupal::config('system.site')->get('mail_notification');
    // If the custom site notification email has not been set, we use the site
    // default for this.
    if (empty($site_mail)) {
      $site_mail = \Drupal::config('system.site')->get('mail');
    }
    if (empty($site_mail)) {
      $site_mail = ini_get('sendmail_from');
    }
    $mail = \Drupal::service('plugin.manager.mail')->mail('user', $op, $account->getEmail(), $account->getPreferredLangcode(), $params, $site_mail);
    if ($op == 'register_pending_approval') {
      // If a user registered requiring admin approval, notify the admin, too.
      // We use the site default language for this.
      \Drupal::service('plugin.manager.mail')->mail('user', 'register_pending_approval_admin', $site_mail, \Drupal::languageManager()->getDefaultLanguage()->getId(), $params);
    }
  }
  return empty($mail) ? NULL : $mail['result'];
}

/**
 * Implements hook_element_info_alter().
 */
#[LegacyHook]
function user_element_info_alter(array &$types) {
  \Drupal::service(UserHooks::CLASS)->userElementInfoAlter($types);
}

/**
 * Form element process handler for client-side password validation.
 *
 * This #process handler is automatically invoked for 'password_confirm' form
 * elements to add the JavaScript and string translations for dynamic password
 * validation.
 */
#[LegacyHook]
function user_form_process_password_confirm($element) {
  \Drupal::service(UserHooks::CLASS)->userFormProcessPasswordConfirm($element);
}

/**
 * Implements hook_modules_uninstalled().
 */
#[LegacyHook]
function user_modules_uninstalled($modules) {
  \Drupal::service(UserHooks::CLASS)->userModulesUninstalled($modules);
}

/**
 * Saves visitor information as a cookie so it can be reused.
 *
 * @param array $values
 *   An array of key/value pairs to be saved into a cookie.
 */
#[LegacyHook]
function user_cookie_save(array $values) {
  \Drupal::service(UserHooks::CLASS)->userCookieSave($values);
}

/**
 * Delete a visitor information cookie.
 *
 * @param string $cookie_name
 *   A cookie name such as 'homepage'.
 */
#[LegacyHook]
function user_cookie_delete($cookie_name) {
  \Drupal::service(UserHooks::CLASS)->userCookieDelete($cookie_name);
}

/**
 * Implements hook_toolbar().
 */
#[LegacyHook]
function user_toolbar() {
  \Drupal::service(UserHooks::CLASS)->userToolbar();
}

/**
 * Logs the current user out.
 */
#[LegacyHook]
function user_logout() {
  \Drupal::service(UserHooks::CLASS)->userLogout();
}

/**
 * Prepares variables for user templates.
 *
 * Default template: user.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *     fields attached to the user. Properties used:
 *     - #user: A \Drupal\user\Entity\User object. The user account of the
 *       profile being viewed.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_user(&$variables) {
  $variables['user'] = $variables['elements']['#user'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for \Drupal\system\Form\RegionalForm.
 */
#[LegacyHook]
function user_form_system_regional_settings_alter(&$form, FormStateInterface $form_state) {
  \Drupal::service(UserHooks::CLASS)->userFormSystemRegionalSettingsAlter($form, $form_state);
}

/**
 * Additional submit handler for \Drupal\system\Form\RegionalForm.
 */
#[LegacyHook]
function user_form_system_regional_settings_submit($form, FormStateInterface $form_state) {
  \Drupal::service(UserHooks::CLASS)->userFormSystemRegionalSettingsSubmit($form, $form_state);
}

/**
 * Implements hook_filter_format_disable().
 */
#[LegacyHook]
function user_filter_format_disable(FilterFormatInterface $filter_format) {
  \Drupal::service(UserHooks::CLASS)->userFilterFormatDisable($filter_format);
}

/**
 * Implements hook_entity_operation().
 */
#[LegacyHook]
function user_entity_operation(EntityInterface $entity) {
  \Drupal::service(UserHooks::CLASS)->userEntityOperation($entity);
}
