<?php

/**
 * @file
 * Helper module for the link generation tests.
 */

use Drupal\Core\Cache\CacheableMetadata;

/**
 * Implements hook_link_alter().
 */
function link_generation_test_link_alter(&$variables) {
  if (\Drupal::state()->get('link_generation_test_link_alter', FALSE)) {
    // Add a text to the end of links.
    if (\Drupal::state()->get('link_generation_test_link_alter_safe', FALSE)) {
      $variables['text'] = t('@text <strong>Test!</strong>', ['@text' => $variables['text']]);
    }
    else {
      $variables['text'] .= ' <strong>Test!</strong>';
    }

    // Add cacheable metadata.
    $variables['cacheable_dependency'] = (new CacheableMetadata())
      ->addCacheContexts(['url', 'languages'])
      ->addCacheTags(['foo', 'bar'])
      ->mergeCacheMaxAge(3600);
  }
}
