<?php

/**
 * @file
 * Helper module for the plugin tests.
 */

use Drupal\Component\Plugin\PluginInspectionInterface;
use Drupal\Core\Form\SubformStateInterface;
use Drupal\plugin_test\Plugin\plugin_test\fruit\Apple;

/**
 * Implements hook_test_plugin_info().
 */
function plugin_test_test_plugin_info() {
  return [
    'apple' => [
      'id' => 'apple',
      'class' => Apple::class,
    ],
  ];
}

/**
 * Implements hook_plugin_test_alter().
 */
function plugin_test_plugin_test_alter(&$definitions) {
  foreach ($definitions as &$definition) {
    $definition['altered'] = TRUE;
  }
  $definitions['user_login']['altered_single'] = TRUE;
}

/**
 * Implements hook_plugin_subform_alter().
 */
function plugin_test_plugin_subform_alter(array &$form, SubformStateInterface $form_state, PluginInspectionInterface $plugin) {
  $form['#' . __FUNCTION__] = TRUE;
}
