#!/usr/bin/env php
<?php

/**
 * @file
 * Provides CLI commands for Drupal.
 */

declare(strict_types = 1);

use Composer\Autoload\ClassLoader;
use Drupal\Core\Command\DrupalApplication;
use Drupal\Core\DrupalKernel;
use Drupal\Core\Site\Settings;
use Symfony\Component\Console\Application;
use Symfony\Component\HttpFoundation\Request;

// We must check $_composer_autoload_path before we use it, because legacy
// callers that invoke this script directly, rather than using vendor/bin/drupal,
// won't get it.
// https://getcomposer.org/doc/articles/vendor-binaries.md#finding-the-composer-autoloader-from-a-binary
$autoload_path = $GLOBALS['_composer_autoload_path'] ?? __DIR__ . '/../../vendor/autoload.php';
require_once dirname($autoload_path) . '/autoload_runtime.php';

if ('cli' !== \PHP_SAPI) {
  throw new Exception('This script must be run from the command line.');
}

// Utilizes the https://symfony.com/doc/current/components/runtime.html component
// to encapsulate the application cleanly.
return static function (array $context): Application {
  $loaders = ClassLoader::getRegisteredLoaders();
  $classLoader = reset($loaders);
  $app = new DrupalApplication($classLoader, $context);
  return $app;
};
