#!/usr/bin/env php
<?php

/**
 * @file
 * Provides CLI commands for Drupal.
 */

use Drupal\Core\Command\DrupalApplication;

if (PHP_SAPI !== 'cli') {
  return;
}

$classloader = require_once __DIR__ . '/../../autoload.php';

$application = new DrupalApplication($classloader);

$application->run();
