name: 'Article comments'
description: 'Provides commenting on article content.'
type: 'Content field'
recipes:
  - article_content_type
  - comment_base
config:
  actions:
    field.field.node.article.comment:
      createIfNotExists:
        id: node.article.comment
        field_name: comment
        entity_type: node
        bundle: article
        label: Comments
        description: ''
        required: false
        translatable: true
        default_value:
          -
            status: 2
            cid: 0
            last_comment_timestamp: 0
            last_comment_name: null
            last_comment_uid: 0
            comment_count: 0
        default_value_callback: ''
        settings:
          default_mode: 1
          per_page: 50
          anonymous: 0
          form_location: true
          preview: 1
        field_type: comment
    core.entity_form_display.node.article.default:
      setComponent:
        name: comment
        options:
          type: comment_default
          weight: 20
          region: content
          settings: {}
          third_party_settings: {}
    core.entity_view_display.node.article.default:
      setComponent:
        name: comment
        options:
          type: comment_default
          label: above
          settings:
            view_mode: default
            pager_id: 0
          third_party_settings: {  }
          weight: 110
          region: content
