<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;

/**
 * The name of the query parameter for image derivative tokens.
 */
define('IMAGE_DERIVATIVE_TOKEN', 'itok');

/**
 * Clears cached versions of a specific file in all styles.
 *
 * @param $path
 *   The Drupal file path to the original image.
 */
function image_path_flush($path) {
  $styles = ImageStyle::loadMultiple();
  foreach ($styles as $style) {
    $style->flush($path);
  }
}

/**
 * Gets an array of image styles suitable for using as select list options.
 *
 * @param $include_empty
 *   If TRUE a '- None -' option will be inserted in the options array.
 *
 * @return string[]
 *   Array of image styles both key and value are set to style name.
 */
function image_style_options($include_empty = TRUE) {
  $styles = ImageStyle::loadMultiple();
  $options = [];
  if ($include_empty && !empty($styles)) {
    $options[''] = t('- None -');
  }
  foreach ($styles as $name => $style) {
    $options[$name] = $style->label();
  }

  if (empty($options)) {
    $options[''] = t('No defined styles');
  }
  return $options;
}

/**
 * Prepares variables for image style templates.
 *
 * Default template: image-style.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - width: The width of the image.
 *   - height: The height of the image.
 *   - style_name: The name of the image style to be applied.
 *   - uri: URI of the source image before styling.
 *   - alt: The alternative text for text-based browsers. HTML 4 and XHTML 1.0
 *     always require an alt attribute. The HTML 5 draft allows the alt
 *     attribute to be omitted in some cases. Therefore, this variable defaults
 *     to an empty string, but can be set to NULL for the attribute to be
 *     omitted. Usually, neither omission nor an empty string satisfies
 *     accessibility requirements, so it is strongly encouraged for code using
 *     '#theme' => 'image_style' to pass a meaningful value for this variable.
 *     - https://www.w3.org/TR/REC-html40/struct/objects.html#h-13.8
 *     - https://www.w3.org/TR/xhtml1/dtds.html
 *     - http://dev.w3.org/html5/spec/Overview.html#alt
 *   - title: The title text is displayed when the image is hovered in some
 *     popular browsers.
 *   - attributes: Associative array of additional attributes to be placed in
 *     the img tag.
 */
function template_preprocess_image_style(&$variables): void {
  $style = ImageStyle::load($variables['style_name']);

  // Determine the dimensions of the styled image.
  $dimensions = [
    'width' => $variables['width'],
    'height' => $variables['height'],
  ];

  $style->transformDimensions($dimensions, $variables['uri']);

  $variables['image'] = [
    '#theme' => 'image',
    '#width' => $dimensions['width'],
    '#height' => $dimensions['height'],
    '#attributes' => $variables['attributes'],
    '#style_name' => $variables['style_name'],
  ];

  // If the current image toolkit supports this file type, prepare the URI for
  // the derivative image. If not, just use the original image resized to the
  // dimensions specified by the style.
  if ($style->supportsUri($variables['uri'])) {
    $variables['image']['#uri'] = $style->buildUrl($variables['uri']);
  }
  else {
    $variables['image']['#uri'] = $variables['uri'];
    // Don't render the image by default, but allow other preprocess functions
    // to override that if they need to.
    $variables['image']['#access'] = FALSE;

    // Inform the site builders why their image didn't work.
    \Drupal::logger('image')->warning('Could not apply @style image style to @uri because the style does not support it.', [
      '@style' => $style->label(),
      '@uri' => $variables['uri'],
    ]);
  }

  if (\array_key_exists('alt', $variables)) {
    $variables['image']['#alt'] = $variables['alt'];
  }
  if (\array_key_exists('title', $variables)) {
    $variables['image']['#title'] = $variables['title'];
  }

}

/**
 * Returns the offset in pixels from the anchor.
 *
 * @param string $anchor
 *   The anchor ('top', 'left', 'bottom', 'right', 'center').
 * @param int $current_size
 *   The current size, in pixels.
 * @param int $new_size
 *   The new size, in pixels.
 *
 * @return int|string
 *   The offset from the anchor, in pixels, or the anchor itself, if its value
 *   isn't one of the accepted values.
 *
 * @deprecated in drupal:11.1.0 and is removed from drupal:12.0.0. Use
 *   \Drupal\Component\Utility\Image::getKeywordOffset() instead.
 *
 * @see https://www.drupal.org/node/3268441
 */
function image_filter_keyword($anchor, $current_size, $new_size) {
  @trigger_error('image_filter_keyword() is deprecated in drupal:11.1.0 and is removed from drupal:12.0.0. Use \Drupal\Component\Utility\Image::getKeywordOffset() instead. See https://www.drupal.org/node/3268441', E_USER_DEPRECATED);
  switch ($anchor) {
    case 'top':
    case 'left':
      return 0;

    case 'bottom':
    case 'right':
      return $current_size - $new_size;

    case 'center':
      return $current_size / 2 - $new_size / 2;

    default:
      return $anchor;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alters the image dialog form for text editor to allow the user to select an
 * image style.
 *
 * @see \Drupal\editor\Form\EditorImageDialog::buildForm()
 */
function image_form_editor_image_dialog_alter(array &$form, FormStateInterface $form_state): void {
  /** @var \Drupal\editor\EditorInterface $editor */
  $editor = $form_state->getBuildInfo()['args'][0];

  /** @var \Drupal\image\Plugin\Filter\FilterImageStyle $filter */
  $filter = $editor->getFilterFormat()->filters('filter_image_style');

  if (!$filter->status) {
    // The 'filter_image_style' filter is not enabled for this text format.
    return;
  }

  // Get the image (<img>) that is being edited on the client.
  $image_element = $form_state->get('image_element');

  // Add a select element to choose an image style.
  $form['image_style']['selection'] = [
    '#title' => t('Use image style'),
    '#type' => 'select',
    '#default_value' => isset($image_element['data-image-style']) ? $image_element['data-image-style'] : '',
    '#options' => $filter->getAllowedImageStylesAsOptions(),
    '#empty_value' => '',
    // Set #parents in order to make the selected value an image attribute,
    // named 'data-image-style', in the same way as other image attributes, such as
    // 'data-align' or 'hasCaption', are added to the form.
    // @see \Drupal\editor\Form\EditorImageDialog::buildForm()
    '#parents' => ['attributes', 'data-image-style'],
  ];

  $form['actions']['save_modal']['#validate'][] = 'image_form_editor_image_dialog_validate';
}

/**
 * Form validation handler for EditorImageDialog.
 *
 * Ensures the image shown in the text editor matches the chosen image style.
 *
 * @param array $form
 *   The form render array
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object.
 *
 * @see image_form_editor_image_dialog_alter()
 * @see \Drupal\editor\Form\EditorImageDialog::buildForm()
 * @see \Drupal\editor\Form\EditorImageDialog::validateForm()
 */
function image_form_editor_image_dialog_validate(array &$form, FormStateInterface $form_state): void {
  // There is no file yet to apply an image style so no need to validate.
  if (empty($form_state->getValue('fid')[0])) {
    return;
  }

  $attributes = $form_state->getValue('attributes');
  if (!$attributes) {
    return;
  }

  // A previous image style may have been removed from the image ("-None-"
  // selected), or globally deleted.
  // So we will check later that this variable is defined.
  $image_style = ImageStyle::load($attributes['data-image-style']);

  $uri = File::load($form_state->getValue('fid')[0])->getFileUri();

  // Set the 'src' attribute to the image style URL. FilterImageStyle will
  // look at the 'data-editor-file-uuid' attribute, not the 'src' attribute
  // to render the appropriate output.
  $attributes['src'] = $image_style ? file_url_transform_relative($image_style->buildUrl($uri)) : '';

  /** @var \Drupal\Core\Image\ImageInterface $image */
  $image = \Drupal::service('image.factory')->get($uri);

  if ($image->isValid()) {
    // Get the original width and height of the image.
    $dimensions = [
      'width' => $image->getWidth(),
      'height' => $image->getHeight(),
    ];

    // Transform the 'width' and 'height' dimensions of the image based on
    // the image style.
    if ($image_style) {
      $image_style->transformDimensions($dimensions, $attributes['src']);
      $attributes['width'] = $dimensions['width'];
      $attributes['height'] = $dimensions['height'];
    }
    else {
      // We must explicitly set to NULL (and not unset) for CKEditor to take
      // the change into account.
      foreach (['width', 'height', 'data-image-style'] as $key) {
        $attributes[$key] = NULL;
      }
    }
  }
  $form_state->setValue('attributes', $attributes);
}
