<?php

/**
 * @file
 * A module to add a custom image type for CKEditor5.
 */

use Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition;

/**
 * Implements hook_ckeditor5_plugin_info_alter().
 */
function ckeditor5_test_module_allowed_image_ckeditor5_plugin_info_alter(array &$plugin_definitions): void {
  // Add a custom file type to the image upload plugin. Note that 'svg+xml'
  // below should be an IANA image media type Name, with the "image/" prefix
  // omitted. In other words: a subtype of type image.
  // @see https://www.iana.org/assignments/media-types/media-types.xhtml#image
  // @see https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageconfig-ImageUploadConfig.html#member-types
  $imageUploadPlugin = $plugin_definitions['ckeditor5_imageUpload']->toArray();
  $imageUploadPlugin['ckeditor5']['config']['image']['upload']['types'][] = 'svg+xml';
  $plugin_definitions['ckeditor5_imageUpload'] = new CKEditor5PluginDefinition($imageUploadPlugin);
}
