<?php

/**
 * @file
 * A module to add a custom image type for CKEditor5.
 */

use Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition;

/**
 * Implements hook_ckeditor5_image_controller_extensions_alter().
 */
function ckeditor5_test_module_allowed_image_ckeditor5_image_controller_extensions_alter(array &$extensions): void {
  // The following array values should be the file name extensions to be
  // validated by the image upload controller.
  // @see https://www.drupal.org/node/3363700
  $extensions[] = 'svg';
}

/**
 * Implements hook_ckeditor5_plugin_info_alter().
 */
function ckeditor5_test_module_allowed_image_ckeditor5_plugin_info_alter(array &$plugin_definitions): void {
  // Add a custom file type to the image upload plugin. Note that 'svg+xml' below
  // should be an IANA image media type Name.
  // @see https://www.iana.org/assignments/media-types/media-types.xhtml#image
  // @see https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageconfig-ImageUploadConfig.html#member-types
  $imageUploadPlugin = $plugin_definitions['ckeditor5_imageUpload']->toArray();
  $imageUploadPlugin['ckeditor5']['config']['image']['upload']['types'][] = 'svg+xml';
  $plugin_definitions['ckeditor5_imageUpload'] = new CKEditor5PluginDefinition($imageUploadPlugin);
}
