/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

((Drupal, once) => {
  let primaryNavigationRegion;
  let mobileNavigationButton;
  let secondLevelNavMenus;
  let secondLevelToggleButtonSelector;

  function isDesktopNav() {
    return mobileNavigationButton.clientHeight === 0;
  }

  function isMobileNavExpanded() {
    return !isDesktopNav() && primaryNavigationRegion.classList.contains('is-expanded');
  }

  function toggleSubNav(topLevelMenuItem, toState) {
    const button = topLevelMenuItem.querySelector(secondLevelToggleButtonSelector);
    const secondLevelMenuSelector = '[data-drupal-selector="main-nav-menu--level-2"]';
    const state = toState !== undefined ? toState : button.getAttribute('aria-expanded') !== 'true';

    if (state) {
      if (isDesktopNav()) {
        secondLevelNavMenus.forEach(el => {
          el.querySelector(secondLevelToggleButtonSelector).setAttribute('aria-expanded', 'false');
          el.querySelector(secondLevelMenuSelector).classList.remove('is-active-menu-parent');
        });
      }

      button.setAttribute('aria-expanded', 'true');
      topLevelMenuItem.querySelector(secondLevelMenuSelector).classList.add('is-active-menu-parent');
    } else {
      button.setAttribute('aria-expanded', 'false');
      topLevelMenuItem.classList.remove('is-touch-event');
      topLevelMenuItem.querySelector(secondLevelMenuSelector).classList.remove('is-active-menu-parent');
    }
  }

  function handleSecondLevelBlur(e) {
    if (!isDesktopNav()) return;
    setTimeout(() => {
      const menuParentItem = e.target.closest('[data-drupal-selector="main-nav-menu-item-has-children"]');

      if (!menuParentItem.contains(document.activeElement)) {
        toggleSubNav(menuParentItem, false);
      }
    }, 200);
  }

  function initSecondLevelNav(secondLevelNavMenus) {
    secondLevelNavMenus.forEach(el => {
      const button = el.querySelector(secondLevelToggleButtonSelector);
      el.addEventListener('touchstart', () => {
        el.classList.add('is-touch-event');
      }, {
        passive: true
      });
      el.addEventListener('mouseover', () => {
        if (isDesktopNav() && !el.classList.contains('is-touch-event')) {
          el.classList.add('is-active-mouseover-event');
          toggleSubNav(el, true);
          setTimeout(() => {
            el.classList.remove('is-active-mouseover-event');
          }, 500);
        }
      });
      button.addEventListener('click', () => {
        if (!el.classList.contains('is-active-mouseover-event')) {
          toggleSubNav(el);
        }
      });
      el.addEventListener('mouseout', () => {
        if (isDesktopNav() && !document.activeElement.matches('[aria-expanded="true"], .is-active-menu-parent *')) {
          toggleSubNav(el, false);
        }
      });
      el.addEventListener('blur', handleSecondLevelBlur, true);
    });
  }

  function closeAllSubNav() {
    secondLevelNavMenus.forEach(el => {
      if (el.contains(document.activeElement)) {
        el.querySelector(secondLevelToggleButtonSelector).focus();
      }

      toggleSubNav(el, false);
    });
  }

  function toggleMobileNav(toState) {
    if (primaryNavigationRegion.contains(document.activeElement)) {
      mobileNavigationButton.focus();
    }

    document.body.classList.toggle('is-active-mobile-menu', toState);
    mobileNavigationButton.setAttribute('aria-expanded', toState);
    primaryNavigationRegion.classList.toggle('is-expanded', toState);
  }

  function handleMobileNavigationButtonClick(e) {
    const isExpanded = e.currentTarget.getAttribute('aria-expanded') === 'true';
    toggleMobileNav(!isExpanded);
  }

  function focusTrap(e) {
    if (e.key === 'Tab' && isMobileNavExpanded()) {
      const tabbableNavElements = tabbable.tabbable(primaryNavigationRegion);
      tabbableNavElements.unshift(mobileNavigationButton);
      const firstTabbableEl = tabbableNavElements[0];
      const lastTabbableEl = tabbableNavElements[tabbableNavElements.length - 1];

      if (e.shiftKey) {
        if (document.activeElement === firstTabbableEl) {
          lastTabbableEl.focus();
          e.preventDefault();
        }
      } else if (document.activeElement === lastTabbableEl) {
        firstTabbableEl.focus();
        e.preventDefault();
      }
    }
  }

  function init(el) {
    primaryNavigationRegion = el;
    mobileNavigationButton = document.querySelector('[data-drupal-selector="main-nav__mobile-button"]');
    secondLevelNavMenus = primaryNavigationRegion.querySelectorAll('[data-drupal-selector="main-nav-menu-item-has-children"]');
    secondLevelToggleButtonSelector = '[data-drupal-selector="main-nav-submenu-toggle-button"], button[data-drupal-selector="main-nav-menu-link-has-children"]';
    initSecondLevelNav(secondLevelNavMenus);
    document.addEventListener('keyup', e => {
      if (e.key === 'Escape') {
        closeAllSubNav();
        toggleMobileNav(false);
      }
    });
    document.body.addEventListener('keydown', focusTrap);
    document.querySelector('[data-drupal-selector="main-nav-overlay"]').addEventListener('click', () => {
      toggleMobileNav(false);
    });
    window.addEventListener('resize', () => {
      toggleMobileNav(false);
      closeAllSubNav();
    });
    mobileNavigationButton.setAttribute('aria-expanded', 'false');
    mobileNavigationButton.setAttribute('aria-controls', primaryNavigationRegion.getAttribute('id'));
    mobileNavigationButton.addEventListener('click', handleMobileNavigationButtonClick);
    document.addEventListener('touchstart', e => {
      if (!e.target.matches('[data-drupal-selector="main-nav-menu--level-1"] *')) {
        closeAllSubNav();
      }
    }, {
      passive: true
    });
    primaryNavigationRegion.addEventListener('click', e => {
      if (e.target.matches(`[href*="${window.location.pathname}#"], [href*="${window.location.pathname}#"] *, [href^="#"], [href^="#"] *`)) {
        toggleMobileNav(false);
      }
    });
  }

  Drupal.behaviors.mainNav = {
    attach(context) {
      once('main-nav', '[data-drupal-selector="region-primary-navigation"]', context).forEach(init);
    }

  };
})(Drupal, once);