<?php

/**
 * @file
 * Install hooks for test module.
 */

use Drupal\Core\Extension\Requirement\RequirementSeverity;

/**
 * Implements hook_requirements().
 */
function requirements1_test_requirements($phase) {
  $requirements = [];

  // Always fails requirements.
  if ('install' == $phase) {
    $requirements['requirements1_test'] = [
      'title' => t('Requirements 1 Test'),
      'severity' => RequirementSeverity::ERROR,
      'description' => t('Requirements 1 Test failed requirements.'),
    ];
  }

  $requirements['requirements1_test_alterable'] = [
    'title' => t('Requirements 1 Test Alterable'),
    'severity' => RequirementSeverity::ERROR,
    'description' => t('A requirement that will be altered.'),
  ];

  $requirements['requirements1_test_deletable'] = [
    'title' => t('Requirements 1 Test Deletable'),
    'severity' => RequirementSeverity::INFO,
    'description' => t('A requirement that will be deleted.'),
  ];

  return $requirements;
}
