<?php

/**
 * @file
 * Install, update and uninstall functions for the mongodb module.
 */

use Drupal\Core\Database\Database;

/**
 * Implements hook_requirements().
 */
function mongodb_requirements($phase) {
  $requirements = [];
  // Test with MongoDB databases for the being used as a replica set.
  if (Database::isActiveConnection()) {
    $connection = Database::getConnection();

    // Set the requirement just for MongoDB.
    if ($connection->driver() == 'mongodb') {
      // If the MongoDB database is not set up as a replica set.
      if ($set = $connection->getReplicaSetName()) {
        $requirements['mongodb_replica_set'] = [
          'severity' => REQUIREMENT_OK,
          'title' => t('MongoDB replica set'),
          'value' => $set,
          'description' => 'The MongoDB database is set up with a replica set.',
        ];
      }
      else {
        $requirements['mongodb_replica_set']['severity'] = REQUIREMENT_ERROR;
        $requirements['mongodb_replica_set']['value'] = t('Not available');
        $requirements['mongodb_replica_set']['description'] = t('The MongoDB is not set up with a <a href=":replication">replica set</a>. Replica sets offer support for multi document <a href=":transactions">transactions</a>, which is needed by Drupal.', [
          ':replication' => 'https://www.mongodb.com/docs/manual/replication/',
          ':transactions' => 'https://www.mongodb.com/docs/manual/core/transactions/',
        ]);
      }
    }
  }

  return $requirements;
}

/**
 * Implements hook_schema().
 */
function mongodb_schema(): array {
  // Install the semaphore table directly instead of doing it the lazy way. The
  // lazy creation of this table creates a lot of watchdog messages during
  // install.
  $schema['semaphore'] = [
    'description' => 'Table for holding semaphores, locks, flags, etc. that cannot be stored as state since they must not be cached.',
    'fields' => [
      'name' => [
        'description' => 'Primary Key: Unique name.',
        'type' => 'varchar_ascii',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ],
      'value' => [
        'description' => 'A value for the semaphore.',
        'type' => 'varchar_ascii',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ],
      'expire' => [
        'description' => 'A Unix timestamp with microseconds indicating when the semaphore should expire.',
        'type' => 'float',
        'size' => 'big',
        'not null' => TRUE,
      ],
    ],
    'indexes' => [
      'value' => ['value'],
      'expire' => ['expire'],
    ],
    'primary key' => ['name'],
  ];
  return $schema;
}
