<?php

/**
 * @file
 * The MongoDB module provides the connection between Drupal and a MongoDB database.
 */

use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Database\Query\ConditionInterface;
use Drupal\Core\Database\Query\SelectInterface;

/**
 * Implements hook_search_plugin_alter().
 */
function mongodb_search_plugin_alter(array &$definitions) {
  if (isset($definitions['help_search'])) {
    $definitions['help_search']['class'] = 'Drupal\mongodb\Plugin\Search\HelpSearch';
    $definitions['help_search']['provider'] = 'mongodb';
  }
  if (isset($definitions['node_search'])) {
    $definitions['node_search']['class'] = 'Drupal\mongodb\Plugin\Search\NodeSearch';
    $definitions['node_search']['provider'] = 'mongodb';
  }
  if (isset($definitions['user_search'])) {
    $definitions['user_search']['class'] = 'Drupal\mongodb\Plugin\Search\UserSearch';
    $definitions['user_search']['provider'] = 'mongodb';
  }
}

/**
 * Implements hook_query_TAG_alter().
 */
function mongodb_query_entity_reference_alter(AlterableInterface $query) {
  // Overrides for the module content_moderation.
  if (\Drupal::moduleHandler()->moduleExists('block_content')) {
    if ($query instanceof SelectInterface && $query->getMetaData('entity_type') === 'block_content' && $query->hasTag('block_content_access')) {
      if (!_mongodb_block_content_has_reusable_condition($query->conditions(), $query->getTables())) {
        $query->condition('block_content_current_revision.reusable', TRUE);
      }
    }
  }
}

/**
 * Utility function is the MongoDB version of _block_content_has_reusable_condition.
 */
function _mongodb_block_content_has_reusable_condition(array $condition, array $tables) {
  // If this is a condition group call this function recursively for each nested
  // condition until a condition is found that return TRUE.
  if (isset($condition['#conjunction'])) {
    foreach (array_filter($condition, 'is_array') as $nested_condition) {
      if (_mongodb_block_content_has_reusable_condition($nested_condition, $tables)) {
        return TRUE;
      }
    }
    return FALSE;
  }
  if (isset($condition['field'])) {
    $field = $condition['field'];
    if (is_object($field) && $field instanceof ConditionInterface) {
      return _mongodb_block_content_has_reusable_condition($field->conditions(), $tables);
    }
    $base_table = \Drupal::entityTypeManager()->getDefinition('block_content')->getBaseTable();
    foreach ($tables as $table) {
      if ($table['table'] === $base_table && $field === 'block_content_current_revision.reusable') {
        return TRUE;
      }
    }
  }
  return FALSE;
}
