<?php

/**
 * @file
 */

use Drupal\content_moderation\ContentPreprocess;
use Drupal\workflows\WorkflowInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function content_moderation_preprocess_node(&$variables): void {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(ContentPreprocess::class)
    ->preprocessNode($variables);
}

/**
 * Creates or updates moderation state change actions for a given workflow.
 */
function content_moderation_save_workflow_actions(WorkflowInterface $workflow) : void {
  $workflow_base_action_id = 'content_moderation_' . $workflow->id();
  $entity_types = $workflow->getTypePlugin()->getEntityTypes();
  foreach ($entity_types as $entity_type_id) {
    // Omit unsupported entity types.
    $entity_type = \Drupal::entityTypeManager()->getDefinition($entity_type_id);
    if (!\Drupal::service('content_moderation.moderation_information')->canModerateEntitiesOfEntityType($entity_type)) {
      continue;
    }
    foreach ($workflow->getTypePlugin()->getStates() as $state_id => $state) {
      $action_id = $workflow_base_action_id . '_' . $entity_type_id . '_change_to_' . $state_id;
      $action = \Drupal::entityTypeManager()->getStorage('action')->load($action_id);
      if (!$action) {
        $action = \Drupal::entityTypeManager()->getStorage('action')->create([
          'id' => $action_id,
          'type' => $entity_type_id,
          'label' => t('Change moderation state to @state', ['@state' => $state->label()]),
          'configuration' => [
            'workflow' => $workflow->id(),
            'state' => $state_id,
            'revision_log_message' => t('Change moderation state to @state', ['@state' => $state->label()]),
          ],
          'plugin' => 'moderation_state_change:' . $entity_type_id,
          'dependencies' => [
            'config' => ['workflows.workflow.' . $workflow->id()],
          ],
        ]);
      }
      else {
        $action->set('label', t('Change moderation state to @state', ['@state' => $state->label()]));
        $action->set('configuration', [
          'workflow' => $workflow->id(),
          'state' => $state_id,
          'revision_log_message' => t('Change moderation state to @state', ['@state' => $state->label()]),
        ]);
        $action->set('dependencies', [
          'config' => ['workflows.workflow.' . $workflow->id()],
        ]);
      }
      $action->save();
    }
  }
}
