<?php

/**
 * @file
 * Install, update and uninstall functions for the Content Moderation module.
 */

/**
 * Implements hook_update_last_removed().
 */
function content_moderation_update_last_removed() {
  return 8700;
}

function content_moderation_update_9200() {
  $manager = \Drupal::entityDefinitionUpdateManager();

  $base_field_definition = $manager->getFieldStorageDefinition('moderation_state', 'content_moderation_state');
  $manager->updateFieldStorageDefinition($base_field_definition);
}
