name: 'Content Moderation'
description: 'Adds permissions to standard user roles for the Content Moderation module.'
type: 'Users'
install:
  - content_moderation
config:
  import:
    standard:
      - workflows.workflow.editorial
  actions:
    user.role.content_editor:
      grantPermissions:
        - 'view any unpublished content'
        - 'view latest version'
        - 'use editorial transition archive'
        - 'use editorial transition archived_draft'
        - 'use editorial transition archived_published'
        - 'use editorial transition create_new_draft'
        - 'use editorial transition publish'
